// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Typed schema for the daemon's configuration.
//!
//! The types in this module are generated by prost from
//! `../../api/unbounded-storage/config.proto` (see `build.rs`) and pulled
//! in via the `include!` below. The `.proto` is the schema source of truth.
//!
//! The schema is proto3-native: byte sizes are plain integers, and fields
//! with documented defaults use proto3 `optional` presence. [`Config::apply_defaults`]
//! runs after deserialization and fills absent values with the documented
//! defaults. Section messages are `Option` in prost and are guaranteed
//! `Some` after `apply_defaults`, so the section accessors below never panic.
//!
//! The TOML loader is strict: each message derives
//! `#[serde(default, deny_unknown_fields)]`, so an unknown key fails
//! loudly at parse time. This strictness applies only to the TOML path;
//! decoding a protobuf wire message keeps
//! protobuf's forward-compatible unknown-field semantics.

include!(concat!(env!("OUT_DIR"), "/unbounded.storage.config.rs"));

const DEFAULT_STRIPE_SIZE_BYTES: u64 = 4 * 1024 * 1024;
const DEFAULT_HTTP_CONCURRENCY: u32 = 64;
pub const DEFAULT_HTTP_FRONTEND_MAX_REQUESTS_PER_CONNECTION: u32 = 1024;
const DEFAULT_FAKE_OBJECT_SIZE_BYTES: u64 = 1024 * 1024;

impl Config {
    /// Populates every omitted section and optional defaulted field with
    /// documented defaults. Idempotent: a field already set, including an
    /// explicit zero, is left untouched. Run once after load (or after
    /// decoding a protobuf message) before the config is consumed.
    pub fn apply_defaults(&mut self) {
        self.fingers_per_node.get_or_insert(100);

        for backend in &mut self.backends {
            backend.apply_defaults();
        }

        for frontend in &mut self.frontends {
            frontend.apply_defaults();
        }

        let startup = self.startup.get_or_insert_with(StartupCfg::default);

        let memory = startup.memory.get_or_insert_with(MemoryCfg::default);
        memory.memory_total_bytes.get_or_insert(128 * 1024 * 1024);

        let fabric = startup.fabric.get_or_insert_with(FabricCfg::default);
        match fabric.binds.as_mut() {
            Some(fabric_cfg::Binds::Tcp(tcp)) if tcp.addr.is_empty() => {
                tcp.addr = "0.0.0.0:0".to_string();
            }
            Some(fabric_cfg::Binds::AutoRdma(auto)) => {
                auto.hcas_per_numa_node.get_or_insert(1);
            }
            Some(fabric_cfg::Binds::Tcp(_)) | Some(fabric_cfg::Binds::Rdma(_)) => {}
            None => {
                fabric.binds = Some(fabric_cfg::Binds::Tcp(TcpFabricBinds {
                    addr: "0.0.0.0:0".to_string(),
                }));
            }
        }
        fabric.progress_threads.get_or_insert(2);
        fabric.progress_poll_us.get_or_insert(10);
        fabric.rpc_worker_threads.get_or_insert(4);
        fabric.max_inflight.get_or_insert(1024);

        let topology = startup.topology.get_or_insert_with(TopologyCfg::default);
        topology.nic_workers.get_or_insert(4);
        // `serving_cores = None` means auto-fill every usable core.

        // Metrics: the exporter is opt-in, so an empty addr (the proto3
        // zero value) is the intended "disabled" default and is left as
        // is. Materialize the section so the accessor never panics.
        startup.metrics.get_or_insert_with(MetricsCfg::default);
    }

    /// Startup-fixed settings section. Panics if called before
    /// [`Config::apply_defaults`]; always valid after `load`. The nested
    /// `memory`/`fabric`/`topology` sections are likewise guaranteed
    /// `Some` once defaults have been applied.
    pub fn startup(&self) -> &StartupCfg {
        self.startup.as_ref().expect("startup section populated")
    }
}

impl BackendSpec {
    fn apply_defaults(&mut self) {
        match self.config.as_mut() {
            Some(backend_spec::Config::Http(cfg)) => {
                apply_http_backend_defaults(&mut cfg.stripe_size_bytes, &mut cfg.http_concurrency)
            }
            Some(backend_spec::Config::S3(cfg)) => {
                apply_http_backend_defaults(&mut cfg.stripe_size_bytes, &mut cfg.http_concurrency)
            }
            Some(backend_spec::Config::Azure(cfg)) => {
                apply_http_backend_defaults(&mut cfg.stripe_size_bytes, &mut cfg.http_concurrency)
            }
            Some(backend_spec::Config::Fake(cfg)) => {
                cfg.stripe_size_bytes
                    .get_or_insert(DEFAULT_STRIPE_SIZE_BYTES);
                cfg.object_size_bytes
                    .get_or_insert(DEFAULT_FAKE_OBJECT_SIZE_BYTES);
            }
            None => {}
        }
    }

    pub fn kind_name(&self) -> &'static str {
        match self.config {
            Some(backend_spec::Config::Http(_)) => "http",
            Some(backend_spec::Config::S3(_)) => "s3",
            Some(backend_spec::Config::Azure(_)) => "azure",
            Some(backend_spec::Config::Fake(_)) => "fake",
            None => "missing",
        }
    }

    pub fn stripe_size_bytes(&self) -> u64 {
        match self.config.as_ref() {
            Some(backend_spec::Config::Http(cfg)) => cfg.stripe_size_bytes.unwrap_or(0),
            Some(backend_spec::Config::S3(cfg)) => cfg.stripe_size_bytes.unwrap_or(0),
            Some(backend_spec::Config::Azure(cfg)) => cfg.stripe_size_bytes.unwrap_or(0),
            Some(backend_spec::Config::Fake(cfg)) => cfg.stripe_size_bytes.unwrap_or(0),
            None => 0,
        }
    }

    pub fn url(&self) -> Option<&str> {
        match self.config.as_ref() {
            Some(backend_spec::Config::Http(cfg)) => Some(cfg.url.as_str()),
            Some(backend_spec::Config::S3(cfg)) => Some(cfg.url.as_str()),
            Some(backend_spec::Config::Azure(cfg)) => Some(cfg.url.as_str()),
            Some(backend_spec::Config::Fake(_)) | None => None,
        }
    }

    pub fn http_concurrency(&self) -> Option<u32> {
        match self.config.as_ref() {
            Some(backend_spec::Config::Http(cfg)) => cfg.http_concurrency,
            Some(backend_spec::Config::S3(cfg)) => cfg.http_concurrency,
            Some(backend_spec::Config::Azure(cfg)) => cfg.http_concurrency,
            Some(backend_spec::Config::Fake(_)) | None => None,
        }
    }
}

impl PeerSpec {
    pub fn transport_name(&self) -> &'static str {
        match self.config {
            Some(peer_spec::Config::Tcp(_)) => "tcp",
            Some(peer_spec::Config::Rdma(_)) => "rdma",
            None => "missing",
        }
    }

    pub fn wire_addr(&self) -> Option<&str> {
        match self.config.as_ref() {
            Some(peer_spec::Config::Tcp(cfg)) => Some(cfg.addr.as_str()),
            Some(peer_spec::Config::Rdma(cfg)) => Some(cfg.addr.as_str()),
            None => None,
        }
    }
}

impl FabricCfg {
    pub fn default_listen_addr(&self) -> Option<&str> {
        match self.binds.as_ref() {
            Some(fabric_cfg::Binds::Tcp(cfg)) => Some(cfg.addr.as_str()),
            Some(fabric_cfg::Binds::Rdma(cfg)) => cfg.binds.first().map(|bind| bind.addr.as_str()),
            Some(fabric_cfg::Binds::AutoRdma(_)) => Some("0.0.0.0:0"),
            None => None,
        }
    }

    pub fn auto_hcas_per_numa_node(&self) -> Option<u64> {
        match self.binds.as_ref() {
            Some(fabric_cfg::Binds::AutoRdma(cfg)) => cfg.hcas_per_numa_node,
            Some(fabric_cfg::Binds::Tcp(_)) | Some(fabric_cfg::Binds::Rdma(_)) | None => None,
        }
    }

    pub fn rdma_listen_addrs(&self) -> impl Iterator<Item = &str> {
        self.binds
            .as_ref()
            .into_iter()
            .filter_map(|binds| match binds {
                fabric_cfg::Binds::Rdma(cfg) => Some(cfg.binds.as_slice()),
                fabric_cfg::Binds::Tcp(_) | fabric_cfg::Binds::AutoRdma(_) => None,
            })
            .flatten()
            .map(|bind| bind.addr.as_str())
    }
}

impl DiskSpec {
    pub fn kind_name(&self) -> &'static str {
        match self.config {
            Some(disk_spec::Config::Block(_)) => "block",
            Some(disk_spec::Config::File(_)) => "file",
            None => "missing",
        }
    }

    pub fn is_file(&self) -> bool {
        matches!(self.config, Some(disk_spec::Config::File(_)))
    }

    pub fn file_size(&self) -> Option<u64> {
        match self.config.as_ref() {
            Some(disk_spec::Config::File(cfg)) => cfg.size,
            Some(disk_spec::Config::Block(_)) | None => None,
        }
    }

    pub fn path(&self) -> Option<&str> {
        match self.config.as_ref() {
            Some(disk_spec::Config::Block(cfg)) => Some(cfg.path.as_str()),
            Some(disk_spec::Config::File(cfg)) => Some(cfg.path.as_str()),
            None => None,
        }
    }

    pub fn numa(&self) -> Option<u32> {
        match self.config.as_ref() {
            Some(disk_spec::Config::Block(cfg)) => cfg.numa,
            Some(disk_spec::Config::File(_)) | None => None,
        }
    }
}

impl FrontendSpec {
    fn apply_defaults(&mut self) {
        if let Some(frontend_spec::Config::Http(cfg)) = self.config.as_mut() {
            cfg.max_requests_per_connection
                .get_or_insert(DEFAULT_HTTP_FRONTEND_MAX_REQUESTS_PER_CONNECTION);
        }
    }

    pub fn kind_name(&self) -> &'static str {
        match self.config {
            Some(frontend_spec::Config::Http(_)) => "http",
            Some(frontend_spec::Config::S3(_)) => "s3",
            Some(frontend_spec::Config::Loadgen(_)) => "loadgen",
            None => "missing",
        }
    }

    pub fn addr(&self) -> Option<&str> {
        match self.config.as_ref() {
            Some(frontend_spec::Config::Http(cfg)) => Some(cfg.addr.as_str()),
            Some(frontend_spec::Config::S3(cfg)) => Some(cfg.addr.as_str()),
            Some(frontend_spec::Config::Loadgen(_)) | None => None,
        }
    }

    pub fn max_requests_per_connection(&self) -> Option<u32> {
        match self.config.as_ref() {
            Some(frontend_spec::Config::Http(cfg)) => cfg.max_requests_per_connection,
            Some(frontend_spec::Config::S3(_)) | Some(frontend_spec::Config::Loadgen(_)) | None => {
                None
            }
        }
    }
}

fn apply_http_backend_defaults(
    stripe_size_bytes: &mut Option<u64>,
    http_concurrency: &mut Option<u32>,
) {
    stripe_size_bytes.get_or_insert(DEFAULT_STRIPE_SIZE_BYTES);
    http_concurrency.get_or_insert(DEFAULT_HTTP_CONCURRENCY);
}

impl StartupCfg {
    /// Memory section. Valid after [`Config::apply_defaults`].
    pub fn memory(&self) -> &MemoryCfg {
        self.memory.as_ref().expect("memory section populated")
    }

    /// Fabric section. Valid after [`Config::apply_defaults`].
    pub fn fabric(&self) -> &FabricCfg {
        self.fabric.as_ref().expect("fabric section populated")
    }

    /// Topology section. Valid after [`Config::apply_defaults`].
    pub fn topology(&self) -> &TopologyCfg {
        self.topology.as_ref().expect("topology section populated")
    }

    /// Metrics section. Valid after [`Config::apply_defaults`].
    pub fn metrics(&self) -> &MetricsCfg {
        self.metrics.as_ref().expect("metrics section populated")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_are_populated() {
        let mut c: Config = toml::from_str("").unwrap();
        c.apply_defaults();
        assert_eq!(c.version, 0);
        assert!(c.peers.is_empty());
        assert!(c.caches.is_empty());
        assert!(c.backends.is_empty());
        assert!(c.frontends.is_empty());
        assert_eq!(c.fingers_per_node, Some(100));
    }

    #[test]
    fn metrics_section_defaults_to_disabled() {
        let mut c: Config = toml::from_str("").unwrap();
        c.apply_defaults();
        // The exporter is opt-in: the addr stays empty unless configured.
        assert_eq!(c.startup().metrics().addr, "");
    }

    #[test]
    fn fabric_binds_round_trip() {
        let s = r#"
[startup.fabric]
max_inflight = 2048

[startup.fabric.binds.rdma]

[[startup.fabric.binds.rdma.binds]]
addr = "192.168.252.1:49151"

[[startup.fabric.binds.rdma.binds]]
addr = "192.168.253.1:49151"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();

        let fabric = c.startup().fabric();
        assert_eq!(fabric.default_listen_addr(), Some("192.168.252.1:49151"));
        let binds: Vec<_> = fabric.rdma_listen_addrs().collect();
        assert_eq!(binds.len(), 2);
        assert_eq!(binds[0], "192.168.252.1:49151");
        assert_eq!(binds[1], "192.168.253.1:49151");
    }

    #[test]
    fn auto_rdma_bind_defaults_hca_cap() {
        let s = r#"
[startup.fabric]

[startup.fabric.binds.auto_rdma]
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();

        let fabric = c.startup().fabric();
        assert_eq!(fabric.default_listen_addr(), Some("0.0.0.0:0"));
        assert_eq!(fabric.auto_hcas_per_numa_node(), Some(1));
    }

    #[test]
    fn version_round_trips() {
        // The top-level `version` is an opaque operator-assigned counter;
        // it round-trips verbatim and is not touched by `apply_defaults`.
        let mut c: Config = toml::from_str("version = 7\n").unwrap();
        c.apply_defaults();
        assert_eq!(c.version, 7);
    }

    #[test]
    fn unknown_fields_are_rejected() {
        // The TOML loader is strict: an unknown key fails loudly at parse
        // time (deny_unknown_fields) so operator typos are caught rather
        // than silently dropped.
        assert!(toml::from_str::<Config>("nonsense = 1\n").is_err());
    }

    #[test]
    fn block_disk_config_round_trips() {
        let s = r#"
[[disks]]
[disks.config.block]
path = "/dev/nvme0n1"
numa = 1
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.disks[0].kind_name(), "block");
        assert_eq!(c.disks[0].path(), Some("/dev/nvme0n1"));
        assert_eq!(c.disks[0].numa(), Some(1));
    }

    #[test]
    fn disk_engine_fields_default_to_unset_and_off() {
        let s = r#"
[[disks]]
[disks.config.block]
path = "/dev/nvme0n1"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.disks[0].page_size_bytes, None);
        assert!(!c.disks[0].skip_recovery_scan);
    }

    #[test]
    fn disk_engine_fields_round_trip() {
        let s = r#"
[[disks]]
page_size_bytes = 4096
skip_recovery_scan = true

[disks.config.block]
path = "/dev/nvme0n1"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.disks[0].page_size_bytes, Some(4096));
        assert!(c.disks[0].skip_recovery_scan);
    }

    #[test]
    fn mesh_round_trips() {
        let s = r#"
fingers_per_node = 128
self = "node-a"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.fingers_per_node, Some(128));
        assert_eq!(c.self_, "node-a");
    }

    #[test]
    fn routing_plan_round_trips() {
        let s = r#"
self = "node-a"

[routing_plan]
fingers = ["node-b", "node-c", "node-d", "node-e"]
successor = "node-b"
predecessor = "node-z"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        let plan = c.routing_plan.as_ref().expect("routing_plan set");
        assert_eq!(
            plan.fingers,
            vec![
                "node-b".to_string(),
                "node-c".to_string(),
                "node-d".to_string(),
                "node-e".to_string(),
            ]
        );
        assert_eq!(plan.successor.as_deref(), Some("node-b"));
        assert_eq!(plan.predecessor.as_deref(), Some("node-z"));
    }

    #[test]
    fn routing_plan_absent_by_default() {
        let mut c: Config = toml::from_str("self = \"node-a\"\n").unwrap();
        c.apply_defaults();
        assert!(c.routing_plan.is_none());
    }

    #[test]
    fn peer_tags_round_trip() {
        let s = r#"
[[peers]]
name = "node-a"
tags = ["us-west", "az1", "row3", "rack7"]

[peers.config.tcp]
addr = "127.0.0.1:9000"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(
            c.peers[0].tags,
            vec![
                "us-west".to_string(),
                "az1".to_string(),
                "row3".to_string(),
                "rack7".to_string(),
            ]
        );
    }

    #[test]
    fn backend_and_frontend_round_trip() {
        let s = r#"
[[backends]]
name = "primary-http"

[backends.config.http]
url = "https://origin.example.com"
stripe_size_bytes = 8388608
http_concurrency = 32

[[frontends]]
name = "workload-http"
source = "primary-http"

[frontends.config.http]
addr = "0.0.0.0:9000"
max_requests_per_connection = 256
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.backends.len(), 1);
        let b = &c.backends[0];
        assert_eq!(b.name, "primary-http");
        match b.config.as_ref().expect("backend config set") {
            backend_spec::Config::Http(cfg) => {
                assert_eq!(cfg.url, "https://origin.example.com");
                assert_eq!(cfg.stripe_size_bytes, Some(8 * 1024 * 1024));
                assert_eq!(cfg.http_concurrency, Some(32));
                assert_eq!(cfg.ca_cert_path, None);
                assert!(!cfg.insecure_skip_verify);
            }
            other => panic!("expected http backend config, got {other:?}"),
        }

        assert_eq!(c.frontends.len(), 1);
        let f = &c.frontends[0];
        assert_eq!(f.name, "workload-http");
        assert_eq!(f.addr(), Some("0.0.0.0:9000"));
        assert_eq!(f.max_requests_per_connection(), Some(256));
        assert_eq!(f.source, "primary-http");
    }

    #[test]
    fn cache_and_frontend_binding_round_trip() {
        let s = r#"
[[caches]]
name = "cache"
source = "backend"

[[frontends]]
name = "cached-http"
source = "cache"

[frontends.config.http]
addr = "0.0.0.0:9000"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.caches[0].name, "cache");
        assert_eq!(c.frontends[0].source, "cache");
    }

    #[test]
    fn backend_optional_fields_default() {
        let s = r#"
[[backends]]
name = "b"

[backends.config.http]
url = "https://example.com"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        match c.backends[0].config.as_ref().expect("backend config set") {
            backend_spec::Config::Http(cfg) => {
                assert_eq!(cfg.stripe_size_bytes, Some(4 * 1024 * 1024));
                assert_eq!(cfg.http_concurrency, Some(64));
                assert_eq!(cfg.ca_cert_path, None);
                assert!(!cfg.insecure_skip_verify);
            }
            other => panic!("expected http backend config, got {other:?}"),
        }
    }

    #[test]
    fn http_frontend_optional_fields_default() {
        let s = r#"
[[frontends]]
name = "f"
source = "b"

[frontends.config.http]
addr = "0.0.0.0:9000"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(
            c.frontends[0].max_requests_per_connection(),
            Some(DEFAULT_HTTP_FRONTEND_MAX_REQUESTS_PER_CONNECTION)
        );
    }

    #[test]
    fn s3_backend_round_trips() {
        let s = r#"
[[backends]]
name = "primary-s3"

[backends.config.s3]
url = "https://s3.us-east-1.amazonaws.com:443"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.backends[0].kind_name(), "s3");
        assert_eq!(
            c.backends[0].url(),
            Some("https://s3.us-east-1.amazonaws.com:443")
        );
    }

    #[test]
    fn s3_frontend_round_trips() {
        let s = r#"
[[frontends]]
name = "workload-s3"
source = "b"

[frontends.config.s3]
addr = "0.0.0.0:9000"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.frontends[0].kind_name(), "s3");
        assert_eq!(c.frontends[0].addr(), Some("0.0.0.0:9000"));
    }

    #[test]
    fn loadgen_frontend_round_trips() {
        let s = r#"
[[frontends]]
name = "synthetic"
source = "cache"

[frontends.config.loadgen]
workers = 8
seed = 1234
keyspace_objects = 4096
object_size_bytes = 1048576
read_bytes = 131072
zipf_exponent = 1.2
verify = true
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();

        let f = &c.frontends[0];
        assert_eq!(f.kind_name(), "loadgen");
        assert_eq!(f.addr(), None);
        assert_eq!(f.source, "cache");

        let loadgen = match f.config.as_ref().expect("loadgen config set") {
            frontend_spec::Config::Loadgen(cfg) => cfg,
            other => panic!("expected loadgen frontend config, got {other:?}"),
        };
        assert_eq!(loadgen.workers, Some(8));
        assert_eq!(loadgen.seed, Some(1234));
        assert_eq!(loadgen.keyspace_objects, Some(4096));
        assert_eq!(loadgen.object_size_bytes, Some(1024 * 1024));
        assert_eq!(loadgen.read_bytes, Some(128 * 1024));
        assert_eq!(loadgen.zipf_exponent, Some(1.2));
        assert!(loadgen.verify);
    }

    #[test]
    fn unknown_loadgen_fields_are_rejected() {
        let s = r#"
[[frontends]]
name = "synthetic"
source = "cache"

[frontends.config.loadgen]
workerz = 8
"#;
        assert!(toml::from_str::<Config>(s).is_err());
    }

    #[test]
    fn startup_defaults_are_populated() {
        let mut c: Config = toml::from_str("").unwrap();
        c.apply_defaults();
        let s = c.startup();
        assert!(!s.memory().no_hugepages);
        assert_eq!(s.memory().memory_total_bytes, Some(128 * 1024 * 1024));
        assert_eq!(s.fabric().default_listen_addr(), Some("0.0.0.0:0"));
        assert_eq!(s.fabric().progress_threads, Some(2));
        assert_eq!(s.fabric().progress_poll_us, Some(10));
        assert_eq!(s.fabric().rpc_worker_threads, Some(4));
        assert_eq!(s.fabric().max_inflight, Some(1024));
        assert_eq!(s.topology().nic_workers, Some(4));
        // `serving_cores` stays absent, which means auto-fill.
        assert_eq!(s.topology().serving_cores, None);
        // The inverted-sense flags default to false so the historical
        // safe behavior (respect isolated, exclude cpu0, require active
        // port) is preserved.
        assert!(!s.topology().use_smt_siblings);
        assert!(!s.topology().ignore_isolated);
        assert!(!s.topology().include_node_cpu0);
        assert!(!s.topology().allow_inactive_port);
        assert!(!s.topology().disable_rdma);
    }

    #[test]
    fn startup_round_trips() {
        let s = r#"
[startup.memory]
no_hugepages = true
memory_total_bytes = 67108864

[startup.fabric]
progress_threads = 3
progress_poll_us = 25
rpc_worker_threads = 8
max_inflight = 2048

[startup.fabric.binds.auto_rdma]
hcas_per_numa_node = 2

[startup.topology]
use_smt_siblings = true
ignore_isolated = true
include_node_cpu0 = true
allow_inactive_port = true
disable_rdma = true
serving_cores = 12
nic_workers = 6
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        let st = c.startup();
        assert!(st.memory().no_hugepages);
        assert_eq!(st.memory().memory_total_bytes, Some(64 * 1024 * 1024));
        assert_eq!(st.fabric().default_listen_addr(), Some("0.0.0.0:0"));
        assert_eq!(st.fabric().auto_hcas_per_numa_node(), Some(2));
        assert_eq!(st.fabric().progress_threads, Some(3));
        assert_eq!(st.fabric().progress_poll_us, Some(25));
        assert_eq!(st.fabric().rpc_worker_threads, Some(8));
        assert_eq!(st.fabric().max_inflight, Some(2048));
        assert!(st.topology().use_smt_siblings);
        assert!(st.topology().ignore_isolated);
        assert!(st.topology().include_node_cpu0);
        assert!(st.topology().allow_inactive_port);
        assert!(st.topology().disable_rdma);
        assert_eq!(st.topology().serving_cores, Some(12));
        assert_eq!(st.topology().nic_workers, Some(6));
    }
    #[test]
    fn startup_defaults_are_idempotent() {
        let mut c: Config = toml::from_str("[startup.fabric]\nprogress_threads = 7\n").unwrap();
        c.apply_defaults();
        c.apply_defaults();
        // An explicitly set value survives repeated defaulting, and the
        // unset siblings keep their documented defaults.
        assert_eq!(c.startup().fabric().progress_threads, Some(7));
        assert_eq!(c.startup().fabric().rpc_worker_threads, Some(4));
        assert_eq!(
            c.startup().memory().memory_total_bytes,
            Some(128 * 1024 * 1024)
        );
    }
}
