// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Typed schema for the daemon's configuration.
//!
//! The types in this module are generated by prost from
//! `../../api/unbounded-storage/config.proto` (see `build.rs`) and pulled
//! in via the `include!` below. The `.proto` is the schema source of truth.
//!
//! The schema is proto3-native: enums are integers, byte sizes are
//! plain integers, and every field's proto3 zero value means "unset".
//! [`Config::apply_defaults`] runs after deserialization and promotes
//! those zero values to the documented defaults. Section messages are
//! `Option` in prost and are guaranteed `Some` after `apply_defaults`,
//! so the section accessors below never panic.
//!
//! The TOML loader is strict: each message derives
//! `#[serde(default, deny_unknown_fields)]`, so an unknown key fails
//! loudly at parse time, and `config::load::validate` rejects enum
//! integers outside their defined discriminants.

include!(concat!(env!("OUT_DIR"), "/unbounded.storage.config.rs"));

impl Config {
    /// Populates every omitted section and promotes proto3 zero values
    /// to their documented defaults. Idempotent: a field already set to
    /// a non-zero value is left untouched. Run once after load (or after
    /// decoding a protobuf message) before the config is consumed.
    pub fn apply_defaults(&mut self) {
        let p2p = self.p2p.get_or_insert_with(P2pCfg::default);
        if p2p.fingers_per_node == 0 {
            p2p.fingers_per_node = 100;
        }

        for b in &mut self.backends {
            if b.stripe_size_bytes == 0 {
                b.stripe_size_bytes = 4 * 1024 * 1024;
            }
            if b.http_concurrency == 0 {
                b.http_concurrency = 64;
            }
        }

        let startup = self.startup.get_or_insert_with(StartupCfg::default);

        let memory = startup.memory.get_or_insert_with(MemoryCfg::default);
        if memory.memory_total_bytes == 0 {
            memory.memory_total_bytes = 128 * 1024 * 1024;
        }

        let fabric = startup.fabric.get_or_insert_with(FabricCfg::default);
        if fabric.listen_addr.is_empty() {
            fabric.listen_addr = "0.0.0.0:0".to_string();
        }
        if fabric.progress_threads == 0 {
            fabric.progress_threads = 2;
        }
        if fabric.progress_poll_us == 0 {
            fabric.progress_poll_us = 10;
        }
        if fabric.rpc_worker_threads == 0 {
            fabric.rpc_worker_threads = 4;
        }
        if fabric.max_inflight == 0 {
            fabric.max_inflight = 1024;
        }

        let topology = startup.topology.get_or_insert_with(TopologyCfg::default);
        if topology.nic_workers == 0 {
            topology.nic_workers = 4;
        }
        if topology.hcas_per_numa_node == 0 {
            topology.hcas_per_numa_node = 1;
        }
        // `serving_cores` keeps its proto3 zero, which the planner reads
        // as "auto-fill every usable core".

        // Metrics: the exporter is opt-in, so an empty bind (the proto3
        // zero value) is the intended "disabled" default and is left as
        // is. Materialize the section so the accessor never panics.
        startup.metrics.get_or_insert_with(MetricsCfg::default);
    }

    /// P2p section. Panics if called before [`Config::apply_defaults`]
    /// on a `Config` with no p2p section; always valid after `load`.
    pub fn p2p(&self) -> &P2pCfg {
        self.p2p.as_ref().expect("p2p section populated")
    }

    /// Startup-fixed settings section. Panics if called before
    /// [`Config::apply_defaults`]; always valid after `load`. The nested
    /// `memory`/`fabric`/`topology` sections are likewise guaranteed
    /// `Some` once defaults have been applied.
    pub fn startup(&self) -> &StartupCfg {
        self.startup.as_ref().expect("startup section populated")
    }
}

impl StartupCfg {
    /// Memory section. Valid after [`Config::apply_defaults`].
    pub fn memory(&self) -> &MemoryCfg {
        self.memory.as_ref().expect("memory section populated")
    }

    /// Fabric section. Valid after [`Config::apply_defaults`].
    pub fn fabric(&self) -> &FabricCfg {
        self.fabric.as_ref().expect("fabric section populated")
    }

    /// Topology section. Valid after [`Config::apply_defaults`].
    pub fn topology(&self) -> &TopologyCfg {
        self.topology.as_ref().expect("topology section populated")
    }

    /// Metrics section. Valid after [`Config::apply_defaults`].
    pub fn metrics(&self) -> &MetricsCfg {
        self.metrics.as_ref().expect("metrics section populated")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_are_populated() {
        let mut c: Config = toml::from_str("").unwrap();
        c.apply_defaults();
        assert_eq!(c.version, 0);
        assert_eq!(c.p2p().fingers_per_node, 100);
        assert!(c.p2p().local_node_id.is_none());
        assert!(c.p2p().local_labels.is_empty());
        assert!(c.peers.is_empty());
        assert!(c.disks.is_empty());
        assert!(c.backends.is_empty());
        assert!(c.frontends.is_empty());
    }

    #[test]
    fn metrics_section_defaults_to_disabled() {
        let mut c: Config = toml::from_str("").unwrap();
        c.apply_defaults();
        // The exporter is opt-in: the bind stays empty unless configured.
        assert_eq!(c.startup().metrics().bind, "");
    }

    #[test]
    fn version_round_trips() {
        // The top-level `version` is an opaque operator-assigned counter;
        // it round-trips verbatim and is not touched by `apply_defaults`.
        let mut c: Config = toml::from_str("version = 7\n").unwrap();
        c.apply_defaults();
        assert_eq!(c.version, 7);
    }

    #[test]
    fn unknown_fields_are_rejected() {
        // The TOML loader is strict: an unknown key fails loudly at parse
        // time (deny_unknown_fields) so operator typos are caught rather
        // than silently dropped.
        assert!(toml::from_str::<Config>("nonsense = 1\n").is_err());
    }

    #[test]
    fn disk_kind_defaults_to_nvme() {
        let s = r#"
[[disks]]
path = "/dev/nvme0n1"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.disks[0].kind(), DiskKind::Nvme);
    }

    #[test]
    fn disk_engine_fields_default_to_unset_and_off() {
        let s = r#"
[[disks]]
path = "/dev/nvme0n1"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.disks[0].page_size_bytes, None);
        assert!(!c.disks[0].bypass_admission);
        assert!(!c.disks[0].skip_recovery_scan_if_no_meta);
    }

    #[test]
    fn disk_engine_fields_round_trip() {
        let s = r#"
[[disks]]
path = "/dev/nvme0n1"
page_size_bytes = 4096
bypass_admission = true
skip_recovery_scan_if_no_meta = true
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.disks[0].page_size_bytes, Some(4096));
        assert!(c.disks[0].bypass_admission);
        assert!(c.disks[0].skip_recovery_scan_if_no_meta);
    }

    #[test]
    fn p2p_round_trips() {
        let s = r#"
[p2p]
fingers_per_node = 128
local_node_id = 42
local_labels = ["us-west", "az1", "row3", "rack7"]
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.p2p().fingers_per_node, 128);
        assert_eq!(c.p2p().local_node_id, Some(42));
        assert_eq!(
            c.p2p().local_labels,
            vec![
                "us-west".to_string(),
                "az1".to_string(),
                "row3".to_string(),
                "rack7".to_string(),
            ]
        );
    }

    #[test]
    fn p2p_routing_plan_round_trips() {
        let s = r#"
[p2p]
local_node_id = 1

[p2p.routing_plan]
fingers = [2, 5, 9, 17]
successor = 2
predecessor = 64
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        let plan = c.p2p().routing_plan.as_ref().expect("routing_plan set");
        assert_eq!(plan.fingers, vec![2, 5, 9, 17]);
        assert_eq!(plan.successor, Some(2));
        assert_eq!(plan.predecessor, Some(64));
    }

    #[test]
    fn p2p_routing_plan_absent_by_default() {
        let mut c: Config = toml::from_str("[p2p]\nlocal_node_id = 1\n").unwrap();
        c.apply_defaults();
        assert!(c.p2p().routing_plan.is_none());
    }

    #[test]
    fn peer_labels_round_trip() {
        let s = r#"
[[peers]]
id = 1
address = { socket = "127.0.0.1:9000" }
labels = ["us-west", "az1", "row3", "rack7"]
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(
            c.peers[0].labels,
            vec![
                "us-west".to_string(),
                "az1".to_string(),
                "row3".to_string(),
                "rack7".to_string(),
            ]
        );
    }

    #[test]
    fn backend_and_frontend_round_trip() {
        let s = r#"
[[backends]]
id = "primary-http"
kind = 0
endpoint = "https://origin.example.com"
stripe_size_bytes = 8388608
http_concurrency = 32

[[frontends]]
id = "workload-http"
kind = 0
bind = "0.0.0.0:9000"
backend = "primary-http"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.backends.len(), 1);
        let b = &c.backends[0];
        assert_eq!(b.id, "primary-http");
        assert_eq!(b.kind(), BackendKind::Http);
        assert_eq!(b.endpoint, "https://origin.example.com");
        assert_eq!(b.stripe_size_bytes, 8 * 1024 * 1024);
        assert_eq!(b.http_concurrency, 32);

        assert_eq!(c.frontends.len(), 1);
        let f = &c.frontends[0];
        assert_eq!(f.id, "workload-http");
        assert_eq!(f.kind(), FrontendKind::Http);
        assert_eq!(f.bind, "0.0.0.0:9000");
        assert_eq!(f.backend, "primary-http");
    }

    #[test]
    fn backend_optional_fields_default() {
        let s = r#"
[[backends]]
id = "b"
kind = 0
endpoint = "https://example.com"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        let b = &c.backends[0];
        assert_eq!(b.stripe_size_bytes, 4 * 1024 * 1024);
        assert_eq!(b.http_concurrency, 64);
    }

    #[test]
    fn s3_backend_round_trips_with_bucket() {
        let s = r#"
[[backends]]
id = "primary-s3"
kind = 1
endpoint = "s3.us-east-1.amazonaws.com:443"
bucket = "my-bucket"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        let b = &c.backends[0];
        assert_eq!(b.kind(), BackendKind::S3);
        assert_eq!(b.bucket.as_deref(), Some("my-bucket"));
    }

    #[test]
    fn s3_frontend_kind_round_trips() {
        let s = r#"
[[frontends]]
id = "workload-s3"
kind = 1
bind = "0.0.0.0:9000"
backend = "b"
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        assert_eq!(c.frontends[0].kind(), FrontendKind::S3);
    }

    #[test]
    fn startup_defaults_are_populated() {
        let mut c: Config = toml::from_str("").unwrap();
        c.apply_defaults();
        let s = c.startup();
        assert!(!s.memory().no_hugepages);
        assert_eq!(s.memory().memory_total_bytes, 128 * 1024 * 1024);
        assert_eq!(s.fabric().listen_addr, "0.0.0.0:0");
        assert_eq!(s.fabric().progress_threads, 2);
        assert_eq!(s.fabric().progress_poll_us, 10);
        assert_eq!(s.fabric().rpc_worker_threads, 4);
        assert_eq!(s.fabric().max_inflight, 1024);
        assert_eq!(s.topology().nic_workers, 4);
        // `serving_cores` stays at its proto3 zero (auto-fill).
        assert_eq!(s.topology().serving_cores, 0);
        // One HCA per NUMA node by default.
        assert_eq!(s.topology().hcas_per_numa_node, 1);
        // The inverted-sense flags default to false so the historical
        // safe behavior (respect isolated, exclude cpu0, require active
        // port) is preserved.
        assert!(!s.topology().use_smt_siblings);
        assert!(!s.topology().ignore_isolated);
        assert!(!s.topology().include_node_cpu0);
        assert!(!s.topology().allow_inactive_port);
        assert!(!s.topology().disable_rdma);
    }

    #[test]
    fn startup_round_trips() {
        let s = r#"
[startup.memory]
no_hugepages = true
memory_total_bytes = 67108864

[startup.fabric]
listen_addr = "10.0.0.1:7000"
progress_threads = 3
progress_poll_us = 25
rpc_worker_threads = 8
max_inflight = 2048

[startup.topology]
use_smt_siblings = true
ignore_isolated = true
include_node_cpu0 = true
allow_inactive_port = true
disable_rdma = true
serving_cores = 12
nic_workers = 6
hcas_per_numa_node = 2
"#;
        let mut c: Config = toml::from_str(s).unwrap();
        c.apply_defaults();
        let st = c.startup();
        assert!(st.memory().no_hugepages);
        assert_eq!(st.memory().memory_total_bytes, 64 * 1024 * 1024);
        assert_eq!(st.fabric().listen_addr, "10.0.0.1:7000");
        assert_eq!(st.fabric().progress_threads, 3);
        assert_eq!(st.fabric().progress_poll_us, 25);
        assert_eq!(st.fabric().rpc_worker_threads, 8);
        assert_eq!(st.fabric().max_inflight, 2048);
        assert!(st.topology().use_smt_siblings);
        assert!(st.topology().ignore_isolated);
        assert!(st.topology().include_node_cpu0);
        assert!(st.topology().allow_inactive_port);
        assert!(st.topology().disable_rdma);
        assert_eq!(st.topology().serving_cores, 12);
        assert_eq!(st.topology().nic_workers, 6);
        assert_eq!(st.topology().hcas_per_numa_node, 2);
    }
    #[test]
    fn startup_defaults_are_idempotent() {
        let mut c: Config = toml::from_str("[startup.fabric]\nprogress_threads = 7\n").unwrap();
        c.apply_defaults();
        c.apply_defaults();
        // An explicitly set value survives repeated defaulting, and the
        // unset siblings keep their documented defaults.
        assert_eq!(c.startup().fabric().progress_threads, 7);
        assert_eq!(c.startup().fabric().rpc_worker_threads, 4);
        assert_eq!(c.startup().memory().memory_total_bytes, 128 * 1024 * 1024);
    }
}
