apiVersion: v1
kind: Service
metadata:
  name: inventory-collector
  namespace: machina-system
  labels:
    app: inventory-collector
spec:
  type: ClusterIP
  selector:
    app: inventory-collector
  ports:
    - port: 50051
      targetPort: 50051
