---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-database-config
  namespace: inventory
data:
  POSTGRES_HOST: "postgres.inventory.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB_NAME: "inventory"
  POSTGRES_USER: "postgres"
  POSTGRES_SSL_MODE: "{{ SSL_MODE }}"
