apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../direct
  - control.yaml
patches:
  - path: daemonset-patch.yaml
images:
  - name: racer-loadgen
    newName: ghcr.io/azure/racer-loadgen
    newTag: f9a088a22a29cf8549e1945af833f508a14199d1
