{{- range $index := until 64 }}
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: {{ printf "gantry-chair-%02d" $index }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gantry.labels" $ | nindent 4 }}
    gantry.io/chair: "true"
spec: {}
{{- end }}