---
apiVersion: unbounded.aks.azure.com/v1alpha1
kind: Site
metadata:
  name: site-1
spec:
  nodeCidrs:
  {{- range .NodeCIDRs }}
    - {{ . }}
  {{- end }}
  podCidrAssignments:
    - cidrBlocks:
      {{- range .PodCIDRs }}
        - {{ . }}
      {{- end }}