// Copyright (c) Microsoft Corporation.
// SPDX-License-Identifier: Apache-2.0

package mirror

import (
	"context"
	"errors"
	"io"
	"sync"
	"time"

	"github.com/Azure/unbounded/pkg/racersdk"
)

const racerFailureLogBurst = 10

// One fixed-size limiter per mirror, never keyed by request or object. A burst
// refills only after a minute of inactivity since the last admitted event, so
// adjacent window boundaries cannot double the burst.
type racerFailureDiagnostics struct {
	mu         sync.Mutex
	last       time.Time
	remaining  int
	suppressed uint64
}

func (d *racerFailureDiagnostics) allow(now time.Time) (bool, uint64) {
	d.mu.Lock()
	defer d.mu.Unlock()

	if d.last.IsZero() || now.Sub(d.last) >= time.Minute {
		d.remaining = racerFailureLogBurst
	}

	if d.remaining == 0 {
		d.suppressed++
		return false, 0
	}

	d.remaining--
	d.last = now
	suppressed := d.suppressed
	d.suppressed = 0

	return true, suppressed
}

// Only SDK accessors and fixed classifications enter the log. In particular,
// neither err.Error() nor an unwrapped cause is safe to log. Correlation is
// generated by the mirror, not copied from caller headers, and is log-only (not
// a metric label). Expected bytes is -1 until valid response metadata is known;
// written bytes counts payload accepted by the writer, not client receipt.
func (s *Server) logRacerFailure(id, stage string, err error, expected, written int64) {
	allowed, suppressed := s.racerDiagnostics.allow(time.Now())
	if !allowed {
		return
	}

	kind, operation, status := "unclassified", "", 0

	var sdkErr *racersdk.Error
	switch {
	case errors.As(err, &sdkErr):
		kind, operation, status = sdkErr.Kind().String(), sdkErr.Operation(), sdkErr.StatusCode()
	case errors.Is(err, context.Canceled):
		kind = "canceled"
	case errors.Is(err, context.DeadlineExceeded):
		kind = "deadline"
	case errors.Is(err, io.ErrUnexpectedEOF):
		kind = "unexpected EOF"
	case errors.Is(err, io.ErrShortWrite):
		kind = "short write"
	case err == nil:
		kind = "length mismatch"
	}

	s.logger.Warn("Racer mirror failure",
		"request_id", id, "stage", stage,
		"error_kind", kind, "sdk_operation", operation, "sdk_status", status,
		"expected_bytes", expected, "written_bytes", written,
		"suppressed", suppressed)
}
