// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayNodeInfo) DeepCopyInto(out *GatewayNodeInfo) {
	*out = *in
	if in.InternalIPs != nil {
		in, out := &in.InternalIPs, &out.InternalIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExternalIPs != nil {
		in, out := &in.ExternalIPs, &out.ExternalIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HealthEndpoints != nil {
		in, out := &in.HealthEndpoints, &out.HealthEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodCIDRs != nil {
		in, out := &in.PodCIDRs, &out.PodCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayNodeInfo.
func (in *GatewayNodeInfo) DeepCopy() *GatewayNodeInfo {
	if in == nil {
		return nil
	}
	out := new(GatewayNodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayNodePathHop) DeepCopyInto(out *GatewayNodePathHop) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayNodePathHop.
func (in *GatewayNodePathHop) DeepCopy() *GatewayNodePathHop {
	if in == nil {
		return nil
	}
	out := new(GatewayNodePathHop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayNodeRoute) DeepCopyInto(out *GatewayNodeRoute) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(GatewayNodePathHop)
		**out = **in
	}
	if in.IntermediateHops != nil {
		in, out := &in.IntermediateHops, &out.IntermediateHops
		*out = make([]GatewayNodePathHop, len(*in))
		copy(*out, *in)
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([][]GatewayNodePathHop, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]GatewayNodePathHop, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayNodeRoute.
func (in *GatewayNodeRoute) DeepCopy() *GatewayNodeRoute {
	if in == nil {
		return nil
	}
	out := new(GatewayNodeRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayNodeSpec) DeepCopyInto(out *GatewayNodeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayNodeSpec.
func (in *GatewayNodeSpec) DeepCopy() *GatewayNodeSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayNodeStatus) DeepCopyInto(out *GatewayNodeStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make(map[string]GatewayNodeRoute, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayNodeStatus.
func (in *GatewayNodeStatus) DeepCopy() *GatewayNodeStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPool) DeepCopyInto(out *GatewayPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPool.
func (in *GatewayPool) DeepCopy() *GatewayPool {
	if in == nil {
		return nil
	}
	out := new(GatewayPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPoolList) DeepCopyInto(out *GatewayPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPoolList.
func (in *GatewayPoolList) DeepCopy() *GatewayPoolList {
	if in == nil {
		return nil
	}
	out := new(GatewayPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPoolNode) DeepCopyInto(out *GatewayPoolNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPoolNode.
func (in *GatewayPoolNode) DeepCopy() *GatewayPoolNode {
	if in == nil {
		return nil
	}
	out := new(GatewayPoolNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayPoolNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPoolNodeList) DeepCopyInto(out *GatewayPoolNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayPoolNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPoolNodeList.
func (in *GatewayPoolNodeList) DeepCopy() *GatewayPoolNodeList {
	if in == nil {
		return nil
	}
	out := new(GatewayPoolNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayPoolNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPoolPeering) DeepCopyInto(out *GatewayPoolPeering) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPoolPeering.
func (in *GatewayPoolPeering) DeepCopy() *GatewayPoolPeering {
	if in == nil {
		return nil
	}
	out := new(GatewayPoolPeering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayPoolPeering) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPoolPeeringList) DeepCopyInto(out *GatewayPoolPeeringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayPoolPeering, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPoolPeeringList.
func (in *GatewayPoolPeeringList) DeepCopy() *GatewayPoolPeeringList {
	if in == nil {
		return nil
	}
	out := new(GatewayPoolPeeringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayPoolPeeringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPoolPeeringSpec) DeepCopyInto(out *GatewayPoolPeeringSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GatewayPools != nil {
		in, out := &in.GatewayPools, &out.GatewayPools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HealthCheckSettings != nil {
		in, out := &in.HealthCheckSettings, &out.HealthCheckSettings
		*out = new(HealthCheckSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.TunnelProtocol != nil {
		in, out := &in.TunnelProtocol, &out.TunnelProtocol
		*out = new(TunnelProtocol)
		**out = **in
	}
	if in.TunnelMTU != nil {
		in, out := &in.TunnelMTU, &out.TunnelMTU
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPoolPeeringSpec.
func (in *GatewayPoolPeeringSpec) DeepCopy() *GatewayPoolPeeringSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayPoolPeeringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPoolRoute) DeepCopyInto(out *GatewayPoolRoute) {
	*out = *in
	out.Origin = in.Origin
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPoolRoute.
func (in *GatewayPoolRoute) DeepCopy() *GatewayPoolRoute {
	if in == nil {
		return nil
	}
	out := new(GatewayPoolRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPoolRouteOrigin) DeepCopyInto(out *GatewayPoolRouteOrigin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPoolRouteOrigin.
func (in *GatewayPoolRouteOrigin) DeepCopy() *GatewayPoolRouteOrigin {
	if in == nil {
		return nil
	}
	out := new(GatewayPoolRouteOrigin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPoolSpec) DeepCopyInto(out *GatewayPoolSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RoutedCidrs != nil {
		in, out := &in.RoutedCidrs, &out.RoutedCidrs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HealthCheckSettings != nil {
		in, out := &in.HealthCheckSettings, &out.HealthCheckSettings
		*out = new(HealthCheckSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.TunnelProtocol != nil {
		in, out := &in.TunnelProtocol, &out.TunnelProtocol
		*out = new(TunnelProtocol)
		**out = **in
	}
	if in.TunnelMTU != nil {
		in, out := &in.TunnelMTU, &out.TunnelMTU
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPoolSpec.
func (in *GatewayPoolSpec) DeepCopy() *GatewayPoolSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPoolStatus) DeepCopyInto(out *GatewayPoolStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]GatewayNodeInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConnectedSites != nil {
		in, out := &in.ConnectedSites, &out.ConnectedSites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReachableSites != nil {
		in, out := &in.ReachableSites, &out.ReachableSites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPoolStatus.
func (in *GatewayPoolStatus) DeepCopy() *GatewayPoolStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckSettings) DeepCopyInto(out *HealthCheckSettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.DetectMultiplier != nil {
		in, out := &in.DetectMultiplier, &out.DetectMultiplier
		*out = new(int32)
		**out = **in
	}
	if in.ReceiveInterval != nil {
		in, out := &in.ReceiveInterval, &out.ReceiveInterval
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TransmitInterval != nil {
		in, out := &in.TransmitInterval, &out.TransmitInterval
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckSettings.
func (in *HealthCheckSettings) DeepCopy() *HealthCheckSettings {
	if in == nil {
		return nil
	}
	out := new(HealthCheckSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeBlockSizes) DeepCopyInto(out *NodeBlockSizes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeBlockSizes.
func (in *NodeBlockSizes) DeepCopy() *NodeBlockSizes {
	if in == nil {
		return nil
	}
	out := new(NodeBlockSizes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInfo) DeepCopyInto(out *NodeInfo) {
	*out = *in
	if in.InternalIPs != nil {
		in, out := &in.InternalIPs, &out.InternalIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodCIDRs != nil {
		in, out := &in.PodCIDRs, &out.PodCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInfo.
func (in *NodeInfo) DeepCopy() *NodeInfo {
	if in == nil {
		return nil
	}
	out := new(NodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCidrAssignment) DeepCopyInto(out *PodCidrAssignment) {
	*out = *in
	if in.AssignmentEnabled != nil {
		in, out := &in.AssignmentEnabled, &out.AssignmentEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CidrBlocks != nil {
		in, out := &in.CidrBlocks, &out.CidrBlocks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeBlockSizes != nil {
		in, out := &in.NodeBlockSizes, &out.NodeBlockSizes
		*out = new(NodeBlockSizes)
		**out = **in
	}
	if in.NodeRegex != nil {
		in, out := &in.NodeRegex, &out.NodeRegex
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCidrAssignment.
func (in *PodCidrAssignment) DeepCopy() *PodCidrAssignment {
	if in == nil {
		return nil
	}
	out := new(PodCidrAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Site) DeepCopyInto(out *Site) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Site.
func (in *Site) DeepCopy() *Site {
	if in == nil {
		return nil
	}
	out := new(Site)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Site) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteGatewayPoolAssignment) DeepCopyInto(out *SiteGatewayPoolAssignment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteGatewayPoolAssignment.
func (in *SiteGatewayPoolAssignment) DeepCopy() *SiteGatewayPoolAssignment {
	if in == nil {
		return nil
	}
	out := new(SiteGatewayPoolAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiteGatewayPoolAssignment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteGatewayPoolAssignmentList) DeepCopyInto(out *SiteGatewayPoolAssignmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SiteGatewayPoolAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteGatewayPoolAssignmentList.
func (in *SiteGatewayPoolAssignmentList) DeepCopy() *SiteGatewayPoolAssignmentList {
	if in == nil {
		return nil
	}
	out := new(SiteGatewayPoolAssignmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiteGatewayPoolAssignmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteGatewayPoolAssignmentSpec) DeepCopyInto(out *SiteGatewayPoolAssignmentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Sites != nil {
		in, out := &in.Sites, &out.Sites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GatewayPools != nil {
		in, out := &in.GatewayPools, &out.GatewayPools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HealthCheckSettings != nil {
		in, out := &in.HealthCheckSettings, &out.HealthCheckSettings
		*out = new(HealthCheckSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.TunnelProtocol != nil {
		in, out := &in.TunnelProtocol, &out.TunnelProtocol
		*out = new(TunnelProtocol)
		**out = **in
	}
	if in.TunnelMTU != nil {
		in, out := &in.TunnelMTU, &out.TunnelMTU
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteGatewayPoolAssignmentSpec.
func (in *SiteGatewayPoolAssignmentSpec) DeepCopy() *SiteGatewayPoolAssignmentSpec {
	if in == nil {
		return nil
	}
	out := new(SiteGatewayPoolAssignmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteList) DeepCopyInto(out *SiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Site, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteList.
func (in *SiteList) DeepCopy() *SiteList {
	if in == nil {
		return nil
	}
	out := new(SiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteNodeSlice) DeepCopyInto(out *SiteNodeSlice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteNodeSlice.
func (in *SiteNodeSlice) DeepCopy() *SiteNodeSlice {
	if in == nil {
		return nil
	}
	out := new(SiteNodeSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiteNodeSlice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteNodeSliceList) DeepCopyInto(out *SiteNodeSliceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SiteNodeSlice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteNodeSliceList.
func (in *SiteNodeSliceList) DeepCopy() *SiteNodeSliceList {
	if in == nil {
		return nil
	}
	out := new(SiteNodeSliceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiteNodeSliceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SitePeering) DeepCopyInto(out *SitePeering) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SitePeering.
func (in *SitePeering) DeepCopy() *SitePeering {
	if in == nil {
		return nil
	}
	out := new(SitePeering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SitePeering) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SitePeeringList) DeepCopyInto(out *SitePeeringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SitePeering, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SitePeeringList.
func (in *SitePeeringList) DeepCopy() *SitePeeringList {
	if in == nil {
		return nil
	}
	out := new(SitePeeringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SitePeeringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SitePeeringSpec) DeepCopyInto(out *SitePeeringSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Sites != nil {
		in, out := &in.Sites, &out.Sites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MeshNodes != nil {
		in, out := &in.MeshNodes, &out.MeshNodes
		*out = new(bool)
		**out = **in
	}
	if in.HealthCheckSettings != nil {
		in, out := &in.HealthCheckSettings, &out.HealthCheckSettings
		*out = new(HealthCheckSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.TunnelProtocol != nil {
		in, out := &in.TunnelProtocol, &out.TunnelProtocol
		*out = new(TunnelProtocol)
		**out = **in
	}
	if in.TunnelMTU != nil {
		in, out := &in.TunnelMTU, &out.TunnelMTU
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SitePeeringSpec.
func (in *SitePeeringSpec) DeepCopy() *SitePeeringSpec {
	if in == nil {
		return nil
	}
	out := new(SitePeeringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SitePeeringStatus) DeepCopyInto(out *SitePeeringStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SitePeeringStatus.
func (in *SitePeeringStatus) DeepCopy() *SitePeeringStatus {
	if in == nil {
		return nil
	}
	out := new(SitePeeringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteSpec) DeepCopyInto(out *SiteSpec) {
	*out = *in
	if in.NodeCidrs != nil {
		in, out := &in.NodeCidrs, &out.NodeCidrs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodCidrAssignments != nil {
		in, out := &in.PodCidrAssignments, &out.PodCidrAssignments
		*out = make([]PodCidrAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManageCniPlugin != nil {
		in, out := &in.ManageCniPlugin, &out.ManageCniPlugin
		*out = new(bool)
		**out = **in
	}
	if in.NonMasqueradeCIDRs != nil {
		in, out := &in.NonMasqueradeCIDRs, &out.NonMasqueradeCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LocalCIDRs != nil {
		in, out := &in.LocalCIDRs, &out.LocalCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HealthCheckSettings != nil {
		in, out := &in.HealthCheckSettings, &out.HealthCheckSettings
		*out = new(HealthCheckSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.TunnelProtocol != nil {
		in, out := &in.TunnelProtocol, &out.TunnelProtocol
		*out = new(TunnelProtocol)
		**out = **in
	}
	if in.TunnelMTU != nil {
		in, out := &in.TunnelMTU, &out.TunnelMTU
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteSpec.
func (in *SiteSpec) DeepCopy() *SiteSpec {
	if in == nil {
		return nil
	}
	out := new(SiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteStatus) DeepCopyInto(out *SiteStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteStatus.
func (in *SiteStatus) DeepCopy() *SiteStatus {
	if in == nil {
		return nil
	}
	out := new(SiteStatus)
	in.DeepCopyInto(out)
	return out
}
