// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: api/inventory/v1/inventory.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryAggregator_SubmitInventory_FullMethodName = "/inventory.v1.InventoryAggregator/SubmitInventory"
)

// InventoryAggregatorClient is the client API for InventoryAggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryAggregator accepts inventory data from nodes.
type InventoryAggregatorClient interface {
	// SubmitInventory receives a batch of device and neighbor records and
	// persists them to the database.
	SubmitInventory(ctx context.Context, in *SubmitInventoryRequest, opts ...grpc.CallOption) (*SubmitInventoryResponse, error)
}

type inventoryAggregatorClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryAggregatorClient(cc grpc.ClientConnInterface) InventoryAggregatorClient {
	return &inventoryAggregatorClient{cc}
}

func (c *inventoryAggregatorClient) SubmitInventory(ctx context.Context, in *SubmitInventoryRequest, opts ...grpc.CallOption) (*SubmitInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryAggregator_SubmitInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryAggregatorServer is the server API for InventoryAggregator service.
// All implementations must embed UnimplementedInventoryAggregatorServer
// for forward compatibility.
//
// InventoryAggregator accepts inventory data from nodes.
type InventoryAggregatorServer interface {
	// SubmitInventory receives a batch of device and neighbor records and
	// persists them to the database.
	SubmitInventory(context.Context, *SubmitInventoryRequest) (*SubmitInventoryResponse, error)
	mustEmbedUnimplementedInventoryAggregatorServer()
}

// UnimplementedInventoryAggregatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryAggregatorServer struct{}

func (UnimplementedInventoryAggregatorServer) SubmitInventory(context.Context, *SubmitInventoryRequest) (*SubmitInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitInventory not implemented")
}
func (UnimplementedInventoryAggregatorServer) mustEmbedUnimplementedInventoryAggregatorServer() {}
func (UnimplementedInventoryAggregatorServer) testEmbeddedByValue()                             {}

// UnsafeInventoryAggregatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryAggregatorServer will
// result in compilation errors.
type UnsafeInventoryAggregatorServer interface {
	mustEmbedUnimplementedInventoryAggregatorServer()
}

func RegisterInventoryAggregatorServer(s grpc.ServiceRegistrar, srv InventoryAggregatorServer) {
	// If the following call panics, it indicates UnimplementedInventoryAggregatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryAggregator_ServiceDesc, srv)
}

func _InventoryAggregator_SubmitInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryAggregatorServer).SubmitInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryAggregator_SubmitInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryAggregatorServer).SubmitInventory(ctx, req.(*SubmitInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryAggregator_ServiceDesc is the grpc.ServiceDesc for InventoryAggregator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryAggregator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryAggregator",
	HandlerType: (*InventoryAggregatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitInventory",
			Handler:    _InventoryAggregator_SubmitInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/inventory/v1/inventory.proto",
}
