// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/inventory/v1/inventory.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryCollector_SubmitInventory_FullMethodName = "/inventory.v1.InventoryCollector/SubmitInventory"
)

// InventoryCollectorClient is the client API for InventoryCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryCollector accepts inventory data from nodes.
type InventoryCollectorClient interface {
	// SubmitInventory receives a batch of device and neighbor records and
	// persists them to the database.
	SubmitInventory(ctx context.Context, in *SubmitInventoryRequest, opts ...grpc.CallOption) (*SubmitInventoryResponse, error)
}

type inventoryCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryCollectorClient(cc grpc.ClientConnInterface) InventoryCollectorClient {
	return &inventoryCollectorClient{cc}
}

func (c *inventoryCollectorClient) SubmitInventory(ctx context.Context, in *SubmitInventoryRequest, opts ...grpc.CallOption) (*SubmitInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryCollector_SubmitInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryCollectorServer is the server API for InventoryCollector service.
// All implementations must embed UnimplementedInventoryCollectorServer
// for forward compatibility.
//
// InventoryCollector accepts inventory data from nodes.
type InventoryCollectorServer interface {
	// SubmitInventory receives a batch of device and neighbor records and
	// persists them to the database.
	SubmitInventory(context.Context, *SubmitInventoryRequest) (*SubmitInventoryResponse, error)
	mustEmbedUnimplementedInventoryCollectorServer()
}

// UnimplementedInventoryCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryCollectorServer struct{}

func (UnimplementedInventoryCollectorServer) SubmitInventory(context.Context, *SubmitInventoryRequest) (*SubmitInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitInventory not implemented")
}
func (UnimplementedInventoryCollectorServer) mustEmbedUnimplementedInventoryCollectorServer() {}
func (UnimplementedInventoryCollectorServer) testEmbeddedByValue()                            {}

// UnsafeInventoryCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryCollectorServer will
// result in compilation errors.
type UnsafeInventoryCollectorServer interface {
	mustEmbedUnimplementedInventoryCollectorServer()
}

func RegisterInventoryCollectorServer(s grpc.ServiceRegistrar, srv InventoryCollectorServer) {
	// If the following call panics, it indicates UnimplementedInventoryCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryCollector_ServiceDesc, srv)
}

func _InventoryCollector_SubmitInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryCollectorServer).SubmitInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryCollector_SubmitInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryCollectorServer).SubmitInventory(ctx, req.(*SubmitInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryCollector_ServiceDesc is the grpc.ServiceDesc for InventoryCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryCollector",
	HandlerType: (*InventoryCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitInventory",
			Handler:    _InventoryCollector_SubmitInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/inventory/v1/inventory.proto",
}
