// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: api/inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceRecord represents a single hardware inventory item.
type DeviceRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceType     string                 `protobuf:"bytes,1,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	DeviceName     string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	HostIdentifier string                 `protobuf:"bytes,3,opt,name=host_identifier,json=hostIdentifier,proto3" json:"host_identifier,omitempty"`
	SerialNumber   string                 `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	// JSON-encoded device attributes.
	Attributes    []byte `protobuf:"bytes,5,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRecord) Reset() {
	*x = DeviceRecord{}
	mi := &file_api_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRecord) ProtoMessage() {}

func (x *DeviceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRecord.ProtoReflect.Descriptor instead.
func (*DeviceRecord) Descriptor() ([]byte, []int) {
	return file_api_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceRecord) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *DeviceRecord) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceRecord) GetHostIdentifier() string {
	if x != nil {
		return x.HostIdentifier
	}
	return ""
}

func (x *DeviceRecord) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *DeviceRecord) GetAttributes() []byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// NeighborRecord represents a discovered network neighbor.
type NeighborRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostIdentifier string                 `protobuf:"bytes,1,opt,name=host_identifier,json=hostIdentifier,proto3" json:"host_identifier,omitempty"`
	LocalInterface string                 `protobuf:"bytes,2,opt,name=local_interface,json=localInterface,proto3" json:"local_interface,omitempty"`
	// JSON-encoded neighbor attributes.
	Attributes    []byte `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighborRecord) Reset() {
	*x = NeighborRecord{}
	mi := &file_api_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighborRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborRecord) ProtoMessage() {}

func (x *NeighborRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborRecord.ProtoReflect.Descriptor instead.
func (*NeighborRecord) Descriptor() ([]byte, []int) {
	return file_api_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *NeighborRecord) GetHostIdentifier() string {
	if x != nil {
		return x.HostIdentifier
	}
	return ""
}

func (x *NeighborRecord) GetLocalInterface() string {
	if x != nil {
		return x.LocalInterface
	}
	return ""
}

func (x *NeighborRecord) GetAttributes() []byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// SubmitInventoryRequest carries a batch of inventory records from a node.
type SubmitInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceRecord        `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	Neighbors     []*NeighborRecord      `protobuf:"bytes,2,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitInventoryRequest) Reset() {
	*x = SubmitInventoryRequest{}
	mi := &file_api_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInventoryRequest) ProtoMessage() {}

func (x *SubmitInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInventoryRequest.ProtoReflect.Descriptor instead.
func (*SubmitInventoryRequest) Descriptor() ([]byte, []int) {
	return file_api_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitInventoryRequest) GetDevices() []*DeviceRecord {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *SubmitInventoryRequest) GetNeighbors() []*NeighborRecord {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

// SubmitInventoryResponse is returned after records have been persisted.
type SubmitInventoryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DevicesSaved   int32                  `protobuf:"varint,1,opt,name=devices_saved,json=devicesSaved,proto3" json:"devices_saved,omitempty"`
	NeighborsSaved int32                  `protobuf:"varint,2,opt,name=neighbors_saved,json=neighborsSaved,proto3" json:"neighbors_saved,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitInventoryResponse) Reset() {
	*x = SubmitInventoryResponse{}
	mi := &file_api_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInventoryResponse) ProtoMessage() {}

func (x *SubmitInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInventoryResponse.ProtoReflect.Descriptor instead.
func (*SubmitInventoryResponse) Descriptor() ([]byte, []int) {
	return file_api_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitInventoryResponse) GetDevicesSaved() int32 {
	if x != nil {
		return x.DevicesSaved
	}
	return 0
}

func (x *SubmitInventoryResponse) GetNeighborsSaved() int32 {
	if x != nil {
		return x.NeighborsSaved
	}
	return 0
}

var File_api_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_api_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	" api/inventory/v1/inventory.proto\x12\finventory.v1\"\xbe\x01\n" +
	"\fDeviceRecord\x12\x1f\n" +
	"\vdevice_type\x18\x01 \x01(\tR\n" +
	"deviceType\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12'\n" +
	"\x0fhost_identifier\x18\x03 \x01(\tR\x0ehostIdentifier\x12#\n" +
	"\rserial_number\x18\x04 \x01(\tR\fserialNumber\x12\x1e\n" +
	"\n" +
	"attributes\x18\x05 \x01(\fR\n" +
	"attributes\"\x82\x01\n" +
	"\x0eNeighborRecord\x12'\n" +
	"\x0fhost_identifier\x18\x01 \x01(\tR\x0ehostIdentifier\x12'\n" +
	"\x0flocal_interface\x18\x02 \x01(\tR\x0elocalInterface\x12\x1e\n" +
	"\n" +
	"attributes\x18\x03 \x01(\fR\n" +
	"attributes\"\x8a\x01\n" +
	"\x16SubmitInventoryRequest\x124\n" +
	"\adevices\x18\x01 \x03(\v2\x1a.inventory.v1.DeviceRecordR\adevices\x12:\n" +
	"\tneighbors\x18\x02 \x03(\v2\x1c.inventory.v1.NeighborRecordR\tneighbors\"g\n" +
	"\x17SubmitInventoryResponse\x12#\n" +
	"\rdevices_saved\x18\x01 \x01(\x05R\fdevicesSaved\x12'\n" +
	"\x0fneighbors_saved\x18\x02 \x01(\x05R\x0eneighborsSaved2u\n" +
	"\x13InventoryAggregator\x12^\n" +
	"\x0fSubmitInventory\x12$.inventory.v1.SubmitInventoryRequest\x1a%.inventory.v1.SubmitInventoryResponseB9Z7github.com/Azure/unbounded/api/inventory/v1;inventoryv1b\x06proto3"

var (
	file_api_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_api_inventory_v1_inventory_proto_rawDescData []byte
)

func file_api_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_api_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_api_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_inventory_v1_inventory_proto_rawDesc), len(file_api_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_api_inventory_v1_inventory_proto_rawDescData
}

var file_api_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_inventory_v1_inventory_proto_goTypes = []any{
	(*DeviceRecord)(nil),            // 0: inventory.v1.DeviceRecord
	(*NeighborRecord)(nil),          // 1: inventory.v1.NeighborRecord
	(*SubmitInventoryRequest)(nil),  // 2: inventory.v1.SubmitInventoryRequest
	(*SubmitInventoryResponse)(nil), // 3: inventory.v1.SubmitInventoryResponse
}
var file_api_inventory_v1_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.v1.SubmitInventoryRequest.devices:type_name -> inventory.v1.DeviceRecord
	1, // 1: inventory.v1.SubmitInventoryRequest.neighbors:type_name -> inventory.v1.NeighborRecord
	2, // 2: inventory.v1.InventoryAggregator.SubmitInventory:input_type -> inventory.v1.SubmitInventoryRequest
	3, // 3: inventory.v1.InventoryAggregator.SubmitInventory:output_type -> inventory.v1.SubmitInventoryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_inventory_v1_inventory_proto_init() }
func file_api_inventory_v1_inventory_proto_init() {
	if File_api_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_inventory_v1_inventory_proto_rawDesc), len(file_api_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_api_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_api_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_api_inventory_v1_inventory_proto = out.File
	file_api_inventory_v1_inventory_proto_goTypes = nil
	file_api_inventory_v1_inventory_proto_depIdxs = nil
}
