---
apiVersion: unbounded.aks.azure.com/v1alpha1
kind: GatewayPool
metadata:
  name: "{{ .PoolName }}"
spec:
  nodeSelector:
    unbounded.aks.azure.com/gateway: "true"
    kubernetes.azure.com/agentpool: "{{ .AgentPool }}"
  type: "{{ .Type }}"