//go:build !ignore_autogenerated

// Copyright (c) Microsoft Corporation.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2PCache) DeepCopyInto(out *P2PCache) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2PCache.
func (in *P2PCache) DeepCopy() *P2PCache {
	if in == nil {
		return nil
	}
	out := new(P2PCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *P2PCache) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2PCacheList) DeepCopyInto(out *P2PCacheList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]P2PCache, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2PCacheList.
func (in *P2PCacheList) DeepCopy() *P2PCacheList {
	if in == nil {
		return nil
	}
	out := new(P2PCacheList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *P2PCacheList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2PCacheParticipants) DeepCopyInto(out *P2PCacheParticipants) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2PCacheParticipants.
func (in *P2PCacheParticipants) DeepCopy() *P2PCacheParticipants {
	if in == nil {
		return nil
	}
	out := new(P2PCacheParticipants)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2PCacheSpec) DeepCopyInto(out *P2PCacheSpec) {
	*out = *in
	in.SiteSelector.DeepCopyInto(&out.SiteSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2PCacheSpec.
func (in *P2PCacheSpec) DeepCopy() *P2PCacheSpec {
	if in == nil {
		return nil
	}
	out := new(P2PCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2PCacheStatus) DeepCopyInto(out *P2PCacheStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Participants = in.Participants
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2PCacheStatus.
func (in *P2PCacheStatus) DeepCopy() *P2PCacheStatus {
	if in == nil {
		return nil
	}
	out := new(P2PCacheStatus)
	in.DeepCopyInto(out)
	return out
}
