// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package goalstates

import "fmt"

const (
	// ConfigDir is the host-level configuration directory for unbounded-kube.
	ConfigDir = "/etc/unbounded/kube"

	// AgentConfigDir is the host-level configuration directory for the
	// unbounded-agent. Applied config files are persisted here.
	AgentConfigDir = "/etc/unbounded/agent"

	SystemdNSpawnDir = "/etc/systemd/nspawn"
	SystemdSystemDir = "/etc/systemd/system"
	BPFFSMountDir    = "/run/bpffs"

	// DaemonUnit is the systemd unit name for the unbounded-agent daemon.
	DaemonUnit = "unbounded-agent-daemon.service"

	// DaemonRecoveryUnit is the systemd recovery unit for the agent daemon.
	DaemonRecoveryUnit = "unbounded-agent-daemon-recovery.service"

	DaemonBinaryPath             = "/usr/local/bin/unbounded-agent"
	DaemonBinaryBluePath         = "/usr/local/bin/unbounded-agent-blue"
	DaemonBinaryGreenPath        = "/usr/local/bin/unbounded-agent-green"
	DaemonBinaryCurrentPath      = "/usr/local/bin/unbounded-agent-current"
	DaemonBinaryLastGoodPath     = "/usr/local/bin/unbounded-agent-last-good"
	DaemonRecoveryScriptPath     = "/usr/local/bin/unbounded-agent-daemon-recovery.sh"
	DaemonAgentUpgradeSignalPath = AgentConfigDir + "/agent-upgrade-signal"

	EnvDaemonBinary                 = "UNBOUNDED_AGENT_DAEMON_BINARY"
	EnvDaemonBinaryBlue             = "UNBOUNDED_AGENT_DAEMON_BINARY_BLUE"
	EnvDaemonBinaryGreen            = "UNBOUNDED_AGENT_DAEMON_BINARY_GREEN"
	EnvDaemonBinaryCurrent          = "UNBOUNDED_AGENT_DAEMON_BINARY_CURRENT"
	EnvDaemonBinaryLastGood         = "UNBOUNDED_AGENT_DAEMON_BINARY_LAST_GOOD"
	EnvDaemonAgentUpgradeSignalPath = "UNBOUNDED_AGENT_DAEMON_AGENT_UPGRADE_SIGNAL_PATH"
)

// NSpawn machine names used for alternating in-place upgrades.
//
//   - NSpawnMachineKube1 is the initial (default) machine name.
//   - NSpawnMachineKube2 will be used for the next upgrade cycle.
//
// The pattern alternates between the two so an in-place upgrade can bring
// up the new machine before tearing down the old one:
//
//	kube1  ← initial
//	kube2  ← after operation 1
//	kube1  ← after operation 2
//	…
const (
	NSpawnMachineKube1 = "kube1"
	NSpawnMachineKube2 = "kube2"
)

// AlternateMachine returns the other machine name in the pair.
// kube1 -> kube2, kube2 -> kube1.
func AlternateMachine(current string) string {
	if current == NSpawnMachineKube1 {
		return NSpawnMachineKube2
	}

	return NSpawnMachineKube1
}

// BPFFSMountPath returns the host-side bpffs mount path for an nspawn machine.
func BPFFSMountPath(machineName string) string {
	return fmt.Sprintf("%s/%s", BPFFSMountDir, machineName)
}

// AppliedConfigPath returns the path to the applied config file for the
// given nspawn machine name, e.g. /etc/unbounded/agent/kube1-applied-config.json.
func AppliedConfigPath(machineName string) string {
	return fmt.Sprintf("%s/%s-applied-config.json", AgentConfigDir, machineName)
}

const (
	ContainerdVersion = "2.0.4"
	RunCVersion       = "1.1.12"
	CNIPluginVersion  = "1.5.1"

	ContainerdMetricsAddress = "0.0.0.0:10257"
	SandboxImage             = "mcr.microsoft.com/oss/kubernetes/pause:3.9"

	CNIBinDir    = "/opt/cni/bin"
	CNIConfigDir = "/etc/cni/net.d"

	// BinDir is the standard binary directory relative to the machine root.
	// Use filepath.Join(machineDir, BinDir) for host-side rootfs paths, or
	// "/"+BinDir for absolute paths inside the running machine container.
	BinDir = "usr/local/bin"

	// NvidiaHostLibDir is the base directory inside the nspawn container where
	// host NVIDIA library directories are bind-mounted read-only. Each unique
	// host directory gets a numbered subdirectory (e.g. /run/host-nvidia/0/).
	NvidiaHostLibDir = "/run/host-nvidia"

	NvidiaContainerRuntimePath = "/usr/bin/nvidia-container-runtime"
	NvidiaRuntimeClassName     = "nvidia"
	NvidiaCTKPath              = "/usr/bin/nvidia-ctk"

	// CDISpecDir is the directory where CDI specifications are stored inside the
	// nspawn machine. containerd reads specs from this directory when CDI is enabled.
	CDISpecDir = "/etc/cdi"

	// CDISpecFile is the path to the NVIDIA CDI specification file inside the
	// nspawn machine. This is generated by nvidia-ctk cdi generate.
	CDISpecFile = "/etc/cdi/nvidia.yaml"

	// Default OCI images for the nspawn rootfs when no image is explicitly
	// configured or set via AGENT_OCI_IMAGE.
	DefaultOCIImage       = "ghcr.io/azure/agent-ubuntu2404:v20260619"
	DefaultNvidiaOCIImage = "ghcr.io/azure/agent-ubuntu2404-nvidia:v20260619"

	// Deprecated: use DefaultNvidiaOCIImage.
	DefaultNvidiaOCImage = DefaultNvidiaOCIImage

	SystemdUnitContainerd   = "containerd.service"
	ContainerdConfigPath    = "/etc/containerd/config.toml"
	ContainerdConfDropInDir = "/etc/containerd/conf.d"

	SystemdUnitKubelet             = "kubelet.service"
	KubeletKubeconfigPath          = "/var/lib/kubelet/kubeconfig"
	KubeletBootstrapKubeconfigPath = "/var/lib/kubelet/bootstrap-kubeconfig"
	KubeletPKIDir                  = "/etc/kubernetes/pki"
	KubeletAPIServerCACertPath     = "/etc/kubernetes/pki/apiserver-client-ca.crt"
	KubeletServiceDropInDir        = "/etc/systemd/system/kubelet.service.d"
	KubeletStaticPodManifestsDir   = "/etc/kubernetes/manifests"
)
