// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskState enumerates the possible terminal states for a task.
type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_SUCCEEDED   TaskState = 1
	TaskState_TASK_STATE_FAILED      TaskState = 2
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_SUCCEEDED",
		2: "TASK_STATE_FAILED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_SUCCEEDED":   1,
		"TASK_STATE_FAILED":      2,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// PullTasksRequest is sent once by the agent when it opens a PullTasks stream.
type PullTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullTasksRequest) Reset() {
	*x = PullTasksRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTasksRequest) ProtoMessage() {}

func (x *PullTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTasksRequest.ProtoReflect.Descriptor instead.
func (*PullTasksRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// PullTasksResponse wraps a single task pushed to the agent over the stream.
type PullTasksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task contains the next task the agent should execute.
	Task          *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullTasksResponse) Reset() {
	*x = PullTasksResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTasksResponse) ProtoMessage() {}

func (x *PullTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTasksResponse.ProtoReflect.Descriptor instead.
func (*PullTasksResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PullTasksResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// Task represents a unit of work assigned to the agent.
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a server-assigned unique identifier for this task.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// spec carries the task-type-specific payload. Exactly one field must be set.
	//
	// Types that are valid to be assigned to Spec:
	//
	//	*Task_NodeUpdate
	Spec isTask_Spec `protobuf_oneof:"spec"`
	// created_at is the server timestamp when the task was created.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetSpec() isTask_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Task) GetNodeUpdate() *NodeUpdateSpec {
	if x != nil {
		if x, ok := x.Spec.(*Task_NodeUpdate); ok {
			return x.NodeUpdate
		}
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type isTask_Spec interface {
	isTask_Spec()
}

type Task_NodeUpdate struct {
	NodeUpdate *NodeUpdateSpec `protobuf:"bytes,2,opt,name=node_update,json=nodeUpdate,proto3,oneof"`
}

func (*Task_NodeUpdate) isTask_Spec() {}

// NodeUpdateSpec is the payload for a node update task. Fields mirror the
// agent configuration (see docs/content/reference/agent/configuration.md).
// The agent uses these values to re-provision the node, which includes
// pointing it at a different cluster at runtime.
type NodeUpdateSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kubernetes_version is the target Kubernetes version (e.g. "1.33.1").
	KubernetesVersion string `protobuf:"bytes,1,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	// api_server is the address of the Kubernetes API server.
	ApiServer string `protobuf:"bytes,2,opt,name=api_server,json=apiServer,proto3" json:"api_server,omitempty"`
	// ca_cert_base64 is the base64-encoded cluster CA certificate.
	CaCertBase64 string `protobuf:"bytes,3,opt,name=ca_cert_base64,json=caCertBase64,proto3" json:"ca_cert_base64,omitempty"`
	// cluster_dns is the ClusterIP of the kube-dns Service.
	ClusterDns string `protobuf:"bytes,4,opt,name=cluster_dns,json=clusterDns,proto3" json:"cluster_dns,omitempty"`
	// bootstrap_token is the token used for TLS bootstrapping. Omit when
	// using TPM attestation.
	BootstrapToken string `protobuf:"bytes,5,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	// oci_image is the OCI image reference for the rootfs. When empty the agent
	// falls back to debootstrap.
	OciImage string `protobuf:"bytes,6,opt,name=oci_image,json=ociImage,proto3" json:"oci_image,omitempty"`
	// node_labels are key-value labels applied to the Node on registration.
	NodeLabels map[string]string `protobuf:"bytes,7,rep,name=node_labels,json=nodeLabels,proto3" json:"node_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// register_with_taints are taints applied to the Node on registration
	// in "key=value:effect" format.
	RegisterWithTaints []string `protobuf:"bytes,8,rep,name=register_with_taints,json=registerWithTaints,proto3" json:"register_with_taints,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeUpdateSpec) Reset() {
	*x = NodeUpdateSpec{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUpdateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUpdateSpec) ProtoMessage() {}

func (x *NodeUpdateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUpdateSpec.ProtoReflect.Descriptor instead.
func (*NodeUpdateSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *NodeUpdateSpec) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *NodeUpdateSpec) GetApiServer() string {
	if x != nil {
		return x.ApiServer
	}
	return ""
}

func (x *NodeUpdateSpec) GetCaCertBase64() string {
	if x != nil {
		return x.CaCertBase64
	}
	return ""
}

func (x *NodeUpdateSpec) GetClusterDns() string {
	if x != nil {
		return x.ClusterDns
	}
	return ""
}

func (x *NodeUpdateSpec) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *NodeUpdateSpec) GetOciImage() string {
	if x != nil {
		return x.OciImage
	}
	return ""
}

func (x *NodeUpdateSpec) GetNodeLabels() map[string]string {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

func (x *NodeUpdateSpec) GetRegisterWithTaints() []string {
	if x != nil {
		return x.RegisterWithTaints
	}
	return nil
}

// ReportTaskStatusRequest is sent by the agent to report task completion.
type ReportTaskStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id is the id of the completed task.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// state indicates whether the task succeeded or failed.
	State TaskState `protobuf:"varint,2,opt,name=state,proto3,enum=unbounded.agent.v1.TaskState" json:"state,omitempty"`
	// message is an optional human-readable status or error description.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskStatusRequest) Reset() {
	*x = ReportTaskStatusRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskStatusRequest) ProtoMessage() {}

func (x *ReportTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ReportTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskStatusRequest) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *ReportTaskStatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ReportTaskStatusResponse is the server acknowledgement.
type ReportTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskStatusResponse) Reset() {
	*x = ReportTaskStatusResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskStatusResponse) ProtoMessage() {}

func (x *ReportTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x12unbounded.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n" +
	"\x10PullTasksRequest\"A\n" +
	"\x11PullTasksResponse\x12,\n" +
	"\x04task\x18\x01 \x01(\v2\x18.unbounded.agent.v1.TaskR\x04task\"\xa0\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\vnode_update\x18\x02 \x01(\v2\".unbounded.agent.v1.NodeUpdateSpecH\x00R\n" +
	"nodeUpdate\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x06\n" +
	"\x04spec\"\xb1\x03\n" +
	"\x0eNodeUpdateSpec\x12-\n" +
	"\x12kubernetes_version\x18\x01 \x01(\tR\x11kubernetesVersion\x12\x1d\n" +
	"\n" +
	"api_server\x18\x02 \x01(\tR\tapiServer\x12$\n" +
	"\x0eca_cert_base64\x18\x03 \x01(\tR\fcaCertBase64\x12\x1f\n" +
	"\vcluster_dns\x18\x04 \x01(\tR\n" +
	"clusterDns\x12'\n" +
	"\x0fbootstrap_token\x18\x05 \x01(\tR\x0ebootstrapToken\x12\x1b\n" +
	"\toci_image\x18\x06 \x01(\tR\bociImage\x12S\n" +
	"\vnode_labels\x18\a \x03(\v22.unbounded.agent.v1.NodeUpdateSpec.NodeLabelsEntryR\n" +
	"nodeLabels\x120\n" +
	"\x14register_with_taints\x18\b \x03(\tR\x12registerWithTaints\x1a=\n" +
	"\x0fNodeLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\x17ReportTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x123\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1d.unbounded.agent.v1.TaskStateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x1a\n" +
	"\x18ReportTaskStatusResponse*X\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_STATE_SUCCEEDED\x10\x01\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x022\xd7\x01\n" +
	"\n" +
	"TaskServer\x12Z\n" +
	"\tPullTasks\x12$.unbounded.agent.v1.PullTasksRequest\x1a%.unbounded.agent.v1.PullTasksResponse0\x01\x12m\n" +
	"\x10ReportTaskStatus\x12+.unbounded.agent.v1.ReportTaskStatusRequest\x1a,.unbounded.agent.v1.ReportTaskStatusResponseB6Z4github.com/Azure/unbounded-kube/agent/api/v1;agentv1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agent_proto_goTypes = []any{
	(TaskState)(0),                   // 0: unbounded.agent.v1.TaskState
	(*PullTasksRequest)(nil),         // 1: unbounded.agent.v1.PullTasksRequest
	(*PullTasksResponse)(nil),        // 2: unbounded.agent.v1.PullTasksResponse
	(*Task)(nil),                     // 3: unbounded.agent.v1.Task
	(*NodeUpdateSpec)(nil),           // 4: unbounded.agent.v1.NodeUpdateSpec
	(*ReportTaskStatusRequest)(nil),  // 5: unbounded.agent.v1.ReportTaskStatusRequest
	(*ReportTaskStatusResponse)(nil), // 6: unbounded.agent.v1.ReportTaskStatusResponse
	nil,                              // 7: unbounded.agent.v1.NodeUpdateSpec.NodeLabelsEntry
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_agent_proto_depIdxs = []int32{
	3, // 0: unbounded.agent.v1.PullTasksResponse.task:type_name -> unbounded.agent.v1.Task
	4, // 1: unbounded.agent.v1.Task.node_update:type_name -> unbounded.agent.v1.NodeUpdateSpec
	8, // 2: unbounded.agent.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	7, // 3: unbounded.agent.v1.NodeUpdateSpec.node_labels:type_name -> unbounded.agent.v1.NodeUpdateSpec.NodeLabelsEntry
	0, // 4: unbounded.agent.v1.ReportTaskStatusRequest.state:type_name -> unbounded.agent.v1.TaskState
	1, // 5: unbounded.agent.v1.TaskServer.PullTasks:input_type -> unbounded.agent.v1.PullTasksRequest
	5, // 6: unbounded.agent.v1.TaskServer.ReportTaskStatus:input_type -> unbounded.agent.v1.ReportTaskStatusRequest
	2, // 7: unbounded.agent.v1.TaskServer.PullTasks:output_type -> unbounded.agent.v1.PullTasksResponse
	6, // 8: unbounded.agent.v1.TaskServer.ReportTaskStatus:output_type -> unbounded.agent.v1.ReportTaskStatusResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*Task_NodeUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
