// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskServer_PullTasks_FullMethodName        = "/unbounded.agent.v1.TaskServer/PullTasks"
	TaskServer_ReportTaskStatus_FullMethodName = "/unbounded.agent.v1.TaskServer/ReportTaskStatus"
)

// TaskServerClient is the client API for TaskServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskServer defines the task-pulling interface used by the unbounded-agent
// to receive work from its control plane.
type TaskServerClient interface {
	// PullTasks is a server-streaming RPC. The agent opens a long-lived stream
	// and the server pushes tasks as they become available.
	PullTasks(ctx context.Context, in *PullTasksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullTasksResponse], error)
	// ReportTaskStatus allows the agent to report the outcome of a previously
	// pulled task back to the server.
	ReportTaskStatus(ctx context.Context, in *ReportTaskStatusRequest, opts ...grpc.CallOption) (*ReportTaskStatusResponse, error)
}

type taskServerClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServerClient(cc grpc.ClientConnInterface) TaskServerClient {
	return &taskServerClient{cc}
}

func (c *taskServerClient) PullTasks(ctx context.Context, in *PullTasksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullTasksResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskServer_ServiceDesc.Streams[0], TaskServer_PullTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullTasksRequest, PullTasksResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskServer_PullTasksClient = grpc.ServerStreamingClient[PullTasksResponse]

func (c *taskServerClient) ReportTaskStatus(ctx context.Context, in *ReportTaskStatusRequest, opts ...grpc.CallOption) (*ReportTaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTaskStatusResponse)
	err := c.cc.Invoke(ctx, TaskServer_ReportTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServerServer is the server API for TaskServer service.
// All implementations must embed UnimplementedTaskServerServer
// for forward compatibility.
//
// TaskServer defines the task-pulling interface used by the unbounded-agent
// to receive work from its control plane.
type TaskServerServer interface {
	// PullTasks is a server-streaming RPC. The agent opens a long-lived stream
	// and the server pushes tasks as they become available.
	PullTasks(*PullTasksRequest, grpc.ServerStreamingServer[PullTasksResponse]) error
	// ReportTaskStatus allows the agent to report the outcome of a previously
	// pulled task back to the server.
	ReportTaskStatus(context.Context, *ReportTaskStatusRequest) (*ReportTaskStatusResponse, error)
	mustEmbedUnimplementedTaskServerServer()
}

// UnimplementedTaskServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServerServer struct{}

func (UnimplementedTaskServerServer) PullTasks(*PullTasksRequest, grpc.ServerStreamingServer[PullTasksResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PullTasks not implemented")
}
func (UnimplementedTaskServerServer) ReportTaskStatus(context.Context, *ReportTaskStatusRequest) (*ReportTaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTaskStatus not implemented")
}
func (UnimplementedTaskServerServer) mustEmbedUnimplementedTaskServerServer() {}
func (UnimplementedTaskServerServer) testEmbeddedByValue()                    {}

// UnsafeTaskServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServerServer will
// result in compilation errors.
type UnsafeTaskServerServer interface {
	mustEmbedUnimplementedTaskServerServer()
}

func RegisterTaskServerServer(s grpc.ServiceRegistrar, srv TaskServerServer) {
	// If the following call pancis, it indicates UnimplementedTaskServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskServer_ServiceDesc, srv)
}

func _TaskServer_PullTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullTasksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskServerServer).PullTasks(m, &grpc.GenericServerStream[PullTasksRequest, PullTasksResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskServer_PullTasksServer = grpc.ServerStreamingServer[PullTasksResponse]

func _TaskServer_ReportTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServerServer).ReportTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServer_ReportTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServerServer).ReportTaskStatus(ctx, req.(*ReportTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskServer_ServiceDesc is the grpc.ServiceDesc for TaskServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "unbounded.agent.v1.TaskServer",
	HandlerType: (*TaskServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportTaskStatus",
			Handler:    _TaskServer_ReportTaskStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullTasks",
			Handler:       _TaskServer_PullTasks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
