# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0

FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.4-trixie AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG TARGETOS
ARG TARGETARCH
ARG VERSION=dev
ARG GIT_COMMIT=
ARG BUILD_TIME=
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    make racer-controller-build VERSION=${VERSION} ${GIT_COMMIT:+GIT_COMMIT=${GIT_COMMIT}} ${BUILD_TIME:+BUILD_TIME=${BUILD_TIME}}

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /src/bin/racer-controller /racer-controller
COPY LICENSE NOTICE /usr/share/licenses/racer-controller/
ENTRYPOINT ["/racer-controller"]
