// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: config.proto

package racerconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cohort int32

const (
	Cohort_COHORT_0 Cohort = 0
	Cohort_COHORT_1 Cohort = 1
	Cohort_COHORT_2 Cohort = 2
)

// Enum value maps for Cohort.
var (
	Cohort_name = map[int32]string{
		0: "COHORT_0",
		1: "COHORT_1",
		2: "COHORT_2",
	}
	Cohort_value = map[string]int32{
		"COHORT_0": 0,
		"COHORT_1": 1,
		"COHORT_2": 2,
	}
)

func (x Cohort) Enum() *Cohort {
	p := new(Cohort)
	*p = x
	return p
}

func (x Cohort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cohort) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (Cohort) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x Cohort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cohort.Descriptor instead.
func (Cohort) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

type Kind int32

const (
	// Optimistic concurrency control. Checksummed. Never cached.
	// Each 4 KiB block is placed on its own.
	Kind_MUTABLE Kind = 0
	// Write-once per tombstone epoch, per 4 KiB block. Not checksummed. Cacheable.
	// Blocks are placed in absolute 4 MiB aligned stripes: the 1024 blocks of a stripe
	// share a consensus group, and nothing else.
	Kind_IMMUTABLE Kind = 1
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "MUTABLE",
		1: "IMMUTABLE",
	}
	Kind_value = map[string]int32{
		"MUTABLE":   0,
		"IMMUTABLE": 1,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[1].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[1]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

type NodeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic config version. Must increment when the config has been modified.
	Generation    uint64      `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Node          *Node       `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Universes     []*Universe `protobuf:"bytes,3,rep,name=universes,proto3" json:"universes,omitempty"`
	Devices       []*Device   `protobuf:"bytes,4,rep,name=devices,proto3" json:"devices,omitempty"`
	Policy        *Policy     `protobuf:"bytes,5,opt,name=policy,proto3,oneof" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *NodeConfig) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *NodeConfig) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeConfig) GetUniverses() []*Universe {
	if x != nil {
		return x.Universes
	}
	return nil
}

func (x *NodeConfig) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *NodeConfig) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Zone          uint32                 `protobuf:"varint,2,opt,name=zone,proto3" json:"zone,omitempty"`
	Cohort        *Cohort                `protobuf:"varint,3,opt,name=cohort,proto3,enum=racer.config.Cohort,oneof" json:"cohort,omitempty"`
	Store         *Store                 `protobuf:"bytes,4,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetZone() uint32 {
	if x != nil {
		return x.Zone
	}
	return 0
}

func (x *Node) GetCohort() Cohort {
	if x != nil && x.Cohort != nil {
		return *x.Cohort
	}
	return Cohort_COHORT_0
}

func (x *Node) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

type Store struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The length of the backing file in bytes. Non-zero and a multiple of 4096.
	// Created at this length on first start, and expanded later (but never shrunk).
	SizeBytes      uint64  `protobuf:"varint,1,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MaxIops        *uint64 `protobuf:"varint,2,opt,name=max_iops,json=maxIops,proto3,oneof" json:"max_iops,omitempty"`
	MaxBytesPerSec *uint64 `protobuf:"varint,3,opt,name=max_bytes_per_sec,json=maxBytesPerSec,proto3,oneof" json:"max_bytes_per_sec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *Store) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Store) GetMaxIops() uint64 {
	if x != nil && x.MaxIops != nil {
		return *x.MaxIops
	}
	return 0
}

func (x *Store) GetMaxBytesPerSec() uint64 {
	if x != nil && x.MaxBytesPerSec != nil {
		return *x.MaxBytesPerSec
	}
	return 0
}

type Universe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique, below 2^26.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Bumped by the control plane whenever this universe's topology changes.
	Epoch uint32 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Set of nodes sharing connections with this one.
	Peers []*Peer `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	// The consensus groups of this zone, within its universe.
	// Length is immutable for the life of the zone to simplify the sharding scheme.
	// At most one member of any trio can change per epoch.
	Catalog []*Trio `protobuf:"bytes,4,rep,name=catalog,proto3" json:"catalog,omitempty"`
	// Peering connections with other zones.
	// Control planes should establish some connections between zones, represented here as "gateway" peers.
	Zones []*Zone `protobuf:"bytes,5,rep,name=zones,proto3" json:"zones,omitempty"`
	// A collection of sparsely allocated block extents that can be presented to clients.
	Extents []*Extent `protobuf:"bytes,6,rep,name=extents,proto3" json:"extents,omitempty"`
	// The ublk minor this node exports this universe's fabric namespace on, so the path is
	// `/dev/ublkb<fabric_device_id>` and the control plane knows it before the node starts.
	// Non-zero, unique on this node against every other universe's value and every
	// `Device.id`, and counted against the same 256 export budget. The control plane
	// publishes this device as an NVMe-oF namespace to exactly this universe's members, and
	// the paths it hands back are the `Peer.device` entries they open. Frozen for the life of
	// the universe here: changing it moves every peer's path and drops every open fd.
	FabricDeviceId uint32 `protobuf:"varint,7,opt,name=fabric_device_id,json=fabricDeviceId,proto3" json:"fabric_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Universe) Reset() {
	*x = Universe{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Universe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Universe) ProtoMessage() {}

func (x *Universe) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Universe.ProtoReflect.Descriptor instead.
func (*Universe) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *Universe) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Universe) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Universe) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Universe) GetCatalog() []*Trio {
	if x != nil {
		return x.Catalog
	}
	return nil
}

func (x *Universe) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *Universe) GetExtents() []*Extent {
	if x != nil {
		return x.Extents
	}
	return nil
}

func (x *Universe) GetFabricDeviceId() uint32 {
	if x != nil {
		return x.FabricDeviceId
	}
	return 0
}

type Peer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The remote node's id. Non-zero, not our own, unique within this universe's peer list.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Local path to this peer's namespace *for this universe*, as attached by the control plane.
	Device        string `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *Peer) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type Trio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cohort_0      uint32                 `protobuf:"varint,1,opt,name=cohort_0,json=cohort0,proto3" json:"cohort_0,omitempty"`
	Cohort_1      uint32                 `protobuf:"varint,2,opt,name=cohort_1,json=cohort1,proto3" json:"cohort_1,omitempty"`
	Cohort_2      uint32                 `protobuf:"varint,3,opt,name=cohort_2,json=cohort2,proto3" json:"cohort_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trio) Reset() {
	*x = Trio{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trio) ProtoMessage() {}

func (x *Trio) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trio.ProtoReflect.Descriptor instead.
func (*Trio) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *Trio) GetCohort_0() uint32 {
	if x != nil {
		return x.Cohort_0
	}
	return 0
}

func (x *Trio) GetCohort_1() uint32 {
	if x != nil {
		return x.Cohort_1
	}
	return 0
}

func (x *Trio) GetCohort_2() uint32 {
	if x != nil {
		return x.Cohort_2
	}
	return 0
}

type Zone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Gateways      []uint32               `protobuf:"varint,2,rep,packed,name=gateways,proto3" json:"gateways,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *Zone) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Zone) GetGateways() []uint32 {
	if x != nil {
		return x.Gateways
	}
	return nil
}

type Extent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Non-zero, and unique across every universe in this file. Never reused.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Where this extent starts in its universe's address space, in 4 KiB blocks.
	// Immutable.
	BaseLba uint64 `protobuf:"varint,2,opt,name=base_lba,json=baseLba,proto3" json:"base_lba,omitempty"`
	// Length in 4 KiB blocks, whatever the kind. Not in bytes.
	// Immutable.
	Blocks uint64 `protobuf:"varint,3,opt,name=blocks,proto3" json:"blocks,omitempty"`
	// The kind of an extent determines its concurrency controls, whether its data is
	// checksummed, and whether it may be cached. Every kind addresses 4 KiB blocks.
	// Immutable.
	Kind Kind `protobuf:"varint,4,opt,name=kind,proto3,enum=racer.config.Kind" json:"kind,omitempty"`
	// The zone of the extent.
	// Must be our own zone or one listed in this universe's `zones`.
	// Immutable.
	Zone uint32 `protobuf:"varint,5,opt,name=zone,proto3" json:"zone,omitempty"`
	// The ID of the zone this extent is being migrated to.
	// 0 when not migrating.
	// The control plane must determine when the migration is done, and swap `next_zone -> zone`.
	NextZone uint32 `protobuf:"varint,6,opt,name=next_zone,json=nextZone,proto3" json:"next_zone,omitempty"`
	// Clean up unreachable immutable blocks, older than the given epoch.
	// Control planes should advance this value ONLY once they're certain that a tombstone is
	// no longer reachable by the application.
	TombstoneEpoch uint32 `protobuf:"varint,7,opt,name=tombstone_epoch,json=tombstoneEpoch,proto3" json:"tombstone_epoch,omitempty"`
	// Cache admission for this extent, and the only knob deciding whether a block of it may
	// enter a node's cache at all:
	//
	//	0       never; blocks of this extent are not cached, and are not even counted
	//	1       admit on first sight
	//	2..=15  admit once the frequency estimate reaches this value
	//
	// The estimate is requests per 250 ms decay interval.
	//
	// It is an admission threshold and nothing more: it reserves no capacity and does not
	// rank extents. Once admitted, a block competes for slots purely on measured frequency, so
	// a hot block of one extent displaces a cold block of another whatever their thresholds
	// were. Raising it evicts nothing already resident. Changing it is legal on any reload,
	// and dropping to 0 stops admission immediately.
	CacheAdmit uint32 `protobuf:"varint,8,opt,name=cache_admit,json=cacheAdmit,proto3" json:"cache_admit,omitempty"`
	// Zones whose caches are optimistically filled with blocks of this extent as they are committed.
	// Best effort: trios that are unreachable at commit time may not be warmed.
	// Only supports IMMUTABLE extents, with a non-zero cache_admit.
	WarmZones     []uint32 `protobuf:"varint,9,rep,packed,name=warm_zones,json=warmZones,proto3" json:"warm_zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extent) Reset() {
	*x = Extent{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extent) ProtoMessage() {}

func (x *Extent) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extent.ProtoReflect.Descriptor instead.
func (*Extent) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *Extent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Extent) GetBaseLba() uint64 {
	if x != nil {
		return x.BaseLba
	}
	return 0
}

func (x *Extent) GetBlocks() uint64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *Extent) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_MUTABLE
}

func (x *Extent) GetZone() uint32 {
	if x != nil {
		return x.Zone
	}
	return 0
}

func (x *Extent) GetNextZone() uint32 {
	if x != nil {
		return x.NextZone
	}
	return 0
}

func (x *Extent) GetTombstoneEpoch() uint32 {
	if x != nil {
		return x.TombstoneEpoch
	}
	return 0
}

func (x *Extent) GetCacheAdmit() uint32 {
	if x != nil {
		return x.CacheAdmit
	}
	return 0
}

func (x *Extent) GetWarmZones() []uint32 {
	if x != nil {
		return x.WarmZones
	}
	return nil
}

type Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique, including fabric device IDs.
	// Passed to ublk as the "minor", e.g. `/dev/ublkb<id>`.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Extent ids in the order they are concatenated.
	// no duplicates, and every id must name an extent of some universe in this file.
	// Immutable.
	Extents       []uint32 `protobuf:"varint,2,rep,packed,name=extents,proto3" json:"extents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *Device) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Device) GetExtents() []uint32 {
	if x != nil {
		return x.Extents
	}
	return nil
}

type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DRAM ceiling for the 4 KiB index, in bytes.
	// Defaults to 8 GiB.
	MaxIndexBytes *uint64 `protobuf:"varint,1,opt,name=max_index_bytes,json=maxIndexBytes,proto3,oneof" json:"max_index_bytes,omitempty"`
	// DRAM ceiling for the OCC read version pool, in bytes.
	// Split evenly across cores.
	// Defaults to 256 MiB.
	OccBytes *uint64 `protobuf:"varint,2,opt,name=occ_bytes,json=occBytes,proto3,oneof" json:"occ_bytes,omitempty"`
	// Registers one anti-entropy sweep will pull while replaying a group, and the number it
	// will push per extent while handing one to another zone.
	// Raise to repair nodes faster, lower to reduce risk of impact to active clients caused by live migrations.
	// Defaults to 4096.
	RepairsPerReplay *uint32 `protobuf:"varint,4,opt,name=repairs_per_replay,json=repairsPerReplay,proto3,oneof" json:"repairs_per_replay,omitempty"`
	// DRAM ceiling for the read cache's index, in bytes.
	// Defaults to 1 GiB.
	CacheIndexBytes *uint64 `protobuf:"varint,5,opt,name=cache_index_bytes,json=cacheIndexBytes,proto3,oneof" json:"cache_index_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *Policy) GetMaxIndexBytes() uint64 {
	if x != nil && x.MaxIndexBytes != nil {
		return *x.MaxIndexBytes
	}
	return 0
}

func (x *Policy) GetOccBytes() uint64 {
	if x != nil && x.OccBytes != nil {
		return *x.OccBytes
	}
	return 0
}

func (x *Policy) GetRepairsPerReplay() uint32 {
	if x != nil && x.RepairsPerReplay != nil {
		return *x.RepairsPerReplay
	}
	return 0
}

func (x *Policy) GetCacheIndexBytes() uint64 {
	if x != nil && x.CacheIndexBytes != nil {
		return *x.CacheIndexBytes
	}
	return 0
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\fracer.config\"\xf8\x01\n" +
	"\n" +
	"NodeConfig\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12&\n" +
	"\x04node\x18\x02 \x01(\v2\x12.racer.config.NodeR\x04node\x124\n" +
	"\tuniverses\x18\x03 \x03(\v2\x16.racer.config.UniverseR\tuniverses\x12.\n" +
	"\adevices\x18\x04 \x03(\v2\x14.racer.config.DeviceR\adevices\x121\n" +
	"\x06policy\x18\x05 \x01(\v2\x14.racer.config.PolicyH\x00R\x06policy\x88\x01\x01B\t\n" +
	"\a_policy\"\x93\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\rR\x04zone\x121\n" +
	"\x06cohort\x18\x03 \x01(\x0e2\x14.racer.config.CohortH\x00R\x06cohort\x88\x01\x01\x12)\n" +
	"\x05store\x18\x04 \x01(\v2\x13.racer.config.StoreR\x05storeB\t\n" +
	"\a_cohort\"\x99\x01\n" +
	"\x05Store\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x01 \x01(\x04R\tsizeBytes\x12\x1e\n" +
	"\bmax_iops\x18\x02 \x01(\x04H\x00R\amaxIops\x88\x01\x01\x12.\n" +
	"\x11max_bytes_per_sec\x18\x03 \x01(\x04H\x01R\x0emaxBytesPerSec\x88\x01\x01B\v\n" +
	"\t_max_iopsB\x14\n" +
	"\x12_max_bytes_per_sec\"\x8c\x02\n" +
	"\bUniverse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\x12(\n" +
	"\x05peers\x18\x03 \x03(\v2\x12.racer.config.PeerR\x05peers\x12,\n" +
	"\acatalog\x18\x04 \x03(\v2\x12.racer.config.TrioR\acatalog\x12(\n" +
	"\x05zones\x18\x05 \x03(\v2\x12.racer.config.ZoneR\x05zones\x12.\n" +
	"\aextents\x18\x06 \x03(\v2\x14.racer.config.ExtentR\aextents\x12(\n" +
	"\x10fabric_device_id\x18\a \x01(\rR\x0efabricDeviceId\".\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\"W\n" +
	"\x04Trio\x12\x19\n" +
	"\bcohort_0\x18\x01 \x01(\rR\acohort0\x12\x19\n" +
	"\bcohort_1\x18\x02 \x01(\rR\acohort1\x12\x19\n" +
	"\bcohort_2\x18\x03 \x01(\rR\acohort2\"2\n" +
	"\x04Zone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bgateways\x18\x02 \x03(\rR\bgateways\"\x8d\x02\n" +
	"\x06Extent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bbase_lba\x18\x02 \x01(\x04R\abaseLba\x12\x16\n" +
	"\x06blocks\x18\x03 \x01(\x04R\x06blocks\x12&\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x12.racer.config.KindR\x04kind\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\rR\x04zone\x12\x1b\n" +
	"\tnext_zone\x18\x06 \x01(\rR\bnextZone\x12'\n" +
	"\x0ftombstone_epoch\x18\a \x01(\rR\x0etombstoneEpoch\x12\x1f\n" +
	"\vcache_admit\x18\b \x01(\rR\n" +
	"cacheAdmit\x12\x1d\n" +
	"\n" +
	"warm_zones\x18\t \x03(\rR\twarmZones\"2\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aextents\x18\x02 \x03(\rR\aextents\"\x8a\x02\n" +
	"\x06Policy\x12+\n" +
	"\x0fmax_index_bytes\x18\x01 \x01(\x04H\x00R\rmaxIndexBytes\x88\x01\x01\x12 \n" +
	"\tocc_bytes\x18\x02 \x01(\x04H\x01R\boccBytes\x88\x01\x01\x121\n" +
	"\x12repairs_per_replay\x18\x04 \x01(\rH\x02R\x10repairsPerReplay\x88\x01\x01\x12/\n" +
	"\x11cache_index_bytes\x18\x05 \x01(\x04H\x03R\x0fcacheIndexBytes\x88\x01\x01B\x12\n" +
	"\x10_max_index_bytesB\f\n" +
	"\n" +
	"_occ_bytesB\x15\n" +
	"\x13_repairs_per_replayB\x14\n" +
	"\x12_cache_index_bytes*2\n" +
	"\x06Cohort\x12\f\n" +
	"\bCOHORT_0\x10\x00\x12\f\n" +
	"\bCOHORT_1\x10\x01\x12\f\n" +
	"\bCOHORT_2\x10\x02*\"\n" +
	"\x04Kind\x12\v\n" +
	"\aMUTABLE\x10\x00\x12\r\n" +
	"\tIMMUTABLE\x10\x01B2Z0github.com/Azure/unbounded/api/racer;racerconfigb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_config_proto_goTypes = []any{
	(Cohort)(0),        // 0: racer.config.Cohort
	(Kind)(0),          // 1: racer.config.Kind
	(*NodeConfig)(nil), // 2: racer.config.NodeConfig
	(*Node)(nil),       // 3: racer.config.Node
	(*Store)(nil),      // 4: racer.config.Store
	(*Universe)(nil),   // 5: racer.config.Universe
	(*Peer)(nil),       // 6: racer.config.Peer
	(*Trio)(nil),       // 7: racer.config.Trio
	(*Zone)(nil),       // 8: racer.config.Zone
	(*Extent)(nil),     // 9: racer.config.Extent
	(*Device)(nil),     // 10: racer.config.Device
	(*Policy)(nil),     // 11: racer.config.Policy
}
var file_config_proto_depIdxs = []int32{
	3,  // 0: racer.config.NodeConfig.node:type_name -> racer.config.Node
	5,  // 1: racer.config.NodeConfig.universes:type_name -> racer.config.Universe
	10, // 2: racer.config.NodeConfig.devices:type_name -> racer.config.Device
	11, // 3: racer.config.NodeConfig.policy:type_name -> racer.config.Policy
	0,  // 4: racer.config.Node.cohort:type_name -> racer.config.Cohort
	4,  // 5: racer.config.Node.store:type_name -> racer.config.Store
	6,  // 6: racer.config.Universe.peers:type_name -> racer.config.Peer
	7,  // 7: racer.config.Universe.catalog:type_name -> racer.config.Trio
	8,  // 8: racer.config.Universe.zones:type_name -> racer.config.Zone
	9,  // 9: racer.config.Universe.extents:type_name -> racer.config.Extent
	1,  // 10: racer.config.Extent.kind:type_name -> racer.config.Kind
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_config_proto_msgTypes[0].OneofWrappers = []any{}
	file_config_proto_msgTypes[1].OneofWrappers = []any{}
	file_config_proto_msgTypes[2].OneofWrappers = []any{}
	file_config_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
