// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: control.proto

package racerconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Every update replaces this entire message. Empty lists remove all entries.
type Snapshot struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Universe []byte                 `protobuf:"bytes,1,opt,name=universe,proto3" json:"universe,omitempty"` // 32 bytes, pinned by bootstrap configuration
	Node     []byte                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`         // 32 bytes, pinned by bootstrap configuration
	Revision uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Peers    []*Peer                `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"` // only this node's direct connections
	Volumes  []*Volume              `protobuf:"bytes,5,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Fabric   string                 `protobuf:"bytes,6,opt,name=fabric,proto3" json:"fabric,omitempty"`
	// Config generation shared across nodes in a universe; zero means unspecified.
	// Observability only: revision still orders updates, Topology.epoch orders routing.
	Epoch uint64 `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Explicitly authorizes readiness without listeners after worker activation.
	// Only selected, eligible idle members receive this; empty removal snapshots
	// leave it false. An idle snapshot must have no volumes or peers.
	Idle          bool `protobuf:"varint,8,opt,name=idle,proto3" json:"idle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetUniverse() []byte {
	if x != nil {
		return x.Universe
	}
	return nil
}

func (x *Snapshot) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Snapshot) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Snapshot) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Snapshot) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *Snapshot) GetFabric() string {
	if x != nil {
		return x.Fabric
	}
	return ""
}

func (x *Snapshot) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Snapshot) GetIdle() bool {
	if x != nil {
		return x.Idle
	}
	return false
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fabric        string                 `protobuf:"bytes,2,opt,name=fabric,proto3" json:"fabric,omitempty"`
	HttpAddress   string                 `protobuf:"bytes,3,opt,name=http_address,json=httpAddress,proto3" json:"http_address,omitempty"` // IPv4:port or [IPv6]:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peer) GetFabric() string {
	if x != nil {
		return x.Fabric
	}
	return ""
}

func (x *Peer) GetHttpAddress() string {
	if x != nil {
		return x.HttpAddress
	}
	return ""
}

type Volume struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Listen          string                 `protobuf:"bytes,2,opt,name=listen,proto3" json:"listen,omitempty"`                                       // numeric IP:port
	OriginAddress   string                 `protobuf:"bytes,3,opt,name=origin_address,json=originAddress,proto3" json:"origin_address,omitempty"`    // IPv4:port or [IPv6]:port; also HTTP Host
	OriginIdentity  string                 `protobuf:"bytes,4,opt,name=origin_identity,json=originIdentity,proto3" json:"origin_identity,omitempty"` // stable logical dataset identity, independent of address
	CacheGeneration uint64                 `protobuf:"varint,5,opt,name=cache_generation,json=cacheGeneration,proto3" json:"cache_generation,omitempty"`
	// Direct transport peers only. Nonempty lists require topology.
	Peers    []string  `protobuf:"bytes,6,rep,name=peers,proto3" json:"peers,omitempty"`
	Topology *Topology `protobuf:"bytes,7,opt,name=topology,proto3" json:"topology,omitempty"`
	// Primary plus successors, including suppressed slots; default 3, range 1..8.
	MaxCandidateAttempts *uint32 `protobuf:"varint,8,opt,name=max_candidate_attempts,json=maxCandidateAttempts,proto3,oneof" json:"max_candidate_attempts,omitempty"`
	// Required: complete direct membership, including incoming-only peers.
	// Empty explicitly authorizes none.
	PeerEndpoints *VolumePeerEndpoints `protobuf:"bytes,9,opt,name=peer_endpoints,json=peerEndpoints,proto3" json:"peer_endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *Volume) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Volume) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *Volume) GetOriginAddress() string {
	if x != nil {
		return x.OriginAddress
	}
	return ""
}

func (x *Volume) GetOriginIdentity() string {
	if x != nil {
		return x.OriginIdentity
	}
	return ""
}

func (x *Volume) GetCacheGeneration() uint64 {
	if x != nil {
		return x.CacheGeneration
	}
	return 0
}

func (x *Volume) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Volume) GetTopology() *Topology {
	if x != nil {
		return x.Topology
	}
	return nil
}

func (x *Volume) GetMaxCandidateAttempts() uint32 {
	if x != nil && x.MaxCandidateAttempts != nil {
		return *x.MaxCandidateAttempts
	}
	return 0
}

func (x *Volume) GetPeerEndpoints() *VolumePeerEndpoints {
	if x != nil {
		return x.PeerEndpoints
	}
	return nil
}

type VolumePeerEndpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*VolumePeerEndpoint  `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumePeerEndpoints) Reset() {
	*x = VolumePeerEndpoints{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumePeerEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumePeerEndpoints) ProtoMessage() {}

func (x *VolumePeerEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumePeerEndpoints.ProtoReflect.Descriptor instead.
func (*VolumePeerEndpoints) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *VolumePeerEndpoints) GetPeers() []*VolumePeerEndpoint {
	if x != nil {
		return x.Peers
	}
	return nil
}

type VolumePeerEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`                                  // exact identity in Snapshot.peers
	HttpAddress   string                 `protobuf:"bytes,2,opt,name=http_address,json=httpAddress,proto3" json:"http_address,omitempty"` // empty explicitly inherits the global endpoint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumePeerEndpoint) Reset() {
	*x = VolumePeerEndpoint{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumePeerEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumePeerEndpoint) ProtoMessage() {}

func (x *VolumePeerEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumePeerEndpoint.ProtoReflect.Descriptor instead.
func (*VolumePeerEndpoint) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *VolumePeerEndpoint) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *VolumePeerEndpoint) GetHttpAddress() string {
	if x != nil {
		return x.HttpAddress
	}
	return ""
}

// Shared slot geometry/epoch; only local slots and their outgoing neighbors.
// All nodes in a volume agree on epoch and slot_count. Revision is node-local.
type Topology struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Epoch      uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	SlotCount  uint32                 `protobuf:"varint,2,opt,name=slot_count,json=slotCount,proto3" json:"slot_count,omitempty"`
	LocalSlots []uint32               `protobuf:"varint,3,rep,packed,name=local_slots,json=localSlots,proto3" json:"local_slots,omitempty"`
	Neighbors  []*SlotPeer            `protobuf:"bytes,4,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	// Destination-rooted shortest paths (2); absent defaults to 2.
	RoutingAlgorithm *uint32 `protobuf:"varint,5,opt,name=routing_algorithm,json=routingAlgorithm,proto3,oneof" json:"routing_algorithm,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Topology) Reset() {
	*x = Topology{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topology) ProtoMessage() {}

func (x *Topology) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topology.ProtoReflect.Descriptor instead.
func (*Topology) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *Topology) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Topology) GetSlotCount() uint32 {
	if x != nil {
		return x.SlotCount
	}
	return 0
}

func (x *Topology) GetLocalSlots() []uint32 {
	if x != nil {
		return x.LocalSlots
	}
	return nil
}

func (x *Topology) GetNeighbors() []*SlotPeer {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *Topology) GetRoutingAlgorithm() uint32 {
	if x != nil && x.RoutingAlgorithm != nil {
		return *x.RoutingAlgorithm
	}
	return 0
}

type SlotPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Peer          string                 `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotPeer) Reset() {
	*x = SlotPeer{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotPeer) ProtoMessage() {}

func (x *SlotPeer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotPeer.ProtoReflect.Descriptor instead.
func (*SlotPeer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *SlotPeer) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SlotPeer) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

// Embedded in HTTP control commands. Local files use its ProtoJSON form.
// Signed snapshots authenticate the exact serialized plaintext bytes.
type Configuration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Contents:
	//
	//	*Configuration_Snapshot
	//	*Configuration_Signed
	Contents      isConfiguration_Contents `protobuf_oneof:"contents"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *Configuration) GetContents() isConfiguration_Contents {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *Configuration) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Contents.(*Configuration_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *Configuration) GetSigned() *SignedSnapshot {
	if x != nil {
		if x, ok := x.Contents.(*Configuration_Signed); ok {
			return x.Signed
		}
	}
	return nil
}

type isConfiguration_Contents interface {
	isConfiguration_Contents()
}

type Configuration_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type Configuration_Signed struct {
	Signed *SignedSnapshot `protobuf:"bytes,2,opt,name=signed,proto3,oneof"`
}

func (*Configuration_Snapshot) isConfiguration_Contents() {}

func (*Configuration_Signed) isConfiguration_Contents() {}

type SignedSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      []byte                 `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedSnapshot) Reset() {
	*x = SignedSnapshot{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedSnapshot) ProtoMessage() {}

func (x *SignedSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedSnapshot.ProtoReflect.Descriptor instead.
func (*SignedSnapshot) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *SignedSnapshot) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *SignedSnapshot) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Served by /v2/{universe}/{node}.
type ControlCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Universe       []byte                 `protobuf:"bytes,1,opt,name=universe,proto3" json:"universe,omitempty"`
	Node           []byte                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Incarnation    []byte                 `protobuf:"bytes,3,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	SnapshotDigest []byte                 `protobuf:"bytes,4,opt,name=snapshot_digest,json=snapshotDigest,proto3" json:"snapshot_digest,omitempty"`
	Revision       uint64                 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	// 1 prepare, 2 enable receive, 3 activate ingress, 4 retire, 5 abort.
	Phase         uint32         `protobuf:"varint,6,opt,name=phase,proto3" json:"phase,omitempty"`
	Configuration *Configuration `protobuf:"bytes,7,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Profile       uint32         `protobuf:"varint,8,opt,name=profile,proto3" json:"profile,omitempty"` // profile 1: scoped peers, 262144 slots, 64 MiB input
	// Conditional forward correction, checked atomically against never-receive.
	ForwardDigest   []byte `protobuf:"bytes,9,opt,name=forward_digest,json=forwardDigest,proto3" json:"forward_digest,omitempty"`
	ForwardRevision uint64 `protobuf:"varint,10,opt,name=forward_revision,json=forwardRevision,proto3" json:"forward_revision,omitempty"`
	PodUid          string `protobuf:"bytes,11,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"` // TokenReview identity, pinned per subscription
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ControlCommand) Reset() {
	*x = ControlCommand{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCommand) ProtoMessage() {}

func (x *ControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCommand.ProtoReflect.Descriptor instead.
func (*ControlCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *ControlCommand) GetUniverse() []byte {
	if x != nil {
		return x.Universe
	}
	return nil
}

func (x *ControlCommand) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ControlCommand) GetIncarnation() []byte {
	if x != nil {
		return x.Incarnation
	}
	return nil
}

func (x *ControlCommand) GetSnapshotDigest() []byte {
	if x != nil {
		return x.SnapshotDigest
	}
	return nil
}

func (x *ControlCommand) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ControlCommand) GetPhase() uint32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *ControlCommand) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *ControlCommand) GetProfile() uint32 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *ControlCommand) GetForwardDigest() []byte {
	if x != nil {
		return x.ForwardDigest
	}
	return nil
}

func (x *ControlCommand) GetForwardRevision() uint64 {
	if x != nil {
		return x.ForwardRevision
	}
	return 0
}

func (x *ControlCommand) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

type SignedControlCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []byte                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // racer/control/v1 over exact command bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedControlCommand) Reset() {
	*x = SignedControlCommand{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedControlCommand) ProtoMessage() {}

func (x *SignedControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedControlCommand.ProtoReflect.Descriptor instead.
func (*SignedControlCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *SignedControlCommand) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SignedControlCommand) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x10racer.control.v1\"\xfa\x01\n" +
	"\bSnapshot\x12\x1a\n" +
	"\buniverse\x18\x01 \x01(\fR\buniverse\x12\x12\n" +
	"\x04node\x18\x02 \x01(\fR\x04node\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12,\n" +
	"\x05peers\x18\x04 \x03(\v2\x16.racer.control.v1.PeerR\x05peers\x122\n" +
	"\avolumes\x18\x05 \x03(\v2\x18.racer.control.v1.VolumeR\avolumes\x12\x16\n" +
	"\x06fabric\x18\x06 \x01(\tR\x06fabric\x12\x14\n" +
	"\x05epoch\x18\a \x01(\x04R\x05epoch\x12\x12\n" +
	"\x04idle\x18\b \x01(\bR\x04idle\"Q\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06fabric\x18\x02 \x01(\tR\x06fabric\x12!\n" +
	"\fhttp_address\x18\x03 \x01(\tR\vhttpAddress\"\x9d\x03\n" +
	"\x06Volume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06listen\x18\x02 \x01(\tR\x06listen\x12%\n" +
	"\x0eorigin_address\x18\x03 \x01(\tR\roriginAddress\x12'\n" +
	"\x0forigin_identity\x18\x04 \x01(\tR\x0eoriginIdentity\x12)\n" +
	"\x10cache_generation\x18\x05 \x01(\x04R\x0fcacheGeneration\x12\x14\n" +
	"\x05peers\x18\x06 \x03(\tR\x05peers\x126\n" +
	"\btopology\x18\a \x01(\v2\x1a.racer.control.v1.TopologyR\btopology\x129\n" +
	"\x16max_candidate_attempts\x18\b \x01(\rH\x00R\x14maxCandidateAttempts\x88\x01\x01\x12L\n" +
	"\x0epeer_endpoints\x18\t \x01(\v2%.racer.control.v1.VolumePeerEndpointsR\rpeerEndpointsB\x19\n" +
	"\x17_max_candidate_attempts\"Q\n" +
	"\x13VolumePeerEndpoints\x12:\n" +
	"\x05peers\x18\x01 \x03(\v2$.racer.control.v1.VolumePeerEndpointR\x05peers\"K\n" +
	"\x12VolumePeerEndpoint\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12!\n" +
	"\fhttp_address\x18\x02 \x01(\tR\vhttpAddress\"\xe2\x01\n" +
	"\bTopology\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x1d\n" +
	"\n" +
	"slot_count\x18\x02 \x01(\rR\tslotCount\x12\x1f\n" +
	"\vlocal_slots\x18\x03 \x03(\rR\n" +
	"localSlots\x128\n" +
	"\tneighbors\x18\x04 \x03(\v2\x1a.racer.control.v1.SlotPeerR\tneighbors\x120\n" +
	"\x11routing_algorithm\x18\x05 \x01(\rH\x00R\x10routingAlgorithm\x88\x01\x01B\x14\n" +
	"\x12_routing_algorithm\"2\n" +
	"\bSlotPeer\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\tR\x04peer\"\x91\x01\n" +
	"\rConfiguration\x128\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1a.racer.control.v1.SnapshotH\x00R\bsnapshot\x12:\n" +
	"\x06signed\x18\x02 \x01(\v2 .racer.control.v1.SignedSnapshotH\x00R\x06signedB\n" +
	"\n" +
	"\bcontents\"J\n" +
	"\x0eSignedSnapshot\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\fR\bsnapshot\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\x89\x03\n" +
	"\x0eControlCommand\x12\x1a\n" +
	"\buniverse\x18\x01 \x01(\fR\buniverse\x12\x12\n" +
	"\x04node\x18\x02 \x01(\fR\x04node\x12 \n" +
	"\vincarnation\x18\x03 \x01(\fR\vincarnation\x12'\n" +
	"\x0fsnapshot_digest\x18\x04 \x01(\fR\x0esnapshotDigest\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x04R\brevision\x12\x14\n" +
	"\x05phase\x18\x06 \x01(\rR\x05phase\x12E\n" +
	"\rconfiguration\x18\a \x01(\v2\x1f.racer.control.v1.ConfigurationR\rconfiguration\x12\x18\n" +
	"\aprofile\x18\b \x01(\rR\aprofile\x12%\n" +
	"\x0eforward_digest\x18\t \x01(\fR\rforwardDigest\x12)\n" +
	"\x10forward_revision\x18\n" +
	" \x01(\x04R\x0fforwardRevision\x12\x17\n" +
	"\apod_uid\x18\v \x01(\tR\x06podUid\"N\n" +
	"\x14SignedControlCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\fR\acommand\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignatureB2Z0github.com/Azure/unbounded/api/racer;racerconfigb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_control_proto_goTypes = []any{
	(*Snapshot)(nil),             // 0: racer.control.v1.Snapshot
	(*Peer)(nil),                 // 1: racer.control.v1.Peer
	(*Volume)(nil),               // 2: racer.control.v1.Volume
	(*VolumePeerEndpoints)(nil),  // 3: racer.control.v1.VolumePeerEndpoints
	(*VolumePeerEndpoint)(nil),   // 4: racer.control.v1.VolumePeerEndpoint
	(*Topology)(nil),             // 5: racer.control.v1.Topology
	(*SlotPeer)(nil),             // 6: racer.control.v1.SlotPeer
	(*Configuration)(nil),        // 7: racer.control.v1.Configuration
	(*SignedSnapshot)(nil),       // 8: racer.control.v1.SignedSnapshot
	(*ControlCommand)(nil),       // 9: racer.control.v1.ControlCommand
	(*SignedControlCommand)(nil), // 10: racer.control.v1.SignedControlCommand
}
var file_control_proto_depIdxs = []int32{
	1, // 0: racer.control.v1.Snapshot.peers:type_name -> racer.control.v1.Peer
	2, // 1: racer.control.v1.Snapshot.volumes:type_name -> racer.control.v1.Volume
	5, // 2: racer.control.v1.Volume.topology:type_name -> racer.control.v1.Topology
	3, // 3: racer.control.v1.Volume.peer_endpoints:type_name -> racer.control.v1.VolumePeerEndpoints
	4, // 4: racer.control.v1.VolumePeerEndpoints.peers:type_name -> racer.control.v1.VolumePeerEndpoint
	6, // 5: racer.control.v1.Topology.neighbors:type_name -> racer.control.v1.SlotPeer
	0, // 6: racer.control.v1.Configuration.snapshot:type_name -> racer.control.v1.Snapshot
	8, // 7: racer.control.v1.Configuration.signed:type_name -> racer.control.v1.SignedSnapshot
	7, // 8: racer.control.v1.ControlCommand.configuration:type_name -> racer.control.v1.Configuration
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[2].OneofWrappers = []any{}
	file_control_proto_msgTypes[5].OneofWrappers = []any{}
	file_control_proto_msgTypes[7].OneofWrappers = []any{
		(*Configuration_Snapshot)(nil),
		(*Configuration_Signed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
