// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: control.proto

package racerconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Universe []byte                 `protobuf:"bytes,1,opt,name=universe,proto3" json:"universe,omitempty"`
	Node     []byte                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Revision uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Peers    []*Peer                `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	Volumes  []*Volume              `protobuf:"bytes,5,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Fabric   string                 `protobuf:"bytes,6,opt,name=fabric,proto3" json:"fabric,omitempty"`
	Epoch    uint64                 `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Idle     bool                   `protobuf:"varint,8,opt,name=idle,proto3" json:"idle,omitempty"`
	// Placement-independent process catalogs, shared by volume references.
	MemberCatalogs []*MemberCatalog `protobuf:"bytes,9,rep,name=member_catalogs,json=memberCatalogs,proto3" json:"member_catalogs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetUniverse() []byte {
	if x != nil {
		return x.Universe
	}
	return nil
}

func (x *Snapshot) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Snapshot) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Snapshot) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Snapshot) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *Snapshot) GetFabric() string {
	if x != nil {
		return x.Fabric
	}
	return ""
}

func (x *Snapshot) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Snapshot) GetIdle() bool {
	if x != nil {
		return x.Idle
	}
	return false
}

func (x *Snapshot) GetMemberCatalogs() []*MemberCatalog {
	if x != nil {
		return x.MemberCatalogs
	}
	return nil
}

type MemberCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberCatalog) Reset() {
	*x = MemberCatalog{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberCatalog) ProtoMessage() {}

func (x *MemberCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberCatalog.ProtoReflect.Descriptor instead.
func (*MemberCatalog) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *MemberCatalog) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          []byte                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	PodUid        string                 `protobuf:"bytes,2,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Fabric        string                 `protobuf:"bytes,3,opt,name=fabric,proto3" json:"fabric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Member) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *Member) GetFabric() string {
	if x != nil {
		return x.Fabric
	}
	return ""
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fabric        string                 `protobuf:"bytes,2,opt,name=fabric,proto3" json:"fabric,omitempty"`
	HttpAddress   string                 `protobuf:"bytes,3,opt,name=http_address,json=httpAddress,proto3" json:"http_address,omitempty"`
	PodUid        string                 `protobuf:"bytes,4,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peer) GetFabric() string {
	if x != nil {
		return x.Fabric
	}
	return ""
}

func (x *Peer) GetHttpAddress() string {
	if x != nil {
		return x.HttpAddress
	}
	return ""
}

func (x *Peer) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

type Volume struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CacheGeneration      uint64                 `protobuf:"varint,5,opt,name=cache_generation,json=cacheGeneration,proto3" json:"cache_generation,omitempty"`
	Peers                []string               `protobuf:"bytes,6,rep,name=peers,proto3" json:"peers,omitempty"`
	Topology             *Topology              `protobuf:"bytes,7,opt,name=topology,proto3" json:"topology,omitempty"`
	MaxCandidateAttempts *uint32                `protobuf:"varint,8,opt,name=max_candidate_attempts,json=maxCandidateAttempts,proto3,oneof" json:"max_candidate_attempts,omitempty"`
	PeerEndpoints        *VolumePeerEndpoints   `protobuf:"bytes,9,opt,name=peer_endpoints,json=peerEndpoints,proto3" json:"peer_endpoints,omitempty"`
	CacheSocket          string                 `protobuf:"bytes,10,opt,name=cache_socket,json=cacheSocket,proto3" json:"cache_socket,omitempty"`
	OriginSocket         string                 `protobuf:"bytes,12,opt,name=origin_socket,json=originSocket,proto3" json:"origin_socket,omitempty"`
	// Required index into Snapshot.member_catalogs, including for empty membership.
	MemberCatalog *uint32 `protobuf:"varint,13,opt,name=member_catalog,json=memberCatalog,proto3,oneof" json:"member_catalog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *Volume) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Volume) GetCacheGeneration() uint64 {
	if x != nil {
		return x.CacheGeneration
	}
	return 0
}

func (x *Volume) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Volume) GetTopology() *Topology {
	if x != nil {
		return x.Topology
	}
	return nil
}

func (x *Volume) GetMaxCandidateAttempts() uint32 {
	if x != nil && x.MaxCandidateAttempts != nil {
		return *x.MaxCandidateAttempts
	}
	return 0
}

func (x *Volume) GetPeerEndpoints() *VolumePeerEndpoints {
	if x != nil {
		return x.PeerEndpoints
	}
	return nil
}

func (x *Volume) GetCacheSocket() string {
	if x != nil {
		return x.CacheSocket
	}
	return ""
}

func (x *Volume) GetOriginSocket() string {
	if x != nil {
		return x.OriginSocket
	}
	return ""
}

func (x *Volume) GetMemberCatalog() uint32 {
	if x != nil && x.MemberCatalog != nil {
		return *x.MemberCatalog
	}
	return 0
}

type VolumePeerEndpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*VolumePeerEndpoint  `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumePeerEndpoints) Reset() {
	*x = VolumePeerEndpoints{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumePeerEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumePeerEndpoints) ProtoMessage() {}

func (x *VolumePeerEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumePeerEndpoints.ProtoReflect.Descriptor instead.
func (*VolumePeerEndpoints) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *VolumePeerEndpoints) GetPeers() []*VolumePeerEndpoint {
	if x != nil {
		return x.Peers
	}
	return nil
}

type VolumePeerEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	HttpAddress   string                 `protobuf:"bytes,2,opt,name=http_address,json=httpAddress,proto3" json:"http_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumePeerEndpoint) Reset() {
	*x = VolumePeerEndpoint{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumePeerEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumePeerEndpoint) ProtoMessage() {}

func (x *VolumePeerEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumePeerEndpoint.ProtoReflect.Descriptor instead.
func (*VolumePeerEndpoint) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *VolumePeerEndpoint) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *VolumePeerEndpoint) GetHttpAddress() string {
	if x != nil {
		return x.HttpAddress
	}
	return ""
}

type Topology struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Epoch            uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	SlotCount        uint32                 `protobuf:"varint,2,opt,name=slot_count,json=slotCount,proto3" json:"slot_count,omitempty"`
	LocalSlots       []uint32               `protobuf:"varint,3,rep,packed,name=local_slots,json=localSlots,proto3" json:"local_slots,omitempty"`
	Neighbors        []*SlotPeer            `protobuf:"bytes,4,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	RoutingAlgorithm *uint32                `protobuf:"varint,5,opt,name=routing_algorithm,json=routingAlgorithm,proto3,oneof" json:"routing_algorithm,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Topology) Reset() {
	*x = Topology{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topology) ProtoMessage() {}

func (x *Topology) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topology.ProtoReflect.Descriptor instead.
func (*Topology) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *Topology) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Topology) GetSlotCount() uint32 {
	if x != nil {
		return x.SlotCount
	}
	return 0
}

func (x *Topology) GetLocalSlots() []uint32 {
	if x != nil {
		return x.LocalSlots
	}
	return nil
}

func (x *Topology) GetNeighbors() []*SlotPeer {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *Topology) GetRoutingAlgorithm() uint32 {
	if x != nil && x.RoutingAlgorithm != nil {
		return *x.RoutingAlgorithm
	}
	return 0
}

type SlotPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Peer          string                 `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotPeer) Reset() {
	*x = SlotPeer{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotPeer) ProtoMessage() {}

func (x *SlotPeer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotPeer.ProtoReflect.Descriptor instead.
func (*SlotPeer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *SlotPeer) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SlotPeer) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

type Configuration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Contents:
	//
	//	*Configuration_Snapshot
	Contents      isConfiguration_Contents `protobuf_oneof:"contents"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *Configuration) GetContents() isConfiguration_Contents {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *Configuration) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Contents.(*Configuration_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

type isConfiguration_Contents interface {
	isConfiguration_Contents()
}

type Configuration_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

func (*Configuration_Snapshot) isConfiguration_Contents() {}

// Full independently applicable desired state on /v1/config. Cursor acknowledges
// receipt, not successful local preparation or application.
type DesiredState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Universe       []byte                 `protobuf:"bytes,1,opt,name=universe,proto3" json:"universe,omitempty"`
	Node           []byte                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Incarnation    []byte                 `protobuf:"bytes,3,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	SnapshotDigest []byte                 `protobuf:"bytes,4,opt,name=snapshot_digest,json=snapshotDigest,proto3" json:"snapshot_digest,omitempty"`
	Revision       uint64                 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Configuration  *Configuration         `protobuf:"bytes,6,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Profile        uint32                 `protobuf:"varint,7,opt,name=profile,proto3" json:"profile,omitempty"`
	PodUid         string                 `protobuf:"bytes,8,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	StoragePolicy  *StoragePolicy         `protobuf:"bytes,9,opt,name=storage_policy,json=storagePolicy,proto3" json:"storage_policy,omitempty"`
	Cursor         string                 `protobuf:"bytes,10,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DesiredState) Reset() {
	*x = DesiredState{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredState) ProtoMessage() {}

func (x *DesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredState.ProtoReflect.Descriptor instead.
func (*DesiredState) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *DesiredState) GetUniverse() []byte {
	if x != nil {
		return x.Universe
	}
	return nil
}

func (x *DesiredState) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *DesiredState) GetIncarnation() []byte {
	if x != nil {
		return x.Incarnation
	}
	return nil
}

func (x *DesiredState) GetSnapshotDigest() []byte {
	if x != nil {
		return x.SnapshotDigest
	}
	return nil
}

func (x *DesiredState) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DesiredState) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *DesiredState) GetProfile() uint32 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *DesiredState) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *DesiredState) GetStoragePolicy() *StoragePolicy {
	if x != nil {
		return x.StoragePolicy
	}
	return nil
}

func (x *DesiredState) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type StoragePolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      []byte                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	DesiredBytes  uint64                 `protobuf:"varint,3,opt,name=desired_bytes,json=desiredBytes,proto3" json:"desired_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoragePolicy) Reset() {
	*x = StoragePolicy{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePolicy) ProtoMessage() {}

func (x *StoragePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePolicy.ProtoReflect.Descriptor instead.
func (*StoragePolicy) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *StoragePolicy) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *StoragePolicy) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StoragePolicy) GetDesiredBytes() uint64 {
	if x != nil {
		return x.DesiredBytes
	}
	return 0
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x10racer.control.v1\"\xc4\x02\n" +
	"\bSnapshot\x12\x1a\n" +
	"\buniverse\x18\x01 \x01(\fR\buniverse\x12\x12\n" +
	"\x04node\x18\x02 \x01(\fR\x04node\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12,\n" +
	"\x05peers\x18\x04 \x03(\v2\x16.racer.control.v1.PeerR\x05peers\x122\n" +
	"\avolumes\x18\x05 \x03(\v2\x18.racer.control.v1.VolumeR\avolumes\x12\x16\n" +
	"\x06fabric\x18\x06 \x01(\tR\x06fabric\x12\x14\n" +
	"\x05epoch\x18\a \x01(\x04R\x05epoch\x12\x12\n" +
	"\x04idle\x18\b \x01(\bR\x04idle\x12H\n" +
	"\x0fmember_catalogs\x18\t \x03(\v2\x1f.racer.control.v1.MemberCatalogR\x0ememberCatalogs\"C\n" +
	"\rMemberCatalog\x122\n" +
	"\amembers\x18\x01 \x03(\v2\x18.racer.control.v1.MemberR\amembers\"M\n" +
	"\x06Member\x12\x12\n" +
	"\x04node\x18\x01 \x01(\fR\x04node\x12\x17\n" +
	"\apod_uid\x18\x02 \x01(\tR\x06podUid\x12\x16\n" +
	"\x06fabric\x18\x03 \x01(\tR\x06fabric\"j\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06fabric\x18\x02 \x01(\tR\x06fabric\x12!\n" +
	"\fhttp_address\x18\x03 \x01(\tR\vhttpAddress\x12\x17\n" +
	"\apod_uid\x18\x04 \x01(\tR\x06podUid\"\xbc\x03\n" +
	"\x06Volume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10cache_generation\x18\x05 \x01(\x04R\x0fcacheGeneration\x12\x14\n" +
	"\x05peers\x18\x06 \x03(\tR\x05peers\x126\n" +
	"\btopology\x18\a \x01(\v2\x1a.racer.control.v1.TopologyR\btopology\x129\n" +
	"\x16max_candidate_attempts\x18\b \x01(\rH\x00R\x14maxCandidateAttempts\x88\x01\x01\x12L\n" +
	"\x0epeer_endpoints\x18\t \x01(\v2%.racer.control.v1.VolumePeerEndpointsR\rpeerEndpoints\x12!\n" +
	"\fcache_socket\x18\n" +
	" \x01(\tR\vcacheSocket\x12#\n" +
	"\rorigin_socket\x18\f \x01(\tR\foriginSocket\x12*\n" +
	"\x0emember_catalog\x18\r \x01(\rH\x01R\rmemberCatalog\x88\x01\x01B\x19\n" +
	"\x17_max_candidate_attemptsB\x11\n" +
	"\x0f_member_catalog\"Q\n" +
	"\x13VolumePeerEndpoints\x12:\n" +
	"\x05peers\x18\x01 \x03(\v2$.racer.control.v1.VolumePeerEndpointR\x05peers\"K\n" +
	"\x12VolumePeerEndpoint\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12!\n" +
	"\fhttp_address\x18\x02 \x01(\tR\vhttpAddress\"\xe2\x01\n" +
	"\bTopology\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x1d\n" +
	"\n" +
	"slot_count\x18\x02 \x01(\rR\tslotCount\x12\x1f\n" +
	"\vlocal_slots\x18\x03 \x03(\rR\n" +
	"localSlots\x128\n" +
	"\tneighbors\x18\x04 \x03(\v2\x1a.racer.control.v1.SlotPeerR\tneighbors\x120\n" +
	"\x11routing_algorithm\x18\x05 \x01(\rH\x00R\x10routingAlgorithm\x88\x01\x01B\x14\n" +
	"\x12_routing_algorithm\"2\n" +
	"\bSlotPeer\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\tR\x04peer\"U\n" +
	"\rConfiguration\x128\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1a.racer.control.v1.SnapshotH\x00R\bsnapshotB\n" +
	"\n" +
	"\bcontents\"\xff\x02\n" +
	"\fDesiredState\x12\x1a\n" +
	"\buniverse\x18\x01 \x01(\fR\buniverse\x12\x12\n" +
	"\x04node\x18\x02 \x01(\fR\x04node\x12 \n" +
	"\vincarnation\x18\x03 \x01(\fR\vincarnation\x12'\n" +
	"\x0fsnapshot_digest\x18\x04 \x01(\fR\x0esnapshotDigest\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x04R\brevision\x12E\n" +
	"\rconfiguration\x18\x06 \x01(\v2\x1f.racer.control.v1.ConfigurationR\rconfiguration\x12\x18\n" +
	"\aprofile\x18\a \x01(\rR\aprofile\x12\x17\n" +
	"\apod_uid\x18\b \x01(\tR\x06podUid\x12F\n" +
	"\x0estorage_policy\x18\t \x01(\v2\x1f.racer.control.v1.StoragePolicyR\rstoragePolicy\x12\x16\n" +
	"\x06cursor\x18\n" +
	" \x01(\tR\x06cursor\"j\n" +
	"\rStoragePolicy\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\fR\bidentity\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12#\n" +
	"\rdesired_bytes\x18\x03 \x01(\x04R\fdesiredBytesB2Z0github.com/Azure/unbounded/api/racer;racerconfigb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_control_proto_goTypes = []any{
	(*Snapshot)(nil),            // 0: racer.control.v1.Snapshot
	(*MemberCatalog)(nil),       // 1: racer.control.v1.MemberCatalog
	(*Member)(nil),              // 2: racer.control.v1.Member
	(*Peer)(nil),                // 3: racer.control.v1.Peer
	(*Volume)(nil),              // 4: racer.control.v1.Volume
	(*VolumePeerEndpoints)(nil), // 5: racer.control.v1.VolumePeerEndpoints
	(*VolumePeerEndpoint)(nil),  // 6: racer.control.v1.VolumePeerEndpoint
	(*Topology)(nil),            // 7: racer.control.v1.Topology
	(*SlotPeer)(nil),            // 8: racer.control.v1.SlotPeer
	(*Configuration)(nil),       // 9: racer.control.v1.Configuration
	(*DesiredState)(nil),        // 10: racer.control.v1.DesiredState
	(*StoragePolicy)(nil),       // 11: racer.control.v1.StoragePolicy
}
var file_control_proto_depIdxs = []int32{
	3,  // 0: racer.control.v1.Snapshot.peers:type_name -> racer.control.v1.Peer
	4,  // 1: racer.control.v1.Snapshot.volumes:type_name -> racer.control.v1.Volume
	1,  // 2: racer.control.v1.Snapshot.member_catalogs:type_name -> racer.control.v1.MemberCatalog
	2,  // 3: racer.control.v1.MemberCatalog.members:type_name -> racer.control.v1.Member
	7,  // 4: racer.control.v1.Volume.topology:type_name -> racer.control.v1.Topology
	5,  // 5: racer.control.v1.Volume.peer_endpoints:type_name -> racer.control.v1.VolumePeerEndpoints
	6,  // 6: racer.control.v1.VolumePeerEndpoints.peers:type_name -> racer.control.v1.VolumePeerEndpoint
	8,  // 7: racer.control.v1.Topology.neighbors:type_name -> racer.control.v1.SlotPeer
	0,  // 8: racer.control.v1.Configuration.snapshot:type_name -> racer.control.v1.Snapshot
	9,  // 9: racer.control.v1.DesiredState.configuration:type_name -> racer.control.v1.Configuration
	11, // 10: racer.control.v1.DesiredState.storage_policy:type_name -> racer.control.v1.StoragePolicy
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[4].OneofWrappers = []any{}
	file_control_proto_msgTypes[7].OneofWrappers = []any{}
	file_control_proto_msgTypes[9].OneofWrappers = []any{
		(*Configuration_Snapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
