apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unbounded-system

resources:
  - daemonset.yaml
  - service-origin.yaml
  - service-gantry.yaml

images:
  - name: racer-loadgen
    newTag: dev
