# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0

FROM docker.io/library/ubuntu:noble@sha256:84e77dee7d1bc93fb029a45e3c6cb9d8aa4831ccfcc7103d36e876938d28895b

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        curl jq util-linux \
    && rm -rf /var/lib/apt/lists/*

COPY images/gantry-node-config/configure-overlaybd.sh /usr/local/bin/configure-overlaybd.sh
RUN chmod 0755 /usr/local/bin/configure-overlaybd.sh

ENTRYPOINT ["/usr/local/bin/configure-overlaybd.sh"]