// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by a fixture. DO NOT EDIT.

package lib

// GeneratedOrphan has no caller, but it lives in a generated file and must not
// be reported: the fix would be to change the generator, not the output.
func GeneratedOrphan() {}
