# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# TODO: switch to debootstrap-based base image once we have the container registry set up
FROM docker.io/library/ubuntu:noble@sha256:84e77dee7d1bc93fb029a45e3c6cb9d8aa4831ccfcc7103d36e876938d28895b

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::Retries=5 install -y --no-install-recommends \
    systemd \
    systemd-sysv \
    dbus \
    curl \
    ca-certificates \
    iproute2 \
    nftables \
    kmod \
    udev \
    procps \
    wireguard-tools \
    && rm -rf /var/lib/apt/lists/*

# TODO: pre-install containerd / runc / kubernetes binaries