# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM mcr.microsoft.com/azurelinux/base/core:3.0

RUN tdnf install -y \
      systemd dbus curl ca-certificates \
      iproute nftables iptables kmod systemd-udev procps-ng wireguard-tools bpftool \
    && tdnf clean all

# TODO: pre-install containerd / runc / kubernetes binaries
