// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package version

// resolveCases are the fixtures and expectations ported from
// hack/release/next-version-test.sh.
//
// Generated once by having bash itself parse that suite's expect
// invocations, so the arguments were never transcribed by hand. Reviewed
// afterwards, and maintained here from now on.
var resolveCases = []resolveCase{
	{kind: wantTag, name: "no tags, release", mode: "release", want: "v0.0.1", tags: []string{}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "no tags, prerelease", mode: "prerelease", want: "v0.0.1-rc.1", tags: []string{}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "final only, prerelease patch", mode: "prerelease", want: "v0.2.5-rc.1", tags: []string{"v0.2.4"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "final only, prerelease minor", mode: "prerelease", want: "v0.3.0-rc.1", tags: []string{"v0.2.4"}, env: []string{"BUMP=minor"}},
	{kind: wantTag, name: "final only, prerelease major", mode: "prerelease", want: "v1.0.0-rc.1", tags: []string{"v0.2.4"}, env: []string{"BUMP=major"}},
	{kind: wantTag, name: "final only, release patch", mode: "release", want: "v0.2.5", tags: []string{"v0.2.4"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "live train auto-increments", mode: "prerelease", want: "v0.2.5-rc.2", tags: []string{"v0.2.4", "v0.2.5-rc.1"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "live train ignores conflicting bump", mode: "prerelease", want: "v0.2.5-rc.2", tags: []string{"v0.2.4", "v0.2.5-rc.1"}, env: []string{"BUMP=minor"}},
	{kind: wantTag, name: "rc numbering is numeric, not lexical", mode: "prerelease", want: "v0.2.5-rc.19", tags: []string{"v0.2.4", "v0.2.5-rc.7", "v0.2.5-rc.8", "v0.2.5-rc.9", "v0.2.5-rc.10", "v0.2.5-rc.18"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "stale train ignored when starting", mode: "prerelease", want: "v0.2.5-rc.1", tags: []string{"v0.1.24-rc.17", "v0.1.24-rc.18", "v0.2.0", "v0.2.4"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "stale train not promotable", mode: "promote", want: "ERROR", wantErr: "no live prerelease train to promote", tags: []string{"v0.1.24-rc.17", "v0.1.24-rc.18", "v0.2.0", "v0.2.4"}, env: []string{}},
	{kind: wantTag, name: "stale train ignored, release", mode: "release", want: "v0.2.5", tags: []string{"v0.1.24-rc.18", "v0.2.4"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "second train refused by default", mode: "prerelease", want: "ERROR", wantErr: "set allow_concurrent_trains", tags: []string{"v0.2.4", "v0.2.5-rc.1", "v0.3.0-rc.1"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "second train allowed with opt-in", mode: "prerelease", want: "v0.3.0-rc.1", tags: []string{"v0.2.4", "v0.2.5-rc.1"}, env: []string{"BUMP=minor", "ALLOW_CONCURRENT_TRAINS=true"}},
	{kind: wantTag, name: "opt-in continues matching train", mode: "prerelease", want: "v0.2.5-rc.2", tags: []string{"v0.2.4", "v0.2.5-rc.1"}, env: []string{"BUMP=patch", "ALLOW_CONCURRENT_TRAINS=true"}},
	{kind: wantTag, name: "promote the only live train", mode: "promote", want: "v0.2.5", tags: []string{"v0.2.4", "v0.2.5-rc.1", "v0.2.5-rc.2"}, env: []string{}},
	{kind: wantTag, name: "promote refuses to guess", mode: "promote", want: "ERROR", wantErr: "pass version to say which one", tags: []string{"v0.2.4", "v0.2.5-rc.1", "v0.3.0-rc.1"}, env: []string{}},
	{kind: wantTag, name: "promote with explicit version", mode: "promote", want: "v0.3.0", tags: []string{"v0.2.4", "v0.2.5-rc.1", "v0.3.0-rc.1"}, env: []string{"VERSION=v0.3.0"}},
	{kind: wantTag, name: "promote accepts bare version", mode: "promote", want: "v0.3.0", tags: []string{"v0.2.4", "v0.3.0-rc.1"}, env: []string{"VERSION=0.3.0"}},
	{kind: wantTag, name: "promote with no train at all", mode: "promote", want: "ERROR", wantErr: "no live prerelease train to promote", tags: []string{"v0.2.4"}, env: []string{}},
	{kind: wantTag, name: "promote rejects a suffixed version", mode: "promote", want: "ERROR", wantErr: "must be a final vX.Y.Z", tags: []string{"v0.2.4", "v0.2.5-rc.1"}, env: []string{"VERSION=v0.2.5-rc.1"}},
	{kind: wantTag, name: "promote rejects a version with no train", mode: "promote", want: "ERROR", wantErr: "no prerelease train found for v0.9.9", tags: []string{"v0.2.4"}, env: []string{"VERSION=v0.9.9"}},
	{kind: wantTag, name: "promote rejects a stale train by name", mode: "promote", want: "ERROR", wantErr: "is older than the latest final", tags: []string{"v0.1.24-rc.17", "v0.1.24-rc.18", "v0.2.4"}, env: []string{"VERSION=v0.1.24"}},
	{kind: wantBase, name: "promote tags the last candidate", mode: "promote", want: "v0.2.5-rc.2", tags: []string{"v0.2.4", "v0.2.5-rc.1@new", "v0.2.5-rc.2@new"}, env: []string{}},
	{kind: wantBase, name: "promote ignores commits merged since", mode: "promote", want: "v0.2.5-rc.1", tags: []string{"v0.2.4", "v0.2.5-rc.1@new", "v9.9.9-marker@new"}, env: []string{"VERSION=v0.2.5"}},
	{kind: wantBase, name: "promote picks rc.18 over rc.9", mode: "promote", want: "v0.2.5-rc.18", tags: []string{"v0.2.4", "v0.2.5-rc.9@new", "v0.2.5-rc.18@new"}, env: []string{}},
	{kind: wantBase, name: "prerelease tags HEAD", mode: "prerelease", want: "HEAD", tags: []string{"v0.2.4", "v0.2.5-rc.1@new"}, env: []string{"BUMP=patch"}},
	{kind: wantBase, name: "release tags HEAD", mode: "release", want: "HEAD", tags: []string{"v0.2.4"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "promote refuses a train with no rc", mode: "promote", want: "ERROR", wantErr: "no live prerelease train to promote", tags: []string{"v0.2.4", "v0.2.5-beta.1"}, env: []string{}},
	{kind: wantTag, name: "explicit rc accepted", mode: "prerelease", want: "v0.2.5-rc.4", tags: []string{"v0.2.4", "v0.2.5-rc.1"}, env: []string{"BUMP=patch", "PRE=rc.4"}},
	{kind: wantTag, name: "beta rejected", mode: "prerelease", want: "ERROR", wantErr: "rc is the only prerelease suffix", tags: []string{"v0.2.4"}, env: []string{"BUMP=patch", "PRE=beta.1"}},
	{kind: wantTag, name: "alpha rejected", mode: "prerelease", want: "ERROR", wantErr: "rc is the only prerelease suffix", tags: []string{"v0.2.4"}, env: []string{"BUMP=patch", "PRE=alpha.0"}},
	{kind: wantTag, name: "rc must move forward", mode: "prerelease", want: "ERROR", wantErr: "is not ahead of", tags: []string{"v0.2.4", "v0.2.5-rc.5"}, env: []string{"BUMP=patch", "PRE=rc.2"}},
	{kind: wantTag, name: "rc equal to current rejected", mode: "prerelease", want: "ERROR", wantErr: "is not ahead of", tags: []string{"v0.2.4", "v0.2.5-rc.5"}, env: []string{"BUMP=patch", "PRE=rc.5"}},
	{kind: wantTag, name: "leading zero rejected", mode: "prerelease", want: "ERROR", wantErr: "no leading zeros", tags: []string{"v0.2.4", "v0.2.5-rc.5"}, env: []string{"BUMP=patch", "PRE=rc.08"}},
	{kind: wantTag, name: "leading zero rejected even when ahead", mode: "prerelease", want: "ERROR", wantErr: "no leading zeros", tags: []string{"v0.2.4", "v0.2.5-rc.1"}, env: []string{"BUMP=patch", "PRE=rc.09"}},
	{kind: wantTag, name: "existing leading-zero tag does not poison max_rc", mode: "prerelease", want: "v0.2.5-rc.10", tags: []string{"v0.2.4", "v0.2.5-rc.08", "v0.2.5-rc.9"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "two-part tag ignored", mode: "release", want: "v0.2.5", tags: []string{"v0.2.4", "v1.2"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "date-shaped tag ignored", mode: "release", want: "v0.2.5", tags: []string{"v0.2.4", "v20260710"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "four-part tag ignored", mode: "release", want: "v0.2.5", tags: []string{"v0.2.4", "v1.2.3.4"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "malformed prerelease tag ignored", mode: "prerelease", want: "v0.2.5-rc.1", tags: []string{"v0.2.4", "v1.2-rc.1"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "bare prerelease suffix ignored", mode: "prerelease", want: "v0.2.5-rc.1", tags: []string{"v0.2.4", "v9.0.0-"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "unknown prerelease suffix ignored", mode: "prerelease", want: "v0.2.5-rc.1", tags: []string{"v0.2.4", "v9.0.0-junk"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "legacy alpha suffix ignored", mode: "prerelease", want: "v0.2.5-rc.1", tags: []string{"v0.2.4", "v9.0.0-alpha.1"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "non-numeric rc ignored", mode: "prerelease", want: "v0.2.5-rc.1", tags: []string{"v0.2.4", "v9.0.0-rc.x"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "zero rc ignored", mode: "prerelease", want: "v0.2.5-rc.1", tags: []string{"v0.2.4", "v9.0.0-rc.0"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "leading-zero rc creates no train", mode: "prerelease", want: "v0.2.5-rc.1", tags: []string{"v0.2.4", "v9.0.0-rc.01"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "canonical rc creates a train", mode: "prerelease", want: "v9.0.0-rc.2", tags: []string{"v0.2.4", "v9.0.0-rc.1"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "promote rejects only malformed candidates", mode: "promote", want: "ERROR", wantErr: "no prerelease train found for v9.0.0", tags: []string{"v0.2.4", "v9.0.0-junk", "v9.0.0-rc.x"}, env: []string{"VERSION=v9.0.0"}},
	{kind: wantTag, name: "off-branch final ignored", mode: "release", want: "v0.2.5", tags: []string{"v0.2.4", "v9.0.0@off"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "off-branch prerelease starts no train", mode: "prerelease", want: "v0.2.5-rc.1", tags: []string{"v0.2.4", "v9.0.0-rc.1@off"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "off-branch train not promotable", mode: "promote", want: "ERROR", wantErr: "no live prerelease train to promote", tags: []string{"v0.2.4", "v9.0.0-rc.1@off"}, env: []string{}},
	{kind: wantTag, name: "off-branch rc name still refused", mode: "prerelease", want: "ERROR", wantErr: "already exists", tags: []string{"v0.2.4", "v0.2.5-rc.1@off"}, env: []string{"BUMP=patch", "PRE=rc.1"}},
	{kind: wantTag, name: "off-branch final blocks a new train", mode: "prerelease", want: "ERROR", wantErr: "could never be promoted", tags: []string{"v0.2.4", "v0.2.5@off"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "off-branch final blocks a second train", mode: "prerelease", want: "ERROR", wantErr: "could never be promoted", tags: []string{"v0.2.4", "v0.2.5-rc.1", "v0.3.0@off"}, env: []string{"BUMP=minor", "ALLOW_CONCURRENT_TRAINS=true"}},
	{kind: wantTag, name: "twenty-digit component ignored", mode: "release", want: "v0.2.5", tags: []string{"v0.2.4", "v99999999999999999999.0.0"}, env: []string{"BUMP=patch"}},
	{kind: wantTag, name: "ten-digit rc rejected", mode: "prerelease", want: "ERROR", wantErr: "at most nine digits", tags: []string{"v0.2.4"}, env: []string{"BUMP=patch", "PRE=rc.9999999999"}},
	{kind: wantTag, name: "bump that overflows refused", mode: "release", want: "ERROR", wantErr: "overflows a version component", tags: []string{"v999999999.0.0"}, env: []string{"BUMP=major"}},
	{kind: wantTag, name: "leading zeros rejected in a version input", mode: "promote", want: "ERROR", wantErr: "must be a final vX.Y.Z", tags: []string{"v0.2.4", "v0.2.5-rc.1"}, env: []string{"VERSION=v01.2.3"}},
	{kind: wantTag, name: "unbounded version input rejected", mode: "promote", want: "ERROR", wantErr: "must be a final vX.Y.Z", tags: []string{"v0.2.4", "v0.2.5-rc.1"}, env: []string{"VERSION=v99999999999.0.0"}},
	{kind: wantTag, name: "pre rejected with release", mode: "release", want: "ERROR", wantErr: "pre is only valid with mode=prerelease", tags: []string{"v0.2.4"}, env: []string{"BUMP=patch", "PRE=rc.1"}},
	{kind: wantTag, name: "pre rejected with promote", mode: "promote", want: "ERROR", wantErr: "pre is only valid with mode=prerelease", tags: []string{"v0.2.4", "v0.2.5-rc.1"}, env: []string{"PRE=rc.1"}},
	{kind: wantTag, name: "existing tag refused", mode: "promote", want: "ERROR", wantErr: "is older than the latest final", tags: []string{"v0.2.4", "v0.2.4-rc.1"}, env: []string{"VERSION=v0.2.4"}},
	{kind: wantTag, name: "unknown mode", mode: "nonsense", want: "ERROR", wantErr: "unexpected mode", tags: []string{"v0.2.4"}, env: []string{}},
	{kind: wantTag, name: "unknown bump", mode: "release", want: "ERROR", wantErr: "unexpected bump level", tags: []string{"v0.2.4"}, env: []string{"BUMP=sideways"}},
	{kind: wantTag, name: "patch on a release branch while main has moved on", mode: "release", want: "v0.3.1", tags: []string{"v0.3.0", "v0.4.0@off"}, env: []string{"BUMP=patch", "SERIES=0.3"}},
	{kind: wantTag, name: "second patch on the same release branch", mode: "release", want: "v0.3.2", tags: []string{"v0.3.0", "v0.3.1", "v0.5.0@off"}, env: []string{"BUMP=patch", "SERIES=0.3"}},
	{kind: wantTag, name: "release branch unaffected by newer minors", mode: "release", want: "v0.3.1", tags: []string{"v0.3.0", "v0.4.0@off", "v0.5.0@off", "v0.6.0@off"}, env: []string{"BUMP=patch", "SERIES=0.3"}},
	{kind: wantTag, name: "candidate on a release branch", mode: "prerelease", want: "v0.3.1-rc.1", tags: []string{"v0.3.0", "v0.4.0@off"}, env: []string{"BUMP=patch", "SERIES=0.3"}},
	{kind: wantTag, name: "promote on a release branch", mode: "promote", want: "v0.3.1", tags: []string{"v0.3.0", "v0.3.1-rc.1", "v0.4.0@off"}, env: []string{"SERIES=0.3"}},
	{kind: wantTag, name: "minor refused on a release branch", mode: "release", want: "ERROR", wantErr: "outside series 0.3", tags: []string{"v0.3.0"}, env: []string{"BUMP=minor", "SERIES=0.3"}},
	{kind: wantTag, name: "major refused on a release branch", mode: "release", want: "ERROR", wantErr: "outside series 0.3", tags: []string{"v0.3.0"}, env: []string{"BUMP=major", "SERIES=0.3"}},
	{kind: wantTag, name: "malformed series refused", mode: "release", want: "ERROR", wantErr: "series must be X.Y", tags: []string{"v0.3.0"}, env: []string{"BUMP=patch", "SERIES=03.1"}},
	{kind: wantTag, name: "series without a minor refused", mode: "release", want: "ERROR", wantErr: "series must be X.Y", tags: []string{"v0.3.0"}, env: []string{"BUMP=patch", "SERIES=3"}},
	{kind: wantTag, name: "tag outside the series refused", mode: "release", want: "ERROR", wantErr: "outside series 0.3", tags: []string{"v0.4.0"}, env: []string{"BUMP=patch", "SERIES=0.3"}},
	{kind: wantTag, name: "release branch with no tags in its series refused", mode: "release", want: "ERROR", wantErr: "outside series 0.3", tags: []string{"v0.9.0@off"}, env: []string{"BUMP=patch", "SERIES=0.3"}},
}
