// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/net/healthcheck/proto/healthcheck.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_REQUEST PacketType = 0
	PacketType_REPLY   PacketType = 1
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "REQUEST",
		1: "REPLY",
	}
	PacketType_value = map[string]int32{
		"REQUEST": 0,
		"REPLY":   1,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_net_healthcheck_proto_healthcheck_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_internal_net_healthcheck_proto_healthcheck_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_internal_net_healthcheck_proto_healthcheck_proto_rawDescGZIP(), []int{0}
}

type HealthCheckPacket struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SourceHostname      string                 `protobuf:"bytes,1,opt,name=source_hostname,json=sourceHostname,proto3" json:"source_hostname,omitempty"`
	DestinationHostname string                 `protobuf:"bytes,2,opt,name=destination_hostname,json=destinationHostname,proto3" json:"destination_hostname,omitempty"`
	SequenceNumber      uint64                 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	TimestampNs         int64                  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Type                PacketType             `protobuf:"varint,5,opt,name=type,proto3,enum=healthcheck.PacketType" json:"type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthCheckPacket) Reset() {
	*x = HealthCheckPacket{}
	mi := &file_internal_net_healthcheck_proto_healthcheck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckPacket) ProtoMessage() {}

func (x *HealthCheckPacket) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_healthcheck_proto_healthcheck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckPacket.ProtoReflect.Descriptor instead.
func (*HealthCheckPacket) Descriptor() ([]byte, []int) {
	return file_internal_net_healthcheck_proto_healthcheck_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckPacket) GetSourceHostname() string {
	if x != nil {
		return x.SourceHostname
	}
	return ""
}

func (x *HealthCheckPacket) GetDestinationHostname() string {
	if x != nil {
		return x.DestinationHostname
	}
	return ""
}

func (x *HealthCheckPacket) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *HealthCheckPacket) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *HealthCheckPacket) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_REQUEST
}

var File_internal_net_healthcheck_proto_healthcheck_proto protoreflect.FileDescriptor

const file_internal_net_healthcheck_proto_healthcheck_proto_rawDesc = "" +
	"\n" +
	"0internal/net/healthcheck/proto/healthcheck.proto\x12\vhealthcheck\"\xe8\x01\n" +
	"\x11HealthCheckPacket\x12'\n" +
	"\x0fsource_hostname\x18\x01 \x01(\tR\x0esourceHostname\x121\n" +
	"\x14destination_hostname\x18\x02 \x01(\tR\x13destinationHostname\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x04R\x0esequenceNumber\x12!\n" +
	"\ftimestamp_ns\x18\x04 \x01(\x03R\vtimestampNs\x12+\n" +
	"\x04type\x18\x05 \x01(\x0e2\x17.healthcheck.PacketTypeR\x04type*$\n" +
	"\n" +
	"PacketType\x12\v\n" +
	"\aREQUEST\x10\x00\x12\t\n" +
	"\x05REPLY\x10\x01B@Z>github.com/Azure/unbounded-kube/internal/net/healthcheck/protob\x06proto3"

var (
	file_internal_net_healthcheck_proto_healthcheck_proto_rawDescOnce sync.Once
	file_internal_net_healthcheck_proto_healthcheck_proto_rawDescData []byte
)

func file_internal_net_healthcheck_proto_healthcheck_proto_rawDescGZIP() []byte {
	file_internal_net_healthcheck_proto_healthcheck_proto_rawDescOnce.Do(func() {
		file_internal_net_healthcheck_proto_healthcheck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_net_healthcheck_proto_healthcheck_proto_rawDesc), len(file_internal_net_healthcheck_proto_healthcheck_proto_rawDesc)))
	})
	return file_internal_net_healthcheck_proto_healthcheck_proto_rawDescData
}

var file_internal_net_healthcheck_proto_healthcheck_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_net_healthcheck_proto_healthcheck_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_net_healthcheck_proto_healthcheck_proto_goTypes = []any{
	(PacketType)(0),           // 0: healthcheck.PacketType
	(*HealthCheckPacket)(nil), // 1: healthcheck.HealthCheckPacket
}
var file_internal_net_healthcheck_proto_healthcheck_proto_depIdxs = []int32{
	0, // 0: healthcheck.HealthCheckPacket.type:type_name -> healthcheck.PacketType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_net_healthcheck_proto_healthcheck_proto_init() }
func file_internal_net_healthcheck_proto_healthcheck_proto_init() {
	if File_internal_net_healthcheck_proto_healthcheck_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_net_healthcheck_proto_healthcheck_proto_rawDesc), len(file_internal_net_healthcheck_proto_healthcheck_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_net_healthcheck_proto_healthcheck_proto_goTypes,
		DependencyIndexes: file_internal_net_healthcheck_proto_healthcheck_proto_depIdxs,
		EnumInfos:         file_internal_net_healthcheck_proto_healthcheck_proto_enumTypes,
		MessageInfos:      file_internal_net_healthcheck_proto_healthcheck_proto_msgTypes,
	}.Build()
	File_internal_net_healthcheck_proto_healthcheck_proto = out.File
	file_internal_net_healthcheck_proto_healthcheck_proto_goTypes = nil
	file_internal_net_healthcheck_proto_healthcheck_proto_depIdxs = nil
}
