// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Package ebpf provides eBPF-based tunnel dataplane management.
//
// TunnelMap loads and manages a single TC classifier program
// (unbounded_encap) generated by bpf2go from bpf/unbounded_encap.c. The
// program is attached on the egress hook of the underlay-facing interface
// (unbounded0) and routes overlay packets to the appropriate tunnel
// interface via a single LPM trie (unb_endpts) keyed on a 16-byte address.
// IPv4 destinations are stored in IPv4-mapped IPv6 form
// (::ffff:<v4>) so the trie's longest-prefix-match naturally segregates
// v4 from v6 entries.
package ebpf

import (
	"errors"
	"fmt"
	"net"
	"os"
	"sync"

	"github.com/cilium/ebpf"
	"github.com/vishvananda/netlink"
	"golang.org/x/sys/unix"
	"k8s.io/klog/v2"
)

// TunnelNexthop describes a single nexthop within a tunnel endpoint.
type TunnelNexthop struct {
	RemoteIP net.IP // the peer's underlay IP (4 or 16 bytes)
	VNI      uint32
	IfIndex  uint32 // tunnel interface index to redirect to
	Healthy  bool   // false = withdrawn from selection
	Protocol uint32 // TunnelProto* constant
	PeerName string // peer hostname for healthcheck correlation (not stored in BPF)
}

// TunnelEndpoint holds all nexthops for a CIDR prefix.
type TunnelEndpoint struct {
	Nexthops []TunnelNexthop
}

// MaxNexthops is the maximum number of nexthops per tunnel endpoint,
// matching MAX_NEXTHOPS in the BPF program.
const MaxNexthops = 4

// Tunnel protocol constants matching BPF PROTO_* constants.
const (
	TunnelProtoGENEVE    uint32 = 1
	TunnelProtoVXLAN     uint32 = 2
	TunnelProtoIPIP      uint32 = 3
	TunnelProtoWireGuard uint32 = 4
	TunnelProtoNone      uint32 = 5
)

// Map and program names exported so cmd/unroute and other diagnostic
// tools agree on what to look for in the kernel.
const (
	MapName      = "unb_endpts"
	TraceMapName = "unb_trace"
	ProgramName  = "unbounded_encap"
)

// Type aliases for the bpf2go-generated kernel structs. The lower-case
// aliases are used internally; the upper-case ones are exported so
// diagnostic tools like cmd/unroute can iterate the map with the exact
// kernel wire format. The Go-facing TunnelEndpoint / TunnelNexthop types
// stay unchanged as the user-facing API.
type (
	lpmKey          = unboundedEncapLpmKey
	tunnelEndpointC = unboundedEncapTunnelEndpoint

	// LpmKey is the on-the-wire LPM trie key. Prefixlen is the number
	// of significant bits in Addr; Addr is always 16 bytes (v4 entries
	// use the IPv4-mapped IPv6 form, ::ffff:<v4>).
	LpmKey = unboundedEncapLpmKey

	// RawTunnelEndpoint is the on-the-wire LPM trie value. It contains
	// a fixed-size array of nexthops with Count set to the number of
	// valid entries at the front of the array. cmd/unroute uses this
	// to iterate the map without re-translating to the higher-level
	// TunnelEndpoint type.
	RawTunnelEndpoint = unboundedEncapTunnelEndpoint

	// RawTraceEvent is one record emitted to the unb_trace ringbuf per
	// packet processed by unbounded_encap when a consumer is reading.
	// cmd/unroute --trace decodes the stream into human-readable form.
	RawTraceEvent = unboundedEncapUnbTraceEvent
)

// filterHandle, filterPriority match the values used historically for the
// single egress filter. They are unique inside the clsact ingress/egress
// pair; we never attach more than one program at this slot.
const (
	filterHandle   uint32 = 1
	filterPriority uint16 = 1
)

// TunnelMap manages the unbounded_encap eBPF program and its LPM trie.
type TunnelMap struct {
	mu sync.Mutex

	prog        *ebpf.Program
	endpoints   *ebpf.Map
	trace       *ebpf.Map
	maxEntries  uint32
	attachedIfs map[int]string // ifindex -> name for TC egress filters

	// lastReconciled is a snapshot of the last Reconcile() desired state,
	// used by SetPeerHealth to find and update entries for a given peer.
	lastReconciled map[string]TunnelEndpoint
}

// TunnelMapOptions configures TunnelMap creation.
type TunnelMapOptions struct {
	// MaxEntries is the capacity of the LPM trie map. Default: 16384.
	MaxEntries uint32
}

// NewTunnelMap loads the unbounded_encap eBPF program and creates its LPM
// trie. The map and program are kept alive for the lifetime of the
// TunnelMap; call Close to release them.
func NewTunnelMap(opts TunnelMapOptions) (*TunnelMap, error) {
	if opts.MaxEntries == 0 {
		opts.MaxEntries = 16384
	}

	spec, err := loadUnboundedEncap()
	if err != nil {
		return nil, fmt.Errorf("load unbounded_encap spec: %w", err)
	}

	if m := spec.Maps[MapName]; m != nil {
		m.MaxEntries = opts.MaxEntries
	}

	coll, err := ebpf.NewCollection(spec)
	if err != nil {
		return nil, fmt.Errorf("create unbounded_encap collection: %w", err)
	}

	prog := coll.Programs[ProgramName]
	if prog == nil {
		coll.Close()
		return nil, fmt.Errorf("program %s not found", ProgramName)
	}

	endpoints := coll.Maps[MapName]
	if endpoints == nil {
		coll.Close()
		return nil, fmt.Errorf("map %s not found", MapName)
	}

	trace := coll.Maps[TraceMapName]
	if trace == nil {
		coll.Close()
		return nil, fmt.Errorf("map %s not found", TraceMapName)
	}

	// Detach the program and maps from the collection wrapper so closing
	// the wrapper does not invalidate them; TunnelMap owns lifetime now.
	delete(coll.Programs, ProgramName)
	delete(coll.Maps, MapName)
	delete(coll.Maps, TraceMapName)
	coll.Close()

	klog.Infof("eBPF unbounded_encap program loaded (map max_entries %d)", opts.MaxEntries)

	return &TunnelMap{
		prog:        prog,
		endpoints:   endpoints,
		trace:       trace,
		maxEntries:  opts.MaxEntries,
		attachedIfs: make(map[int]string),
	}, nil
}

// AttachToInterface installs the unbounded_encap TC egress filter on the
// named interface. With NOARP on the dummy interface, no ARP responder is
// needed. Idempotent.
func (tm *TunnelMap) AttachToInterface(ifName string) error {
	tm.mu.Lock()
	defer tm.mu.Unlock()

	iface, err := netlink.LinkByName(ifName)
	if err != nil {
		return fmt.Errorf("find interface %q: %w", ifName, err)
	}

	ifIdx := iface.Attrs().Index
	if _, already := tm.attachedIfs[ifIdx]; already {
		return nil
	}

	if err := ensureClsactQdisc(ifIdx, ifName); err != nil {
		return err
	}

	if err := attachEgressFilter(ifIdx, ifName, tm.prog); err != nil {
		return err
	}

	tm.attachedIfs[ifIdx] = ifName
	klog.Infof("eBPF TC on %s: unbounded_encap (egress), ifindex %d", ifName, ifIdx)

	return nil
}

// Attached reports whether the TC filter has been attached to at least one
// interface.
func (tm *TunnelMap) Attached() bool {
	tm.mu.Lock()
	defer tm.mu.Unlock()

	return len(tm.attachedIfs) > 0
}

// Reconcile sets the LPM trie to exactly match the desired state. Stale
// entries (present in the kernel but not in desired) are removed; new and
// changed entries are written.
func (tm *TunnelMap) Reconcile(desired map[string]TunnelEndpoint) error {
	tm.mu.Lock()
	defer tm.mu.Unlock()

	desiredByKey := make(map[lpmKey]TunnelEndpoint, len(desired))
	for cidrStr, ep := range desired {
		_, cidr, err := net.ParseCIDR(cidrStr)
		if err != nil {
			continue
		}

		key, err := cidrToKey(cidr)
		if err != nil {
			continue
		}

		desiredByKey[key] = ep
	}

	var (
		cursor lpmKey
		val    tunnelEndpointC
		stale  []lpmKey
	)

	iter := tm.endpoints.Iterate()
	for iter.Next(&cursor, &val) {
		if _, ok := desiredByKey[cursor]; !ok {
			stale = append(stale, cursor)
		}
	}

	if err := iter.Err(); err != nil {
		klog.Warningf("eBPF reconcile iterate: %v", err)
	}

	for _, key := range stale {
		if err := tm.endpoints.Delete(key); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
			klog.Warningf("eBPF reconcile: delete stale: %v", err)
		}
	}

	for key, ep := range desiredByKey {
		if err := tm.endpoints.Update(key, endpointToC(ep), ebpf.UpdateAny); err != nil {
			klog.Warningf("eBPF reconcile: update failed: %v", err)
		}
	}

	klog.V(2).Infof("eBPF tunnel map reconciled: %d entries (%d stale removed)",
		len(desiredByKey), len(stale))

	tm.lastReconciled = desired

	return nil
}

// SetPeerHealth toggles the Healthy field on all BPF map nexthops belonging
// to the named peer. When healthy is false, the BPF program skips the
// nexthop and falls through to kernel routing (effectively withdrawing the
// peer). Returns the number of map entries updated.
func (tm *TunnelMap) SetPeerHealth(peerName string, healthy bool) int {
	tm.mu.Lock()
	defer tm.mu.Unlock()

	updated := 0

	for cidrStr, ep := range tm.lastReconciled {
		modified := false

		for i := range ep.Nexthops {
			if ep.Nexthops[i].PeerName != peerName {
				continue
			}

			ep.Nexthops[i].Healthy = healthy
			modified = true
		}

		if !modified {
			continue
		}

		tm.lastReconciled[cidrStr] = ep

		_, cidr, err := net.ParseCIDR(cidrStr)
		if err != nil {
			continue
		}

		key, err := cidrToKey(cidr)
		if err != nil {
			continue
		}

		if err := tm.endpoints.Update(key, endpointToC(ep), ebpf.UpdateAny); err != nil {
			klog.Warningf("eBPF SetPeerHealth %s: %v", cidrStr, err)
			continue
		}

		updated++
	}

	return updated
}

// Close detaches the TC filter from every registered interface and
// releases the eBPF program and map.
//
// The node agent holds its TunnelMap for the life of the process and so has
// no reason to call this; only the tests do. It is kept deliberately.
// detachEgressFilter below is the only code in the tree that removes the TC
// filter, and deleting the pair would leave the attach half of the lifecycle
// with no counterpart.
func (tm *TunnelMap) Close() error {
	tm.mu.Lock()
	defer tm.mu.Unlock()

	for ifIdx := range tm.attachedIfs {
		detachEgressFilter(ifIdx)
	}

	if tm.prog != nil {
		_ = tm.prog.Close() //nolint:errcheck
		tm.prog = nil
	}

	if tm.endpoints != nil {
		_ = tm.endpoints.Close() //nolint:errcheck
		tm.endpoints = nil
	}

	if tm.trace != nil {
		_ = tm.trace.Close() //nolint:errcheck
		tm.trace = nil
	}

	return nil
}

// --- helpers ---

func ensureClsactQdisc(ifIdx int, ifName string) error {
	qdisc := &netlink.GenericQdisc{
		QdiscAttrs: netlink.QdiscAttrs{
			LinkIndex: ifIdx,
			Handle:    netlink.MakeHandle(0xffff, 0),
			Parent:    netlink.HANDLE_CLSACT,
		},
		QdiscType: "clsact",
	}
	if err := netlink.QdiscAdd(qdisc); err != nil {
		if !errors.Is(err, os.ErrExist) && !isErrExist(err) {
			return fmt.Errorf("add clsact qdisc to %s: %w", ifName, err)
		}
	}

	return nil
}

func attachEgressFilter(ifIdx int, ifName string, prog *ebpf.Program) error {
	filter := &netlink.BpfFilter{
		FilterAttrs: netlink.FilterAttrs{
			LinkIndex: ifIdx,
			Handle:    filterHandle,
			Parent:    netlink.HANDLE_MIN_EGRESS,
			Priority:  filterPriority,
			Protocol:  unix.ETH_P_ALL,
		},
		Fd:           prog.FD(),
		Name:         ProgramName,
		DirectAction: true,
	}

	_ = netlink.FilterDel(filter) //nolint:errcheck
	if err := netlink.FilterAdd(filter); err != nil {
		return fmt.Errorf("add %s to %s egress: %w", ProgramName, ifName, err)
	}

	return nil
}

func detachEgressFilter(ifIdx int) {
	filter := &netlink.BpfFilter{
		FilterAttrs: netlink.FilterAttrs{
			LinkIndex: ifIdx,
			Handle:    filterHandle,
			Parent:    netlink.HANDLE_MIN_EGRESS,
			Priority:  filterPriority,
			Protocol:  unix.ETH_P_ALL,
		},
	}
	_ = netlink.FilterDel(filter) //nolint:errcheck
}

// cidrToKey builds an LPM trie key from a destination CIDR. The address
// is stored in IPv4-mapped IPv6 form (::ffff:<v4>) for v4 CIDRs and
// natively for v6 CIDRs. Prefix length is offset by 96 for v4-mapped
// entries so the trie matches the v4 portion at the right depth.
func cidrToKey(cidr *net.IPNet) (lpmKey, error) {
	if cidr == nil || cidr.IP == nil {
		return lpmKey{}, errors.New("nil CIDR")
	}

	mappedIP := cidr.IP.To16()
	if mappedIP == nil {
		return lpmKey{}, fmt.Errorf("invalid CIDR address: %s", cidr)
	}

	ones, _ := cidr.Mask.Size()
	prefixlen := uint32(ones)

	if cidr.IP.To4() != nil {
		prefixlen += 96
	}

	var key lpmKey

	key.Prefixlen = prefixlen
	copy(key.Addr[:], mappedIP)

	return key, nil
}

// endpointToC converts a TunnelEndpoint to the bpf2go-generated value
// type. The remote endpoint is stored in IPv4-mapped IPv6 form for v4
// underlays (via net.IP.To16, which already returns ::ffff:<v4> for
// 4-byte addresses) and natively for v6 underlays.
func endpointToC(ep TunnelEndpoint) tunnelEndpointC {
	var c tunnelEndpointC

	for i, nh := range ep.Nexthops {
		if i >= MaxNexthops {
			break
		}

		c.Nexthops[i].Vni = nh.VNI
		c.Nexthops[i].Ifindex = nh.IfIndex
		c.Nexthops[i].Protocol = nh.Protocol

		if nh.Healthy {
			c.Nexthops[i].Healthy = 1
		} else {
			c.Nexthops[i].Healthy = 0
		}

		if ip16 := nh.RemoteIP.To16(); ip16 != nil {
			copy(c.Nexthops[i].RemoteEndpoint[:], ip16)
		}

		c.Count++
	}

	return c
}

// IsV4Mapped reports whether a 16-byte address is in the IPv4-mapped
// IPv6 prefix ::ffff:0:0/96. Exported so cmd/unroute can classify entries.
func IsV4Mapped(addr [16]byte) bool {
	for i := 0; i < 10; i++ {
		if addr[i] != 0 {
			return false
		}
	}

	return addr[10] == 0xff && addr[11] == 0xff
}

// TunnelMACFromIP derives a locally-administered MAC address from an IP.
// IPv4: 02:<ip[0]>:<ip[1]>:<ip[2]>:<ip[3]>:FF.
// IPv6: 02:<ip[12]>:<ip[13]>:<ip[14]>:<ip[15]>:FF (last 4 bytes).
func TunnelMACFromIP(ip net.IP) net.HardwareAddr {
	if ip4 := ip.To4(); ip4 != nil {
		return net.HardwareAddr{0x02, ip4[0], ip4[1], ip4[2], ip4[3], 0xFF}
	}

	if ip16 := ip.To16(); ip16 != nil {
		return net.HardwareAddr{0x02, ip16[12], ip16[13], ip16[14], ip16[15], 0xFF}
	}

	return net.HardwareAddr{0x02, 0x00, 0x00, 0x00, 0x00, 0xFF}
}

// isErrExist checks for EEXIST from netlink.
func isErrExist(err error) bool {
	var errno unix.Errno
	return errors.As(err, &errno) && errno == unix.EEXIST
}
