// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type unboundedEncapLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type unboundedEncapTunnelEndpoint struct {
	_        structs.HostLayout
	Nexthops [4]struct {
		_              structs.HostLayout
		RemoteEndpoint [16]uint8
		Vni            uint32
		Ifindex        uint32
		Healthy        uint32
		Protocol       uint32
	}
	Count uint32
}

type unboundedEncapUnbTraceEvent struct {
	_            structs.HostLayout
	TsNs         uint64
	Cpu          uint32
	SkbLen       uint32
	EthProto     uint16
	IpProto      uint8
	Pad0         uint8
	Sport        uint16
	Dport        uint16
	Saddr        [16]uint8
	Daddr        [16]uint8
	LpmPrefixlen uint32
	NhCount      uint32
	ChosenIdx    int32
	Remote       [16]uint8
	Vni          uint32
	Ifindex      uint32
	Protocol     uint32
	NeedsKey     uint8
	Pad1         [3]uint8
	SetKeyRet    int32
	RedirectRet  int32
	Verdict      int32
}

// loadUnboundedEncap returns the embedded CollectionSpec for unboundedEncap.
func loadUnboundedEncap() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UnboundedEncapBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load unboundedEncap: %w", err)
	}

	return spec, err
}

// loadUnboundedEncapObjects loads unboundedEncap and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*unboundedEncapObjects
//	*unboundedEncapPrograms
//	*unboundedEncapMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadUnboundedEncapObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadUnboundedEncap()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// unboundedEncapSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type unboundedEncapSpecs struct {
	unboundedEncapProgramSpecs
	unboundedEncapMapSpecs
	unboundedEncapVariableSpecs
}

// unboundedEncapProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type unboundedEncapProgramSpecs struct {
	UnboundedEncap *ebpf.ProgramSpec `ebpf:"unbounded_encap"`
}

// unboundedEncapMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type unboundedEncapMapSpecs struct {
	UnbEndpts *ebpf.MapSpec `ebpf:"unb_endpts"`
	UnbTrace  *ebpf.MapSpec `ebpf:"unb_trace"`
}

// unboundedEncapVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type unboundedEncapVariableSpecs struct {
	UnbTraceEventLayout *ebpf.VariableSpec `ebpf:"_unb_trace_event_layout"`
}

// unboundedEncapObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadUnboundedEncapObjects or ebpf.CollectionSpec.LoadAndAssign.
type unboundedEncapObjects struct {
	unboundedEncapPrograms
	unboundedEncapMaps
	unboundedEncapVariables
}

func (o *unboundedEncapObjects) Close() error {
	return _UnboundedEncapClose(
		&o.unboundedEncapPrograms,
		&o.unboundedEncapMaps,
	)
}

// unboundedEncapMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadUnboundedEncapObjects or ebpf.CollectionSpec.LoadAndAssign.
type unboundedEncapMaps struct {
	UnbEndpts *ebpf.Map `ebpf:"unb_endpts"`
	UnbTrace  *ebpf.Map `ebpf:"unb_trace"`
}

func (m *unboundedEncapMaps) Close() error {
	return _UnboundedEncapClose(
		m.UnbEndpts,
		m.UnbTrace,
	)
}

// unboundedEncapVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadUnboundedEncapObjects or ebpf.CollectionSpec.LoadAndAssign.
type unboundedEncapVariables struct {
	UnbTraceEventLayout *ebpf.Variable `ebpf:"_unb_trace_event_layout"`
}

// unboundedEncapPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadUnboundedEncapObjects or ebpf.CollectionSpec.LoadAndAssign.
type unboundedEncapPrograms struct {
	UnboundedEncap *ebpf.Program `ebpf:"unbounded_encap"`
}

func (p *unboundedEncapPrograms) Close() error {
	return _UnboundedEncapClose(
		p.UnboundedEncap,
	)
}

func _UnboundedEncapClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed unboundedencap_bpfel.o
var _UnboundedEncapBytes []byte
