# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0

FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.8-trixie AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG TARGETOS
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -trimpath -ldflags="-s -w" -o /out/racer-loadgen ./cmd/racer-loadgen

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /out/racer-loadgen /racer-loadgen
COPY LICENSE NOTICE /usr/share/licenses/racer-loadgen/
# UDS needs write access to /run/racer and a 0600 origin socket the dataplane can use.
# Default to the root dataplane UID; non-root deployments must align ownership and UID.
USER 0:0
EXPOSE 8080 9090
ENTRYPOINT ["/racer-loadgen"]
