# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0

FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.27.0-trixie AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG TARGETOS
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -trimpath -ldflags="-s -w" -o /out/racer-loadgen ./cmd/racer-loadgen

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /out/racer-loadgen /racer-loadgen
COPY LICENSE NOTICE /usr/share/licenses/racer-loadgen/
USER 65532:65532
EXPOSE 8080 9090
ENTRYPOINT ["/racer-loadgen"]
