// Code generated by `make net-ebpf-generate`. DO NOT EDIT.
//
// Generated from the kernel pin in bpf/btf-kernel-pin:
//
// package_url=https://archive.ubuntu.com/ubuntu/pool/main/l/linux-signed/linux-image-7.0.0-31-generic_7.0.0-31.31_amd64.deb
//
// SHA256 hashes are tracked in bpf/btf-kernel-pin-hashes.
// To bump the pin, edit bpf/btf-kernel-pin and run `make net-ebpf-generate`.

typedef unsigned char      __u8;
typedef unsigned short     __u16;
typedef unsigned int       __u32;
typedef unsigned long long __u64;
typedef signed char        __s8;
typedef short              __s16;
typedef int                __s32;
typedef long long          __s64;
typedef __u16              __sum16;
typedef __u32              __wsum;

#ifndef __VMLINUX_H__
#define __VMLINUX_H__

#ifndef BPF_NO_PRESERVE_ACCESS_INDEX
#pragma clang attribute push (__attribute__((preserve_access_index)), apply_to = record)
#endif

#ifndef __ksym
#define __ksym __attribute__((section(".ksyms")))
#endif

#ifndef __weak
#define __weak __attribute__((weak))
#endif

#ifndef __bpf_fastcall
#if __has_attribute(bpf_fastcall)
#define __bpf_fastcall __attribute__((bpf_fastcall))
#else
#define __bpf_fastcall
#endif
#endif


typedef __u16 __be16;



typedef __u32 __be32;

struct __sk_buff {
	__u32 len;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	int: 32;
	__u32 data;
	__u32 data_end;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
};

struct bpf_tunnel_key {
	__u32 tunnel_id;
	union {
		__u32 remote_ipv4;
		__u32 remote_ipv6[4];
	};
	char: 8;
	__u8 tunnel_ttl;
	long: 64;
	long: 64;
	int: 32;
};

struct ethhdr {
	unsigned char h_dest[6];
	int: 32;
	__be16 h_proto;
};

struct in6_addr {
	long: 64;
	long: 64;
};

struct iphdr {
	__u8 ihl: 4;
	long: 0;
	char: 8;
	__u8 protocol;
	union {
		struct {
			__be32 saddr;
			__be32 daddr;
		};
	};
};

struct ipv6hdr {
	long: 48;
	__u8 nexthdr;
	long: 0;
	union {
		struct {
			struct in6_addr saddr;
			struct in6_addr daddr;
		};
	};
};


/* BPF kfuncs */
#ifndef BPF_NO_KFUNC_PROTOTYPES
#endif

#ifndef BPF_NO_PRESERVE_ACCESS_INDEX
#pragma clang attribute pop
#endif

#endif /* __VMLINUX_H__ */
