---
apiVersion: net.unbounded-cloud.io/v1alpha1
kind: SiteGatewayPoolAssignment
metadata:
  name: {{ .SiteName }}
  labels:
    unbounded-cloud.io/site: "{{ .SiteName }}"
spec:
  sites:
    - {{ .SiteName }}
  gatewayPools:
    - gw-main
