package defaults

const (
	LabelKeyDefaultBootstrapTokenSecret   = "unbounded.project-unbounded.io/default-bootstrap-token"
	LabelValueDefaultBootstrapTokenSecret = "true"

	LabelKeyDefaultSSHSecret   = "unbounded.project-unbounded.io/default-ssh-secret"
	LabelValueDefaultSSHSecret = "true"

	// SSHSecretNamespace is the namespace where SSH secrets are stored.
	// This must match the namespace used by the machina controller
	// (SecretNamespaceMachinaSystem in cmd/machina).
	SSHSecretNamespace = "machina-system"

	// SSHSecretName is the default name of the SSH private key secret
	// generated by "kubectl unbounded setup".
	SSHSecretName = "machina-ssh"
)
