apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playpen
rules:
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
- apiGroups: ["apiregistration.k8s.io"]
  resources: ["apiservices"]
  verbs: ["get", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["create", "get", "list", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["nodes/status"]
  verbs: ["update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "delete", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "update", "patch"]
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachines", "virtualmachineinstances"]
  verbs: ["create", "get", "list", "delete", "patch", "update"]
- apiGroups: ["net.unbounded-cloud.io"]
  resources: ["sites", "gatewaypools", "sitegatewaypoolassignments"]
  verbs: ["create", "get", "list", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: playpen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: playpen
subjects:
- kind: ServiceAccount
  name: playpen
  namespace: unbounded-kube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playpen-user
rules:
- apiGroups: ["playpen.unbounded-cloud.io"]
  resources: ["vms/allocate", "vms/deallocate"]
  verbs: ["create"]
