apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.playpen.unbounded-cloud.io
spec:
  group: playpen.unbounded-cloud.io
  version: v1alpha1
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: playpen
    namespace: unbounded-kube
    port: 9443
  insecureSkipTLSVerify: false
