#!/bin/bash
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

set -eo pipefail

# -----------------------------------------------------------------
# Unbounded-kube node bootstrap script
#
# Generated by: kubectl unbounded node-bootstrap
# Machine:      {{ .MachineName }}
# -----------------------------------------------------------------

if [ "$(id -u)" -ne 0 ]; then
  echo "Error: this script must be run as root (use sudo)" >&2
  exit 1
fi

# Write agent config to a temporary file.
UNBOUNDED_AGENT_CONFIG_FILE=$(mktemp /tmp/unbounded-agent-config.XXXXXX.json)
export UNBOUNDED_AGENT_CONFIG_FILE

cat > "${UNBOUNDED_AGENT_CONFIG_FILE}" <<'AGENT_CONFIG_EOF'
{{ .AgentConfigJSON }}
AGENT_CONFIG_EOF

# -----------------------------------------------------------------
# Embedded install script
# -----------------------------------------------------------------

bash <<'INSTALL_SCRIPT_EOF'
{{ .InstallScript }}
INSTALL_SCRIPT_EOF
