apiVersion: v1
kind: Service
metadata:
  name: vllm-api
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    leaderworkerset.sigs.k8s.io/name: vllm
    app.kubernetes.io/component: leader
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
