use super::*;
use crate::control::caches::canonical_socket_paths;
use sha2::{Digest, Sha256};

fn content_hashes(p: &Publication) -> Result<(String, String)> {
    let (content, membership) = canonical_content(p)?;
    Ok((
        format!("{:x}", Sha256::digest(content)),
        format!("{:x}", Sha256::digest(membership)),
    ))
}

const ROOT: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../internal/racer/wire/testdata/"
);
fn fixture(name: &str) -> Vec<u8> {
    let mut b = std::fs::read(format!("{ROOT}{name}")).unwrap();
    if b.last() == Some(&b'\n') {
        b.pop();
    }
    b
}
fn round_trip(name: &str, b: &[u8]) -> Result<Vec<u8>> {
    match name {
        "publication.json" => encode_publication(&decode_publication(b)?),
        "bootstrap-request.json" => encode_enrollment_request(&decode_enrollment_request(b)?),
        "bootstrap-response.json" => encode_enrollment_response(&decode_enrollment_response(b)?),
        "bundle.json" => encode_bundle(&decode_bundle(b)?),
        _ => panic!("unknown vector"),
    }
}

#[test]
fn shared_publication_vectors() {
    let p = decode_publication(fixture("publication.json").as_slice()).unwrap();
    let (content, membership) = canonical_content(&p).unwrap();
    assert_eq!(content, fixture("content.json"));
    assert_eq!(membership, fixture("membership.json"));
    let hashes: Value = serde_json::from_slice(&fixture("hashes.json")).unwrap();
    let (ph, mh) = content_hashes(&p).unwrap();
    assert_eq!(ph, hashes["content"]);
    assert_eq!(mh, hashes["membership"]);
    let b = encode_publication(&p).unwrap();
    assert_eq!(b, round_trip("publication.json", &b).unwrap());
}

#[test]
fn shared_site_vectors() {
    // Generated by Go's opt-in TestGenerateSharedSiteVectors, never by Rust.
    // JSON strings preserve canonical field ordering for byte-for-byte comparisons.
    #[derive(Deserialize)]
    struct SiteVector {
        name: String,
        site: String,
        publication: String,
        content: String,
        membership: String,
        content_hash: String,
        membership_hash: String,
        delta: Option<String>,
    }
    let vectors: Vec<SiteVector> = serde_json::from_slice(&fixture("site-vectors.json")).unwrap();
    assert_eq!(vectors.len(), 4);
    let legacy = decode_publication(&fixture("publication.json")).unwrap();
    let mut previous = None;
    for (i, (name, site)) in [
        ("absent", ""),
        ("added", "Site_1.west-2"),
        ("changed", "Site_2.east-1"),
        ("removed", ""),
    ]
    .into_iter()
    .enumerate()
    {
        let v = &vectors[i];
        assert_eq!(v.name, name);
        assert_eq!(v.site, site);
        let bytes = v.publication.as_bytes();
        let p = decode_publication(bytes).unwrap();
        let mut want = legacy.clone();
        want.sequence.0 = (i + 1) as u64;
        want.membership_version.0 = (i + 1) as u64;
        want.members[0].site = site.into();
        assert_eq!(encode_publication(&want).unwrap(), bytes, "{name}");
        assert_eq!(encode_publication(&p).unwrap(), bytes, "{name}");
        let (content, membership) = canonical_content(&p).unwrap();
        assert_eq!(content, v.content.as_bytes(), "{name}");
        assert_eq!(membership, v.membership.as_bytes(), "{name}");
        let (ph, mh) = content_hashes(&p).unwrap();
        assert_eq!(ph, v.content_hash, "{name}");
        assert_eq!(mh, v.membership_hash, "{name}");
        if let Some(base) = &previous {
            assert_ne!(ph, vectors[i - 1].content_hash);
            assert_ne!(mh, vectors[i - 1].membership_hash);
            let delta = v.delta.as_ref().unwrap().as_bytes();
            let applied = apply_delta(base, delta).unwrap();
            assert_eq!(encode_publication(&applied).unwrap(), bytes, "{name}");
            let mut d: Value = serde_json::from_slice(delta).unwrap();
            assert_eq!(d["upsert_members"].as_array().unwrap().len(), 1);
            assert!(d["remove_members"].as_array().unwrap().is_empty());
            if site.is_empty() {
                assert!(d["upsert_members"][0].get("site").is_none());
            } else {
                assert_eq!(d["upsert_members"][0]["site"], site);
            }
            d["upsert_members"][0]["site"] = "tampered-site".into();
            assert_eq!(
                apply_delta(base, &serde_json::to_vec(&d).unwrap()).err(),
                Some(Error::Replay),
                "Site is bound to the target hash: {name}"
            );
            let mut wrong_base = base.clone();
            wrong_base.members[0].site = "stale-site".into();
            assert_eq!(apply_delta(&wrong_base, delta).err(), Some(Error::Replay));
            assert_eq!(apply_delta(&p, delta).err(), Some(Error::Replay));
        } else {
            assert!(v.delta.is_none());
        }
        previous = Some(p);
    }
    assert_eq!(vectors[0].content, vectors[3].content);
    assert_eq!(vectors[0].membership, vectors[3].membership);
    assert_eq!(vectors[0].content_hash, vectors[3].content_hash);
    assert_eq!(vectors[0].membership_hash, vectors[3].membership_hash);
}

#[test]
fn site_wire_defaults_validation_and_hashes() {
    let mut p = decode_publication(&fixture("publication.json")).unwrap();
    assert!(p.members.iter().all(|m| m.site.is_empty()));
    let legacy = encode_publication(&p).unwrap();
    assert!(
        !String::from_utf8(legacy.clone())
            .unwrap()
            .contains("\"site\"")
    );
    let original = content_hashes(&p).unwrap();
    for site in ["west", "Site_1.west-2", &"A".repeat(63)] {
        p.members[0].site = site.into();
        let encoded = encode_publication(&p).unwrap();
        assert_eq!(decode_publication(&encoded).unwrap().members[0].site, site);
        let changed = content_hashes(&p).unwrap();
        assert_ne!(changed.0, original.0);
        assert_ne!(changed.1, original.1);
    }
    for site in ["-a", "a-", "a_", ".a", "a/b", "é", &"a".repeat(64)] {
        p.members[0].site = site.into();
        assert_eq!(encode_publication(&p), Err(Error::InvalidRequest));
        let mut json: Value = serde_json::from_slice(&legacy).unwrap();
        json["members"][0]["site"] = site.into();
        assert!(decode_publication(&serde_json::to_vec(&json).unwrap()).is_err());
    }
    p.members[0].site.clear();
    assert_eq!(encode_publication(&p).unwrap(), legacy);
    for value in ["null", "1", "true", "[]", "{}", "\"a\",\"site\":\"b\""] {
        let raw = String::from_utf8(legacy.clone()).unwrap().replacen(
            "\"alignment_enabled\":true",
            &format!("\"alignment_enabled\":true,\"site\":{value}"),
            1,
        );
        assert!(decode_publication(raw.as_bytes()).is_err(), "{value}");
    }
}

#[test]
fn shared_bootstrap_and_bundle_vectors() {
    for name in [
        "bootstrap-request.json",
        "bootstrap-response.json",
        "bundle.json",
    ] {
        let b = fixture(name);
        assert_eq!(round_trip(name, &b).unwrap(), b, "{name}");
    }
}

#[test]
fn shared_rejection_vectors() {
    let cases: Value = serde_json::from_slice(&fixture("rejections.json")).unwrap();
    for case in cases.as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let file = case["file"].as_str().unwrap();
        let input = String::from_utf8(fixture(file)).unwrap();
        let mutated = input.replacen(
            case["old"].as_str().unwrap(),
            case["new"].as_str().unwrap(),
            1,
        );
        assert_ne!(input, mutated, "mutation did not match: {name}");
        // The client maps wire version and size failures to its local error domain.
        let expected = match case["code"].as_str().unwrap() {
            "unsupported_version" => Error::IncompatibleMembership,
            "too_large" => Error::Overloaded,
            "invalid_request" => Error::InvalidRequest,
            code => panic!("unexpected rejection code: {code}"),
        };
        assert_eq!(
            round_trip(file, mutated.as_bytes()).err(),
            Some(expected),
            "{name}"
        );
    }
}

#[test]
fn hash_semantics() {
    let mut p = decode_publication(fixture("publication.json").as_slice()).unwrap();
    let hashes = content_hashes(&p).unwrap();
    p.sequence.0 = 0;
    p.membership_version.0 = 0;
    p.members.reverse();
    p.members[0].rails.reverse();
    assert_eq!(content_hashes(&p).unwrap(), hashes);
    assert_eq!(p.members[0].rails[0].rail.0, 65535, "caller input mutated");
    p.caches[0].id = CacheId("66666666-6666-4666-8666-666666666666".into());
    let changed = content_hashes(&p).unwrap();
    assert_ne!(changed.0, hashes.0);
    assert_eq!(changed.1, hashes.1);
    p.members[0].peer_endpoint = "[2001:db8::2]:7443".into();
    let endpoint = content_hashes(&p).unwrap();
    assert_ne!(endpoint.0, changed.0);
    assert_ne!(endpoint.1, changed.1);
}

#[test]
fn local_publications_share_wire_validation_and_normalization() {
    let original = decode_publication(&fixture("publication.json")).unwrap();
    let mut unsorted = original.clone();
    unsorted.members.reverse();
    for member in &mut unsorted.members {
        member.rails.reverse();
    }
    let normalized = validate_publication(&unsorted).unwrap();
    assert_eq!(
        encode_publication(&normalized).unwrap(),
        encode_publication(&original).unwrap()
    );
    for mutation in 0..8 {
        let mut candidate = original.clone();
        match mutation {
            0 => candidate.schema_version += 1,
            1 => candidate.cluster.0 = "invalid".into(),
            2 => candidate.sequence.0 = 0,
            3 => candidate.membership_version.0 = 0,
            4 => candidate.members.push(candidate.members[0].clone()),
            5 => candidate.members[0].peer_endpoint = "host:443".into(),
            6 => {
                let member = candidate
                    .members
                    .iter_mut()
                    .find(|m| !m.rails.is_empty())
                    .unwrap();
                let duplicate = member.rails[0].clone();
                member.rails.push(duplicate);
            }
            _ => candidate.caches[0].client_socket = "/unexpected/socket".into(),
        }
        let bytes = encode(&dto(&candidate).unwrap(), MAX_PUBLICATION_BYTES).unwrap();
        let expected = decode_publication(&bytes).err();
        assert!(expected.is_some(), "mutation {mutation}");
        assert_eq!(
            validate_publication(&candidate).err(),
            expected,
            "mutation {mutation}"
        );
        assert_eq!(
            encode_publication(&candidate).err(),
            expected,
            "mutation {mutation}"
        );
    }
}

#[test]
fn byte_bounds_and_malformed_documents() {
    for (name, max) in [
        ("publication.json", MAX_PUBLICATION_BYTES),
        ("bootstrap-request.json", MAX_ENROLLMENT_BYTES),
        ("bootstrap-response.json", MAX_ENROLLMENT_BYTES),
        ("bundle.json", MAX_BUNDLE_BYTES),
    ] {
        let b = fixture(name);
        let mut padded = b.clone();
        padded.resize(max, b' ');
        assert!(round_trip(name, &padded).is_ok(), "exact bound {name}");
        padded.push(b' ');
        assert_eq!(round_trip(name, &padded).err(), Some(Error::Overloaded));
        for bad in [
            Vec::new(),
            b"null".to_vec(),
            b"[]".to_vec(),
            b[..b.len() - 1].to_vec(),
            [b.as_slice(), b"{}"].concat(),
            [b.as_slice(), &[0xff]].concat(),
            format!("{}{}", "[".repeat(1000), "]".repeat(1000)).into_bytes(),
        ] {
            assert_eq!(
                round_trip(name, &bad).err(),
                Some(Error::InvalidRequest),
                "{name}"
            );
        }
    }
    // Runtime decoders accept already bounded byte slices, not Read adapters.
    let source = vec![0; MAX_ENROLLMENT_BYTES * 10];
    assert_eq!(
        decode_enrollment_request(&source).err(),
        Some(Error::Overloaded)
    );
}

#[test]
fn path_member_and_enum_bounds() {
    for name in [
        ".",
        "..",
        "a/b",
        "a\\b",
        "a\0b",
        "A",
        "-a",
        "a-",
        "a..b",
        &"a".repeat(64),
    ] {
        assert!(canonical_socket_paths(name).is_err());
    }
    let name = format!("{}.{}", "a".repeat(63), "b".repeat(18));
    assert_eq!(
        canonical_socket_paths(&name).unwrap().0.as_os_str().len(),
        107
    );
    assert!(canonical_socket_paths(&(name + "b")).is_err());
    let mut p = decode_publication(fixture("publication.json").as_slice()).unwrap();
    p.members.resize(MAX_MEMBERS + 1, p.members[0].clone());
    assert_eq!(encode_publication(&p).err(), Some(Error::Overloaded));
    for code in [
        "invalid_request",
        "unauthenticated",
        "forbidden",
        "conflict",
        "too_large",
        "unsupported_version",
        "overloaded",
        "unavailable",
    ] {
        let b = format!(r#"{{"code":"{code}"}}"#);
        assert_eq!(
            encode_error(&decode_error(b.as_bytes()).unwrap()).unwrap(),
            b.as_bytes()
        );
    }
    assert!(decode_error(br#"{"code":"future"}"#.as_slice()).is_err());
}

#[test]
fn maximum_membership() {
    let mut p = decode_publication(fixture("publication.json").as_slice()).unwrap();
    p.members = (0..MAX_MEMBERS)
        .map(|i| Member {
            node: NodeId(format!("{i:08x}-1111-4111-8111-111111111111")),
            shares: NonZeroU32::new(1).unwrap(),
            peer_endpoint: "192.0.2.1:1".into(),
            rails: vec![],
            alignment_enabled: false,
            site: String::new(),
        })
        .collect();
    let b = encode_publication(&p).unwrap();
    assert_eq!(
        decode_publication(b.as_slice()).unwrap().members.len(),
        MAX_MEMBERS
    );
    let mut dto = dto(&p).unwrap();
    let extra: MemberDto =
        serde_json::from_value(serde_json::to_value(&dto.members[0]).unwrap()).unwrap();
    dto.members.push(extra);
    let b = encode(&dto, MAX_PUBLICATION_BYTES).unwrap();
    assert_eq!(
        decode_publication(b.as_slice()).err(),
        Some(Error::Overloaded)
    );
}
