FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.27.0-trixie AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS=linux
ARG TARGETARCH=amd64
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -trimpath -ldflags="-s -w" -o /out/acr-origin-proxy ./hack/cmd/acr-origin-proxy

FROM gcr.io/distroless/static-debian12:nonroot

EXPOSE 5002 9090

COPY --from=builder /out/acr-origin-proxy /usr/local/bin/acr-origin-proxy
COPY LICENSE NOTICE /unbounded/licenses/

USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/acr-origin-proxy"]
