#!/usr/bin/env bash
# Generate a fresh basic-auth Secret manifest for the W1.1 Ingress.
#
# Output: secret.local.yaml (gitignored). The cleartext password is printed
# ONCE to stdout so the operator can save it to a password manager.
#
# Re-run to rotate. The Secret name is `ollama-basic-auth` and is referenced
# from ingress.yaml.

set -euo pipefail

cd "$(dirname "$0")"

USER="${LAB_AUTH_USER:-lab}"
PASS=$(openssl rand -base64 24 | tr -d '+/=' | head -c 32)
HASH=$(printf '%s' "$PASS" | openssl passwd -apr1 -stdin)

cat > secret.local.yaml <<EOF
# Generated by make-auth-secret.sh. DO NOT EDIT BY HAND.
# Regenerate to rotate. Gitignored.
apiVersion: v1
kind: Secret
metadata:
  name: ollama-basic-auth
  namespace: lab-ollama-qwen-moe
type: Opaque
stringData:
  # nginx-ingress basic-auth Secret format: htpasswd file content under key 'auth'.
  auth: |
    ${USER}:${HASH}
EOF

cat <<EOF
secret.local.yaml written.

Credentials (save NOW; not stored anywhere else):
  user: ${USER}
  pass: ${PASS}

Apply with:
  kubectl apply -k lab/inference/ollama-qwen-moe/

Test through ingress (after DNS points at the ingress LB):
  curl -u ${USER}:${PASS} https://<host>/api/tags
EOF
