baseURL = "/unbounded/"
languageCode = "en-us"
title = "Unbounded"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  description = "Run nodes across multiple cloud providers and bare-metal infrastructure to form a unified Kubernetes cluster, no matter where your infrastructure lives."
  repo = "https://github.com/Azure/unbounded"

[menu]
  [[menu.main]]
    name = "Guides"
    pageRef = "/guides"
    weight = 1
  [[menu.main]]
    name = "Concepts"
    pageRef = "/concepts"
    weight = 2
  [[menu.main]]
    name = "Reference"
    pageRef = "/reference"
    weight = 3
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/Azure/unbounded"
    weight = 4
