// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: config.proto

package storageconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiskKind int32

const (
	DiskKind_DISK_KIND_NVME  DiskKind = 0
	DiskKind_DISK_KIND_BLOCK DiskKind = 1
	DiskKind_DISK_KIND_FILE  DiskKind = 2
)

// Enum value maps for DiskKind.
var (
	DiskKind_name = map[int32]string{
		0: "DISK_KIND_NVME",
		1: "DISK_KIND_BLOCK",
		2: "DISK_KIND_FILE",
	}
	DiskKind_value = map[string]int32{
		"DISK_KIND_NVME":  0,
		"DISK_KIND_BLOCK": 1,
		"DISK_KIND_FILE":  2,
	}
)

func (x DiskKind) Enum() *DiskKind {
	p := new(DiskKind)
	*p = x
	return p
}

func (x DiskKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiskKind) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (DiskKind) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x DiskKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiskKind.Descriptor instead.
func (DiskKind) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

type BackendKind int32

const (
	BackendKind_BACKEND_KIND_HTTP  BackendKind = 0
	BackendKind_BACKEND_KIND_S3    BackendKind = 1
	BackendKind_BACKEND_KIND_AZURE BackendKind = 2
)

// Enum value maps for BackendKind.
var (
	BackendKind_name = map[int32]string{
		0: "BACKEND_KIND_HTTP",
		1: "BACKEND_KIND_S3",
		2: "BACKEND_KIND_AZURE",
	}
	BackendKind_value = map[string]int32{
		"BACKEND_KIND_HTTP":  0,
		"BACKEND_KIND_S3":    1,
		"BACKEND_KIND_AZURE": 2,
	}
)

func (x BackendKind) Enum() *BackendKind {
	p := new(BackendKind)
	*p = x
	return p
}

func (x BackendKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackendKind) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[1].Descriptor()
}

func (BackendKind) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[1]
}

func (x BackendKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackendKind.Descriptor instead.
func (BackendKind) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

type FrontendKind int32

const (
	FrontendKind_FRONTEND_KIND_HTTP FrontendKind = 0
	FrontendKind_FRONTEND_KIND_S3   FrontendKind = 1
)

// Enum value maps for FrontendKind.
var (
	FrontendKind_name = map[int32]string{
		0: "FRONTEND_KIND_HTTP",
		1: "FRONTEND_KIND_S3",
	}
	FrontendKind_value = map[string]int32{
		"FRONTEND_KIND_HTTP": 0,
		"FRONTEND_KIND_S3":   1,
	}
)

func (x FrontendKind) Enum() *FrontendKind {
	p := new(FrontendKind)
	*p = x
	return p
}

func (x FrontendKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrontendKind) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[2].Descriptor()
}

func (FrontendKind) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[2]
}

func (x FrontendKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrontendKind.Descriptor instead.
func (FrontendKind) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator-assigned configuration version. The daemon treats it as an
	// opaque counter: it never drives behavior, but it is tracked as the
	// latest-known and latest-applied config versions so operators can
	// confirm a pushed config has been realized across the process. The
	// proto3 zero value (0) means "unversioned".
	Version   uint64          `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	P2P       *P2PCfg         `protobuf:"bytes,1,opt,name=p2p,proto3" json:"p2p,omitempty"`
	Peers     []*PeerSpec     `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	Disks     []*DiskSpec     `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
	Backends  []*BackendSpec  `protobuf:"bytes,4,rep,name=backends,proto3" json:"backends,omitempty"`
	Frontends []*FrontendSpec `protobuf:"bytes,5,rep,name=frontends,proto3" json:"frontends,omitempty"`
	// Startup-fixed settings (memory backing, fabric endpoint/threads, CPU
	// topology placement). Unlike the rest of the config these cannot be
	// hot-reloaded: they are read exactly once when the process starts and
	// changing them requires a restart. They are deliberately excluded from
	// ConfigDiff; operators observe which config version's startup settings
	// are realized via the separately tracked "startup" config version.
	Startup       *StartupCfg `protobuf:"bytes,7,opt,name=startup,proto3" json:"startup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Config) GetP2P() *P2PCfg {
	if x != nil {
		return x.P2P
	}
	return nil
}

func (x *Config) GetPeers() []*PeerSpec {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Config) GetDisks() []*DiskSpec {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *Config) GetBackends() []*BackendSpec {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *Config) GetFrontends() []*FrontendSpec {
	if x != nil {
		return x.Frontends
	}
	return nil
}

func (x *Config) GetStartup() *StartupCfg {
	if x != nil {
		return x.Startup
	}
	return nil
}

// Startup-fixed settings, grouped by the subsystem that consumes them.
// Every field's proto3 zero value means "unset" and is promoted to the
// documented default by Config::apply_defaults.
type StartupCfg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *MemoryCfg             `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Fabric        *FabricCfg             `protobuf:"bytes,2,opt,name=fabric,proto3" json:"fabric,omitempty"`
	Topology      *TopologyCfg           `protobuf:"bytes,3,opt,name=topology,proto3" json:"topology,omitempty"`
	Metrics       *MetricsCfg            `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartupCfg) Reset() {
	*x = StartupCfg{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartupCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartupCfg) ProtoMessage() {}

func (x *StartupCfg) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartupCfg.ProtoReflect.Descriptor instead.
func (*StartupCfg) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *StartupCfg) GetMemory() *MemoryCfg {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *StartupCfg) GetFabric() *FabricCfg {
	if x != nil {
		return x.Fabric
	}
	return nil
}

func (x *StartupCfg) GetTopology() *TopologyCfg {
	if x != nil {
		return x.Topology
	}
	return nil
}

func (x *StartupCfg) GetMetrics() *MetricsCfg {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricsCfg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Listen address for the Prometheus metrics exporter (e.g.
	// "0.0.0.0:9100"). "" -> exporter disabled.
	Bind          string `protobuf:"bytes,1,opt,name=bind,proto3" json:"bind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsCfg) Reset() {
	*x = MetricsCfg{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsCfg) ProtoMessage() {}

func (x *MetricsCfg) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsCfg.ProtoReflect.Descriptor instead.
func (*MetricsCfg) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsCfg) GetBind() string {
	if x != nil {
		return x.Bind
	}
	return ""
}

type MemoryCfg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allocate per-shard backing from the heap instead of 2 MiB hugepages.
	NoHugepages bool `protobuf:"varint,1,opt,name=no_hugepages,json=noHugepages,proto3" json:"no_hugepages,omitempty"`
	// Total backing pool across all serving shards, in bytes. Each serving
	// shard is allocated `memory_total_bytes / serving_shard_count`,
	// NUMA-local, so the host footprint stays fixed regardless of the
	// auto-scaled serving-core count. 0 -> 128 MiB.
	MemoryTotalBytes uint64 `protobuf:"varint,2,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemoryCfg) Reset() {
	*x = MemoryCfg{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryCfg) ProtoMessage() {}

func (x *MemoryCfg) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryCfg.ProtoReflect.Descriptor instead.
func (*MemoryCfg) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *MemoryCfg) GetNoHugepages() bool {
	if x != nil {
		return x.NoHugepages
	}
	return false
}

func (x *MemoryCfg) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

type FabricCfg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-shard fabric listen address. "" -> "0.0.0.0:0" (":0" picks a free
	// port).
	ListenAddr string `protobuf:"bytes,1,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	// libfabric progress threads per shard. 0 -> 2.
	ProgressThreads uint32 `protobuf:"varint,2,opt,name=progress_threads,json=progressThreads,proto3" json:"progress_threads,omitempty"`
	// Progress-thread busy-poll budget in microseconds. 0 -> 10.
	ProgressPollUs uint32 `protobuf:"varint,3,opt,name=progress_poll_us,json=progressPollUs,proto3" json:"progress_poll_us,omitempty"`
	// Fabric RPC worker threads per shard. 0 -> 4.
	RpcWorkerThreads uint32 `protobuf:"varint,4,opt,name=rpc_worker_threads,json=rpcWorkerThreads,proto3" json:"rpc_worker_threads,omitempty"`
	// Max in-flight fabric operations per shard (back-pressure limit that
	// sizes the completion registry and server-side request cap). 0 -> 1024.
	MaxInflight   uint32 `protobuf:"varint,5,opt,name=max_inflight,json=maxInflight,proto3" json:"max_inflight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FabricCfg) Reset() {
	*x = FabricCfg{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FabricCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FabricCfg) ProtoMessage() {}

func (x *FabricCfg) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FabricCfg.ProtoReflect.Descriptor instead.
func (*FabricCfg) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *FabricCfg) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *FabricCfg) GetProgressThreads() uint32 {
	if x != nil {
		return x.ProgressThreads
	}
	return 0
}

func (x *FabricCfg) GetProgressPollUs() uint32 {
	if x != nil {
		return x.ProgressPollUs
	}
	return 0
}

func (x *FabricCfg) GetRpcWorkerThreads() uint32 {
	if x != nil {
		return x.RpcWorkerThreads
	}
	return 0
}

func (x *FabricCfg) GetMaxInflight() uint32 {
	if x != nil {
		return x.MaxInflight
	}
	return 0
}

type TopologyCfg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Place shards on SMT sibling CPUs as well as physical cores.
	UseSmtSiblings bool `protobuf:"varint,4,opt,name=use_smt_siblings,json=useSmtSiblings,proto3" json:"use_smt_siblings,omitempty"`
	// Schedule shards onto isolcpus-isolated CPUs too. The proto3 false
	// default preserves the historical "respect isolated CPUs" behavior.
	IgnoreIsolated bool `protobuf:"varint,5,opt,name=ignore_isolated,json=ignoreIsolated,proto3" json:"ignore_isolated,omitempty"`
	// Allow placing a shard on each NUMA node's CPU 0. The proto3 false
	// default preserves the historical "exclude node CPU 0" behavior.
	IncludeNodeCpu0 bool `protobuf:"varint,6,opt,name=include_node_cpu0,json=includeNodeCpu0,proto3" json:"include_node_cpu0,omitempty"`
	// Use HCA ports that are not in the active state. The proto3 false
	// default preserves the historical "require active port" behavior.
	AllowInactivePort bool `protobuf:"varint,7,opt,name=allow_inactive_port,json=allowInactivePort,proto3" json:"allow_inactive_port,omitempty"`
	// Disable RDMA and force the libfabric tcp provider.
	DisableRdma bool `protobuf:"varint,8,opt,name=disable_rdma,json=disableRdma,proto3" json:"disable_rdma,omitempty"`
	// Cap on the number of serving-shard CPUs to pin. 0 -> auto (claim
	// every usable core left after storage and NIC-worker reservations).
	ServingCores uint64 `protobuf:"varint,9,opt,name=serving_cores,json=servingCores,proto3" json:"serving_cores,omitempty"`
	// NIC-worker CPUs to pin per active HCA. 0 -> 4.
	NicWorkers uint64 `protobuf:"varint,10,opt,name=nic_workers,json=nicWorkers,proto3" json:"nic_workers,omitempty"`
	// Maximum number of HCAs to use per NUMA node. 0 -> 1. Raise this to
	// use additional HCAs on a NUMA node. HCAs whose NUMA node is unknown
	// are never capped.
	HcasPerNumaNode uint64 `protobuf:"varint,11,opt,name=hcas_per_numa_node,json=hcasPerNumaNode,proto3" json:"hcas_per_numa_node,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TopologyCfg) Reset() {
	*x = TopologyCfg{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyCfg) ProtoMessage() {}

func (x *TopologyCfg) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyCfg.ProtoReflect.Descriptor instead.
func (*TopologyCfg) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *TopologyCfg) GetUseSmtSiblings() bool {
	if x != nil {
		return x.UseSmtSiblings
	}
	return false
}

func (x *TopologyCfg) GetIgnoreIsolated() bool {
	if x != nil {
		return x.IgnoreIsolated
	}
	return false
}

func (x *TopologyCfg) GetIncludeNodeCpu0() bool {
	if x != nil {
		return x.IncludeNodeCpu0
	}
	return false
}

func (x *TopologyCfg) GetAllowInactivePort() bool {
	if x != nil {
		return x.AllowInactivePort
	}
	return false
}

func (x *TopologyCfg) GetDisableRdma() bool {
	if x != nil {
		return x.DisableRdma
	}
	return false
}

func (x *TopologyCfg) GetServingCores() uint64 {
	if x != nil {
		return x.ServingCores
	}
	return 0
}

func (x *TopologyCfg) GetNicWorkers() uint64 {
	if x != nil {
		return x.NicWorkers
	}
	return 0
}

func (x *TopologyCfg) GetHcasPerNumaNode() uint64 {
	if x != nil {
		return x.HcasPerNumaNode
	}
	return 0
}

type P2PCfg struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FingersPerNode uint32                 `protobuf:"varint,1,opt,name=fingers_per_node,json=fingersPerNode,proto3" json:"fingers_per_node,omitempty"`
	LocalNodeId    *uint64                `protobuf:"varint,2,opt,name=local_node_id,json=localNodeId,proto3,oneof" json:"local_node_id,omitempty"`
	LocalLabels    []string               `protobuf:"bytes,3,rep,name=local_labels,json=localLabels,proto3" json:"local_labels,omitempty"`
	// When set, the daemon uses this precomputed routing table verbatim
	// instead of deriving fingers from the full peer set. This is the
	// "disjoint discovery" mode: a global-view planner selects each
	// node's neighbors and ships them here, so a node only needs to know
	// (and connect to) its direct routing neighbors. When unset, the
	// daemon falls back to building the finger table from `peers` using
	// `fingers_per_node`.
	RoutingPlan   *RoutingPlan `protobuf:"bytes,4,opt,name=routing_plan,json=routingPlan,proto3,oneof" json:"routing_plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PCfg) Reset() {
	*x = P2PCfg{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PCfg) ProtoMessage() {}

func (x *P2PCfg) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PCfg.ProtoReflect.Descriptor instead.
func (*P2PCfg) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *P2PCfg) GetFingersPerNode() uint32 {
	if x != nil {
		return x.FingersPerNode
	}
	return 0
}

func (x *P2PCfg) GetLocalNodeId() uint64 {
	if x != nil && x.LocalNodeId != nil {
		return *x.LocalNodeId
	}
	return 0
}

func (x *P2PCfg) GetLocalLabels() []string {
	if x != nil {
		return x.LocalLabels
	}
	return nil
}

func (x *P2PCfg) GetRoutingPlan() *RoutingPlan {
	if x != nil {
		return x.RoutingPlan
	}
	return nil
}

// A precomputed routing table for a single node, produced by a
// global-view planner. All ids reference `PeerSpec.id` values in the
// `peers` list (each must be present so a fabric connection exists).
// Ring positions are derived from ids, and labels do not affect runtime
// routing, so only ids are carried here.
type RoutingPlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer ids selected as fingers. The local node id is excluded and
	// the order is irrelevant (routing scans all fingers regardless).
	Fingers []uint64 `protobuf:"varint,1,rep,packed,name=fingers,proto3" json:"fingers,omitempty"`
	// Peer id of the nearest-forward neighbor on the ring.
	Successor *uint64 `protobuf:"varint,2,opt,name=successor,proto3,oneof" json:"successor,omitempty"`
	// Peer id of the nearest-backward neighbor on the ring.
	Predecessor   *uint64 `protobuf:"varint,3,opt,name=predecessor,proto3,oneof" json:"predecessor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingPlan) Reset() {
	*x = RoutingPlan{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingPlan) ProtoMessage() {}

func (x *RoutingPlan) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingPlan.ProtoReflect.Descriptor instead.
func (*RoutingPlan) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *RoutingPlan) GetFingers() []uint64 {
	if x != nil {
		return x.Fingers
	}
	return nil
}

func (x *RoutingPlan) GetSuccessor() uint64 {
	if x != nil && x.Successor != nil {
		return *x.Successor
	}
	return 0
}

func (x *RoutingPlan) GetPredecessor() uint64 {
	if x != nil && x.Predecessor != nil {
		return *x.Predecessor
	}
	return 0
}

type FabricAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Numeric IP socket address usable by libfabric/RDMA CM, e.g.
	// "10.0.0.1:9000". On InfiniBand this is usually an IPoIB address;
	// on tcp fallback it is a normal TCP socket address.
	Socket string `protobuf:"bytes,1,opt,name=socket,proto3" json:"socket,omitempty"`
	// Provider-native escape hatch for RDMA deployments without socket
	// addressing. Currently encoded as "hex:<fi_getname-bytes>" so a
	// controller can publish the raw provider address when needed.
	Native        string `protobuf:"bytes,2,opt,name=native,proto3" json:"native,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FabricAddress) Reset() {
	*x = FabricAddress{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FabricAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FabricAddress) ProtoMessage() {}

func (x *FabricAddress) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FabricAddress.ProtoReflect.Descriptor instead.
func (*FabricAddress) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *FabricAddress) GetSocket() string {
	if x != nil {
		return x.Socket
	}
	return ""
}

func (x *FabricAddress) GetNative() string {
	if x != nil {
		return x.Native
	}
	return ""
}

type PeerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       *FabricAddress         `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	HcaNuma       *uint32                `protobuf:"varint,3,opt,name=hca_numa,json=hcaNuma,proto3,oneof" json:"hca_numa,omitempty"`
	Labels        []string               `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerSpec) Reset() {
	*x = PeerSpec{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSpec) ProtoMessage() {}

func (x *PeerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSpec.ProtoReflect.Descriptor instead.
func (*PeerSpec) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *PeerSpec) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PeerSpec) GetAddress() *FabricAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PeerSpec) GetHcaNuma() uint32 {
	if x != nil && x.HcaNuma != nil {
		return *x.HcaNuma
	}
	return 0
}

func (x *PeerSpec) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type DiskSpec struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Path                     string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Kind                     DiskKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=unbounded.storage.config.DiskKind" json:"kind,omitempty"`
	Size                     *uint64                `protobuf:"varint,3,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Numa                     *uint32                `protobuf:"varint,4,opt,name=numa,proto3,oneof" json:"numa,omitempty"`
	QueueDepth               *uint32                `protobuf:"varint,5,opt,name=queue_depth,json=queueDepth,proto3,oneof" json:"queue_depth,omitempty"`
	PageSizeBytes            *uint64                `protobuf:"varint,6,opt,name=page_size_bytes,json=pageSizeBytes,proto3,oneof" json:"page_size_bytes,omitempty"`
	BypassAdmission          bool                   `protobuf:"varint,7,opt,name=bypass_admission,json=bypassAdmission,proto3" json:"bypass_admission,omitempty"`
	SkipRecoveryScanIfNoMeta bool                   `protobuf:"varint,8,opt,name=skip_recovery_scan_if_no_meta,json=skipRecoveryScanIfNoMeta,proto3" json:"skip_recovery_scan_if_no_meta,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DiskSpec) Reset() {
	*x = DiskSpec{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSpec) ProtoMessage() {}

func (x *DiskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSpec.ProtoReflect.Descriptor instead.
func (*DiskSpec) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10}
}

func (x *DiskSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskSpec) GetKind() DiskKind {
	if x != nil {
		return x.Kind
	}
	return DiskKind_DISK_KIND_NVME
}

func (x *DiskSpec) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *DiskSpec) GetNuma() uint32 {
	if x != nil && x.Numa != nil {
		return *x.Numa
	}
	return 0
}

func (x *DiskSpec) GetQueueDepth() uint32 {
	if x != nil && x.QueueDepth != nil {
		return *x.QueueDepth
	}
	return 0
}

func (x *DiskSpec) GetPageSizeBytes() uint64 {
	if x != nil && x.PageSizeBytes != nil {
		return *x.PageSizeBytes
	}
	return 0
}

func (x *DiskSpec) GetBypassAdmission() bool {
	if x != nil {
		return x.BypassAdmission
	}
	return false
}

func (x *DiskSpec) GetSkipRecoveryScanIfNoMeta() bool {
	if x != nil {
		return x.SkipRecoveryScanIfNoMeta
	}
	return false
}

type BackendSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind            BackendKind            `protobuf:"varint,2,opt,name=kind,proto3,enum=unbounded.storage.config.BackendKind" json:"kind,omitempty"`
	Endpoint        string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	StripeSizeBytes uint64                 `protobuf:"varint,4,opt,name=stripe_size_bytes,json=stripeSizeBytes,proto3" json:"stripe_size_bytes,omitempty"`
	HttpConcurrency uint32                 `protobuf:"varint,5,opt,name=http_concurrency,json=httpConcurrency,proto3" json:"http_concurrency,omitempty"`
	Bucket          *string                `protobuf:"bytes,6,opt,name=bucket,proto3,oneof" json:"bucket,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BackendSpec) Reset() {
	*x = BackendSpec{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendSpec) ProtoMessage() {}

func (x *BackendSpec) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendSpec.ProtoReflect.Descriptor instead.
func (*BackendSpec) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{11}
}

func (x *BackendSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackendSpec) GetKind() BackendKind {
	if x != nil {
		return x.Kind
	}
	return BackendKind_BACKEND_KIND_HTTP
}

func (x *BackendSpec) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *BackendSpec) GetStripeSizeBytes() uint64 {
	if x != nil {
		return x.StripeSizeBytes
	}
	return 0
}

func (x *BackendSpec) GetHttpConcurrency() uint32 {
	if x != nil {
		return x.HttpConcurrency
	}
	return 0
}

func (x *BackendSpec) GetBucket() string {
	if x != nil && x.Bucket != nil {
		return *x.Bucket
	}
	return ""
}

type FrontendSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          FrontendKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=unbounded.storage.config.FrontendKind" json:"kind,omitempty"`
	Bind          string                 `protobuf:"bytes,3,opt,name=bind,proto3" json:"bind,omitempty"`
	Backend       string                 `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendSpec) Reset() {
	*x = FrontendSpec{}
	mi := &file_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendSpec) ProtoMessage() {}

func (x *FrontendSpec) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendSpec.ProtoReflect.Descriptor instead.
func (*FrontendSpec) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{12}
}

func (x *FrontendSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FrontendSpec) GetKind() FrontendKind {
	if x != nil {
		return x.Kind
	}
	return FrontendKind_FRONTEND_KIND_HTTP
}

func (x *FrontendSpec) GetBind() string {
	if x != nil {
		return x.Bind
	}
	return ""
}

func (x *FrontendSpec) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x18unbounded.storage.config\"\x93\x03\n" +
	"\x06Config\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\x122\n" +
	"\x03p2p\x18\x01 \x01(\v2 .unbounded.storage.config.P2pCfgR\x03p2p\x128\n" +
	"\x05peers\x18\x02 \x03(\v2\".unbounded.storage.config.PeerSpecR\x05peers\x128\n" +
	"\x05disks\x18\x03 \x03(\v2\".unbounded.storage.config.DiskSpecR\x05disks\x12A\n" +
	"\bbackends\x18\x04 \x03(\v2%.unbounded.storage.config.BackendSpecR\bbackends\x12D\n" +
	"\tfrontends\x18\x05 \x03(\v2&.unbounded.storage.config.FrontendSpecR\tfrontends\x12>\n" +
	"\astartup\x18\a \x01(\v2$.unbounded.storage.config.StartupCfgR\astartup\"\x89\x02\n" +
	"\n" +
	"StartupCfg\x12;\n" +
	"\x06memory\x18\x01 \x01(\v2#.unbounded.storage.config.MemoryCfgR\x06memory\x12;\n" +
	"\x06fabric\x18\x02 \x01(\v2#.unbounded.storage.config.FabricCfgR\x06fabric\x12A\n" +
	"\btopology\x18\x03 \x01(\v2%.unbounded.storage.config.TopologyCfgR\btopology\x12>\n" +
	"\ametrics\x18\x04 \x01(\v2$.unbounded.storage.config.MetricsCfgR\ametrics\" \n" +
	"\n" +
	"MetricsCfg\x12\x12\n" +
	"\x04bind\x18\x01 \x01(\tR\x04bind\"\\\n" +
	"\tMemoryCfg\x12!\n" +
	"\fno_hugepages\x18\x01 \x01(\bR\vnoHugepages\x12,\n" +
	"\x12memory_total_bytes\x18\x02 \x01(\x04R\x10memoryTotalBytes\"\xd2\x01\n" +
	"\tFabricCfg\x12\x1f\n" +
	"\vlisten_addr\x18\x01 \x01(\tR\n" +
	"listenAddr\x12)\n" +
	"\x10progress_threads\x18\x02 \x01(\rR\x0fprogressThreads\x12(\n" +
	"\x10progress_poll_us\x18\x03 \x01(\rR\x0eprogressPollUs\x12,\n" +
	"\x12rpc_worker_threads\x18\x04 \x01(\rR\x10rpcWorkerThreads\x12!\n" +
	"\fmax_inflight\x18\x05 \x01(\rR\vmaxInflight\"\xa8\x03\n" +
	"\vTopologyCfg\x12(\n" +
	"\x10use_smt_siblings\x18\x04 \x01(\bR\x0euseSmtSiblings\x12'\n" +
	"\x0fignore_isolated\x18\x05 \x01(\bR\x0eignoreIsolated\x12*\n" +
	"\x11include_node_cpu0\x18\x06 \x01(\bR\x0fincludeNodeCpu0\x12.\n" +
	"\x13allow_inactive_port\x18\a \x01(\bR\x11allowInactivePort\x12!\n" +
	"\fdisable_rdma\x18\b \x01(\bR\vdisableRdma\x12#\n" +
	"\rserving_cores\x18\t \x01(\x04R\fservingCores\x12\x1f\n" +
	"\vnic_workers\x18\n" +
	" \x01(\x04R\n" +
	"nicWorkers\x12+\n" +
	"\x12hcas_per_numa_node\x18\v \x01(\x04R\x0fhcasPerNumaNodeJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x15rdma_progress_per_hcaR\x15rdma_handlers_per_hcaR\x14tcp_fallback_threads\"\xf0\x01\n" +
	"\x06P2pCfg\x12(\n" +
	"\x10fingers_per_node\x18\x01 \x01(\rR\x0efingersPerNode\x12'\n" +
	"\rlocal_node_id\x18\x02 \x01(\x04H\x00R\vlocalNodeId\x88\x01\x01\x12!\n" +
	"\flocal_labels\x18\x03 \x03(\tR\vlocalLabels\x12M\n" +
	"\frouting_plan\x18\x04 \x01(\v2%.unbounded.storage.config.RoutingPlanH\x01R\vroutingPlan\x88\x01\x01B\x10\n" +
	"\x0e_local_node_idB\x0f\n" +
	"\r_routing_plan\"\x8f\x01\n" +
	"\vRoutingPlan\x12\x18\n" +
	"\afingers\x18\x01 \x03(\x04R\afingers\x12!\n" +
	"\tsuccessor\x18\x02 \x01(\x04H\x00R\tsuccessor\x88\x01\x01\x12%\n" +
	"\vpredecessor\x18\x03 \x01(\x04H\x01R\vpredecessor\x88\x01\x01B\f\n" +
	"\n" +
	"_successorB\x0e\n" +
	"\f_predecessor\"?\n" +
	"\rFabricAddress\x12\x16\n" +
	"\x06socket\x18\x01 \x01(\tR\x06socket\x12\x16\n" +
	"\x06native\x18\x02 \x01(\tR\x06native\"\xa2\x01\n" +
	"\bPeerSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12A\n" +
	"\aaddress\x18\x02 \x01(\v2'.unbounded.storage.config.FabricAddressR\aaddress\x12\x1e\n" +
	"\bhca_numa\x18\x03 \x01(\rH\x00R\ahcaNuma\x88\x01\x01\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labelsB\v\n" +
	"\t_hca_numa\"\xfd\x02\n" +
	"\bDiskSpec\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x126\n" +
	"\x04kind\x18\x02 \x01(\x0e2\".unbounded.storage.config.DiskKindR\x04kind\x12\x17\n" +
	"\x04size\x18\x03 \x01(\x04H\x00R\x04size\x88\x01\x01\x12\x17\n" +
	"\x04numa\x18\x04 \x01(\rH\x01R\x04numa\x88\x01\x01\x12$\n" +
	"\vqueue_depth\x18\x05 \x01(\rH\x02R\n" +
	"queueDepth\x88\x01\x01\x12+\n" +
	"\x0fpage_size_bytes\x18\x06 \x01(\x04H\x03R\rpageSizeBytes\x88\x01\x01\x12)\n" +
	"\x10bypass_admission\x18\a \x01(\bR\x0fbypassAdmission\x12?\n" +
	"\x1dskip_recovery_scan_if_no_meta\x18\b \x01(\bR\x18skipRecoveryScanIfNoMetaB\a\n" +
	"\x05_sizeB\a\n" +
	"\x05_numaB\x0e\n" +
	"\f_queue_depthB\x12\n" +
	"\x10_page_size_bytes\"\xf3\x01\n" +
	"\vBackendSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\x04kind\x18\x02 \x01(\x0e2%.unbounded.storage.config.BackendKindR\x04kind\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12*\n" +
	"\x11stripe_size_bytes\x18\x04 \x01(\x04R\x0fstripeSizeBytes\x12)\n" +
	"\x10http_concurrency\x18\x05 \x01(\rR\x0fhttpConcurrency\x12\x1b\n" +
	"\x06bucket\x18\x06 \x01(\tH\x00R\x06bucket\x88\x01\x01B\t\n" +
	"\a_bucket\"\x88\x01\n" +
	"\fFrontendSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\x04kind\x18\x02 \x01(\x0e2&.unbounded.storage.config.FrontendKindR\x04kind\x12\x12\n" +
	"\x04bind\x18\x03 \x01(\tR\x04bind\x12\x18\n" +
	"\abackend\x18\x04 \x01(\tR\abackend*G\n" +
	"\bDiskKind\x12\x12\n" +
	"\x0eDISK_KIND_NVME\x10\x00\x12\x13\n" +
	"\x0fDISK_KIND_BLOCK\x10\x01\x12\x12\n" +
	"\x0eDISK_KIND_FILE\x10\x02*Q\n" +
	"\vBackendKind\x12\x15\n" +
	"\x11BACKEND_KIND_HTTP\x10\x00\x12\x13\n" +
	"\x0fBACKEND_KIND_S3\x10\x01\x12\x16\n" +
	"\x12BACKEND_KIND_AZURE\x10\x02*<\n" +
	"\fFrontendKind\x12\x16\n" +
	"\x12FRONTEND_KIND_HTTP\x10\x00\x12\x14\n" +
	"\x10FRONTEND_KIND_S3\x10\x01B@Z>github.com/Azure/unbounded/api/unbounded-storage;storageconfigb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_config_proto_goTypes = []any{
	(DiskKind)(0),         // 0: unbounded.storage.config.DiskKind
	(BackendKind)(0),      // 1: unbounded.storage.config.BackendKind
	(FrontendKind)(0),     // 2: unbounded.storage.config.FrontendKind
	(*Config)(nil),        // 3: unbounded.storage.config.Config
	(*StartupCfg)(nil),    // 4: unbounded.storage.config.StartupCfg
	(*MetricsCfg)(nil),    // 5: unbounded.storage.config.MetricsCfg
	(*MemoryCfg)(nil),     // 6: unbounded.storage.config.MemoryCfg
	(*FabricCfg)(nil),     // 7: unbounded.storage.config.FabricCfg
	(*TopologyCfg)(nil),   // 8: unbounded.storage.config.TopologyCfg
	(*P2PCfg)(nil),        // 9: unbounded.storage.config.P2pCfg
	(*RoutingPlan)(nil),   // 10: unbounded.storage.config.RoutingPlan
	(*FabricAddress)(nil), // 11: unbounded.storage.config.FabricAddress
	(*PeerSpec)(nil),      // 12: unbounded.storage.config.PeerSpec
	(*DiskSpec)(nil),      // 13: unbounded.storage.config.DiskSpec
	(*BackendSpec)(nil),   // 14: unbounded.storage.config.BackendSpec
	(*FrontendSpec)(nil),  // 15: unbounded.storage.config.FrontendSpec
}
var file_config_proto_depIdxs = []int32{
	9,  // 0: unbounded.storage.config.Config.p2p:type_name -> unbounded.storage.config.P2pCfg
	12, // 1: unbounded.storage.config.Config.peers:type_name -> unbounded.storage.config.PeerSpec
	13, // 2: unbounded.storage.config.Config.disks:type_name -> unbounded.storage.config.DiskSpec
	14, // 3: unbounded.storage.config.Config.backends:type_name -> unbounded.storage.config.BackendSpec
	15, // 4: unbounded.storage.config.Config.frontends:type_name -> unbounded.storage.config.FrontendSpec
	4,  // 5: unbounded.storage.config.Config.startup:type_name -> unbounded.storage.config.StartupCfg
	6,  // 6: unbounded.storage.config.StartupCfg.memory:type_name -> unbounded.storage.config.MemoryCfg
	7,  // 7: unbounded.storage.config.StartupCfg.fabric:type_name -> unbounded.storage.config.FabricCfg
	8,  // 8: unbounded.storage.config.StartupCfg.topology:type_name -> unbounded.storage.config.TopologyCfg
	5,  // 9: unbounded.storage.config.StartupCfg.metrics:type_name -> unbounded.storage.config.MetricsCfg
	10, // 10: unbounded.storage.config.P2pCfg.routing_plan:type_name -> unbounded.storage.config.RoutingPlan
	11, // 11: unbounded.storage.config.PeerSpec.address:type_name -> unbounded.storage.config.FabricAddress
	0,  // 12: unbounded.storage.config.DiskSpec.kind:type_name -> unbounded.storage.config.DiskKind
	1,  // 13: unbounded.storage.config.BackendSpec.kind:type_name -> unbounded.storage.config.BackendKind
	2,  // 14: unbounded.storage.config.FrontendSpec.kind:type_name -> unbounded.storage.config.FrontendKind
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_config_proto_msgTypes[6].OneofWrappers = []any{}
	file_config_proto_msgTypes[7].OneofWrappers = []any{}
	file_config_proto_msgTypes[9].OneofWrappers = []any{}
	file_config_proto_msgTypes[10].OneofWrappers = []any{}
	file_config_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
