#!/usr/bin/env bash
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# gen-storage-mesh-config.sh -- Generate a test unbounded-storage TOML config
# for one node of the current Kubernetes cluster, wiring every other node in as
# a TCP peer (a full peer mesh) using each node's InternalIP.
#
# Usage:
#   hack/scripts/gen-storage-mesh-config.sh [options]
#
# Options:
#       --context NAME       kubeconfig context (defaults to current context)
#   -l, --selector SEL       node label selector passed to kubectl get nodes
#       --local-node NAME    node this config is for (defaults to the first
#                            node by sorted name)
#       --port PORT          fabric / peer TCP port (default 7000)
#       --frontend-port PORT frontend bind port (default 9000)
#       --origin URL         backend origin endpoint
#                            (default http://origin.example.invalid)
#   -h, --help               Show this help and exit

set -euo pipefail

# ── helpers ──────────────────────────────────────────────────────────────────

die() {
	echo "error: $*" >&2
	exit 1
}

usage() {
	# Print the leading "# Usage:" comment block with the "# " prefix stripped.
	# The quit-check runs before the substitution: stripping the "# " leaves a
	# leading space, so testing /^[^#]/ after the substitution would wrongly match
	# every stripped line and quit after the first.
	sed -n '/^# Usage:/,/^[^#]/{ /^[^#]/q; s/^# \{0,1\}//; p }' "$0"
	exit 0
}

require_cmd() {
	command -v "$1" >/dev/null 2>&1 || die "$1 not found. $2"
}

# ── argument parsing ──────────────────────────────────────────────────────────

OPT_CONTEXT=""
OPT_SELECTOR=""
OPT_LOCAL_NODE=""
OPT_PORT="7000"
OPT_FRONTEND_PORT="9000"
OPT_ORIGIN="http://origin.example.invalid"

while [[ $# -gt 0 ]]; do
	case "$1" in
	--context)
		OPT_CONTEXT="$2"
		shift 2
		;;
	-l | --selector)
		OPT_SELECTOR="$2"
		shift 2
		;;
	--local-node)
		OPT_LOCAL_NODE="$2"
		shift 2
		;;
	--port)
		OPT_PORT="$2"
		shift 2
		;;
	--frontend-port)
		OPT_FRONTEND_PORT="$2"
		shift 2
		;;
	--origin)
		OPT_ORIGIN="$2"
		shift 2
		;;
	-h | --help) usage ;;
	*) die "unknown option: $1. Use --help for usage." ;;
	esac
done

# ── preflight checks ──────────────────────────────────────────────────────────

require_cmd kubectl "Install kubectl: https://kubernetes.io/docs/tasks/tools/"

[[ "$OPT_PORT" =~ ^[0-9]+$ ]] || die "--port must be a number (got '$OPT_PORT')."
[[ "$OPT_FRONTEND_PORT" =~ ^[0-9]+$ ]] || die "--frontend-port must be a number (got '$OPT_FRONTEND_PORT')."

# ── kubectl context args ──────────────────────────────────────────────────────

KUBECTL_CTX_ARGS=()
if [[ -n "$OPT_CONTEXT" ]]; then
	KUBECTL_CTX_ARGS=(--context "$OPT_CONTEXT")
fi

KUBECTL_SEL_ARGS=()
if [[ -n "$OPT_SELECTOR" ]]; then
	KUBECTL_SEL_ARGS=(-l "$OPT_SELECTOR")
fi

# ── fetch node name / InternalIP pairs ────────────────────────────────────────

# One "<name> <internal-ip>" line per node. Nodes without an InternalIP emit a
# trailing-space line and are rejected below so a missing address fails loudly
# rather than silently producing a peer with an empty address.
NODE_LINES=$(kubectl "${KUBECTL_CTX_ARGS[@]}" get nodes "${KUBECTL_SEL_ARGS[@]}" \
	-o jsonpath='{range .items[*]}{.metadata.name}{" "}{range .status.addresses[?(@.type=="InternalIP")]}{.address}{end}{"\n"}{end}' |
	grep -v '^[[:space:]]*$' |
	sort)

[[ -z "$NODE_LINES" ]] && die "no nodes found in the current cluster."

# Parse into parallel arrays of names and IPs, assigning ids 1..N by sort order.
NAMES=()
IPS=()
while IFS=' ' read -r name ip; do
	[[ -z "$name" ]] && continue
	[[ -z "$ip" ]] && die "node '$name' has no InternalIP address."
	NAMES+=("$name")
	IPS+=("$ip")
done <<<"$NODE_LINES"

NODE_COUNT="${#NAMES[@]}"

# ── pick the local node ───────────────────────────────────────────────────────

LOCAL_IDX=-1
if [[ -n "$OPT_LOCAL_NODE" ]]; then
	for i in "${!NAMES[@]}"; do
		if [[ "${NAMES[$i]}" == "$OPT_LOCAL_NODE" ]]; then
			LOCAL_IDX="$i"
			break
		fi
	done
	[[ "$LOCAL_IDX" -lt 0 ]] && die "node '$OPT_LOCAL_NODE' not found among the $NODE_COUNT selected node(s)."
else
	LOCAL_IDX=0
fi

LOCAL_NAME="${NAMES[$LOCAL_IDX]}"
LOCAL_IP="${IPS[$LOCAL_IDX]}"
LOCAL_ID=$((LOCAL_IDX + 1))

# ── emit the config to stdout ─────────────────────────────────────────────────

# Sample sizing for the file-backed test disk and origin backend stripe.
DISK_SIZE=$((256 * 1024 * 1024)) # 256 MiB
STRIPE_SIZE=$((4 * 1024 * 1024)) # 4 MiB

cat <<EOF
# Generated by hack/scripts/gen-storage-mesh-config.sh -- test config, not for
# production. This file is the unbounded-storage config for node:
#
#   name:        $LOCAL_NAME
#   internal ip: $LOCAL_IP
#   node id:     $LOCAL_ID  (of $NODE_COUNT nodes; ids assigned by sorted name)
#
# Every other node in the cluster is wired in below as a TCP peer. Regenerate
# the peer config for a different node with --local-node <name>.

[p2p]
local_node_id = $LOCAL_ID
EOF

# Peers: every node except the local one.
for i in "${!NAMES[@]}"; do
	[[ "$i" -eq "$LOCAL_IDX" ]] && continue
	peer_id=$((i + 1))
	cat <<EOF

[[peers]]
# peer node: ${NAMES[$i]}
id = $peer_id
# transport: 0 = tcp, 1 = rdma.
transport = 0
address = "${IPS[$i]}:$OPT_PORT"
EOF
done

cat <<EOF

[[disks]]
path = "/tmp/unbounded-storage-${LOCAL_NAME}.disk"
# kind: 0 = nvme, 1 = block, 2 = file.
kind = 2
size = $DISK_SIZE
page_size_bytes = 4096
bypass_admission = true
skip_recovery_scan_if_no_meta = true

[[backends]]
id = "origin"
# kind: 0 = http, 1 = s3.
kind = 0
endpoint = "$OPT_ORIGIN"
stripe_size_bytes = $STRIPE_SIZE

[[frontends]]
id = "fe"
# kind: 0 = http, 1 = s3.
kind = 0
bind = "0.0.0.0:$OPT_FRONTEND_PORT"
backend = "origin"

[startup.fabric]
listen_addr = "0.0.0.0:$OPT_PORT"
EOF
