#!/usr/bin/env bash
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
#
# net-ebpf-generate.sh -- regenerate bpf/vmlinux.h from the pinned Ubuntu
# kernel package (bpf/btf-kernel-pin) and bpf/btf-kernel-pin-hashes.
#
# Pipeline:
#  1. Read package_url from bpf/btf-kernel-pin.
#  2. Download the .deb and record its sha256.
#  3. Extract vmlinuz, decompress to ELF vmlinux.
#  4. Dump full BTF (binary + C) via bpftool.
#  5. Probe-compile bpf/unbounded_encap.c against the full vmlinux.h
#     to produce an object file whose CO-RE relocations list the types
#     we actually use.
#  6. Run `bpftool gen min_core_btf` to extract a minimal BTF containing
#     only the types referenced by our probe object.
#  7. Dump the minimal BTF as C, prepend a provenance header that embeds
#     bpf/btf-kernel-pin verbatim, and write bpf/vmlinux.h.
#  8. Compute the sha256 of the new bpf/vmlinux.h.
#  9. Regenerate bpf/btf-kernel-pin-hashes with both sha256s.
# 10. Run `go generate ./internal/net/ebpf/...` to refresh bpf2go bindings.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
pin_file="$repo_root/bpf/btf-kernel-pin"
hashes_file="$repo_root/bpf/btf-kernel-pin-hashes"
vmlinux_h="$repo_root/bpf/vmlinux.h"
bpf_src="$repo_root/bpf/unbounded_encap.c"
extract="$repo_root/hack/scripts/extract-vmlinux.py"

: "${BPFTOOL:=bpftool}"
: "${CLANG:=clang-18}"
: "${CURL:=curl}"

for tool in "$BPFTOOL" "$CLANG" "$CURL" dpkg-deb sha256sum; do
	if ! command -v "$tool" >/dev/null 2>&1; then
		echo "net-ebpf-generate: required tool not found in PATH: $tool" >&2
		exit 1
	fi
done

if [[ ! -r "$pin_file" ]]; then
	echo "net-ebpf-generate: missing $pin_file" >&2
	exit 1
fi

# Extract the package_url= line from the pin (ignoring # comments).
package_url=""
while IFS= read -r line; do
	case "$line" in
		\#*|"") continue ;;
		package_url=*) package_url="${line#package_url=}" ;;
	esac
done < "$pin_file"

if [[ -z "$package_url" ]]; then
	echo "net-ebpf-generate: $pin_file is missing 'package_url=' line" >&2
	exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "==> downloading $package_url"
"$CURL" -fsSL "$package_url" -o "$tmp/pkg.deb"

package_sha256="$(sha256sum "$tmp/pkg.deb" | awk '{print $1}')"
echo "    package sha256: $package_sha256"

echo "==> extracting kernel image"
mkdir -p "$tmp/extracted"
dpkg-deb -x "$tmp/pkg.deb" "$tmp/extracted"
vmlinuz="$(find "$tmp/extracted" -maxdepth 4 -name 'vmlinuz-*' -type f | head -n 1)"
if [[ -z "$vmlinuz" ]]; then
	echo "net-ebpf-generate: no vmlinuz-* file inside $package_url" >&2
	exit 1
fi
echo "    found $vmlinuz"

echo "==> decompressing vmlinuz to ELF"
"$extract" "$vmlinuz" > "$tmp/vmlinux"

echo "==> dumping full BTF"
"$BPFTOOL" btf dump file "$tmp/vmlinux" format raw > /dev/null  # validates BTF is present
"$BPFTOOL" btf dump file "$tmp/vmlinux" format c > "$tmp/vmlinux.h"

# The probe compile produces an object whose CO-RE relocations list every
# type / field / size we touch. min_core_btf walks the relocations to compute
# the closure of types we actually need.
#
# We copy the source to $tmp and compile from there so that #include "vmlinux.h"
# picks up the full BTF dump in $tmp, not the (possibly stale, minified) header
# committed under bpf/.
#
# -Wno-missing-declarations: the full BTF→C dump from bpftool emits bare
# forward declarations like "struct ns_tree;" inside parent struct bodies for
# anonymous nested types that BTF cannot express otherwise. They are no-op
# declarations and clang warns about them; the warnings are dumper artifacts,
# not actual problems in the kernel headers or our source.
echo "==> probe-compiling bpf/unbounded_encap.c"
cp "$bpf_src" "$tmp/unbounded_encap.c"
"$CLANG" -O2 -g -Wall -Wno-missing-declarations \
	-target bpf \
	-I"$tmp" \
	-c "$tmp/unbounded_encap.c" \
	-o "$tmp/probe.o"

echo "==> minifying BTF for committed header"
# bpftool gen min_core_btf accepts a vmlinux ELF (with BTF section) or a
# raw BTF blob. Use the ELF directly.
"$BPFTOOL" gen min_core_btf "$tmp/vmlinux" "$tmp/min.btf" "$tmp/probe.o"
"$BPFTOOL" btf dump file "$tmp/min.btf" format c > "$tmp/vmlinux-min.h"

echo "==> assembling bpf/vmlinux.h with provenance header"
{
	echo "// Code generated by \`make net-ebpf-generate\`. DO NOT EDIT."
	echo "//"
	echo "// Generated from the kernel pin in bpf/btf-kernel-pin:"
	echo "//"
	# Embed bpf/btf-kernel-pin verbatim (excluding its # comments) so CI can
	# diff this block against the pin file without parsing.
	while IFS= read -r line; do
		case "$line" in
			\#*|"") continue ;;
			*) printf '// %s\n' "$line" ;;
		esac
	done < "$pin_file"
	echo "//"
	echo "// SHA256 hashes are tracked in bpf/btf-kernel-pin-hashes."
	echo "// To bump the pin, edit bpf/btf-kernel-pin and run \`make net-ebpf-generate\`."
	echo
	# Standard kernel integer typedefs plus a few network-checksum typedefs.
	# libbpf's bpf_helper_defs.h depends on all of these; the minified
	# vmlinux.h below only emits the subset reachable from the retained
	# struct fields, so we declare them all up front and strip duplicate
	# definitions from the minified header.
	cat <<-'EOF'
		typedef unsigned char      __u8;
		typedef unsigned short     __u16;
		typedef unsigned int       __u32;
		typedef unsigned long long __u64;
		typedef signed char        __s8;
		typedef short              __s16;
		typedef int                __s32;
		typedef long long          __s64;
		typedef __u16              __sum16;
		typedef __u32              __wsum;

	EOF
	# Strip the same typedef declarations from the minified header to avoid
	# redefinition errors.
	sed -E '
		/^typedef unsigned char __u8;$/d
		/^typedef short unsigned int __u16;$/d
		/^typedef unsigned int __u32;$/d
		/^typedef unsigned long long __u64;$/d
		/^typedef signed char __s8;$/d
		/^typedef short __s16;$/d
		/^typedef int __s32;$/d
		/^typedef long long __s64;$/d
		/^typedef __u16 __sum16;$/d
		/^typedef __u32 __wsum;$/d
	' "$tmp/vmlinux-min.h"
} > "$vmlinux_h"

vmlinux_h_sha256="$(sha256sum "$vmlinux_h" | awk '{print $1}')"
echo "    bpf/vmlinux.h sha256: $vmlinux_h_sha256"

echo "==> writing bpf/btf-kernel-pin-hashes"
{
	echo "# Code generated by \`make net-ebpf-generate\`. DO NOT EDIT."
	echo "# SHA256 hashes for the kernel package pinned in bpf/btf-kernel-pin"
	echo "# and the minified BTF header it produces."
	echo "package_sha256=$package_sha256"
	echo "vmlinux_h_sha256=$vmlinux_h_sha256"
} > "$hashes_file"

echo "==> running go generate"
(cd "$repo_root" && go generate ./internal/net/ebpf/...)

echo
echo "Regenerated:"
echo "  $vmlinux_h"
echo "  $hashes_file"
echo "  $repo_root/internal/net/ebpf/unboundedencap_bpfel.{go,o}"
