[package]
name = "unbounded-s3"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
unbounded-storage = { path = "../unbounded-storage" }
tokio             = { version = "1", features = ["rt-multi-thread", "rt", "macros", "signal", "sync", "net", "io-util"] }
axum              = "0.7"

bytes             = "1"
futures           = "0.3"
serde             = { version = "1", features = ["derive"] }
serde_yaml        = "0.9"
hex               = "0.4"
quick-xml         = { version = "0.36", features = ["serialize"] }
tracing           = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
time              = { version = "0.3", features = ["parsing", "formatting", "macros"] }

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["stream"] }
tempfile = "3"
tower    = "0.5"
