// Gantry coordination RPCs (libp2p, length-prefixed protobuf).
//
// Carried over libp2p stream protocol ID `/gantry/coord/1.1.0` as described in
// detailed-design.md §4.4. One stream per request/response pair; the stream
// is closed after the response is written. Forward-compat policy: additive
// changes bump the minor (`/gantry/coord/1.1.0`), breaking changes bump the
// major (`/gantry/coord/2.0.0`).
//
// gRPC is intentionally avoided - `go-msgio` length-delimited framing is
// sufficient and avoids HTTP-over-libp2p complexity.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: coord.proto

package coordv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FailureClass classifies the cause of a terminal origin pull failure.
// See detailed-design.md §5.8 for semantics and cluster-wide trust rules.
type FailureClass int32

const (
	FailureClass_FAILURE_CLASS_UNSPECIFIED  FailureClass = 0
	FailureClass_FAILURE_CLASS_AUTH         FailureClass = 1 // 401 / 403 from origin
	FailureClass_FAILURE_CLASS_NOT_FOUND    FailureClass = 2 // 404 from origin
	FailureClass_FAILURE_CLASS_RATE_LIMITED FailureClass = 3 // 429 from origin
	FailureClass_FAILURE_CLASS_TRANSIENT    FailureClass = 4 // connection / timeout / DNS / 5xx
)

// Enum value maps for FailureClass.
var (
	FailureClass_name = map[int32]string{
		0: "FAILURE_CLASS_UNSPECIFIED",
		1: "FAILURE_CLASS_AUTH",
		2: "FAILURE_CLASS_NOT_FOUND",
		3: "FAILURE_CLASS_RATE_LIMITED",
		4: "FAILURE_CLASS_TRANSIENT",
	}
	FailureClass_value = map[string]int32{
		"FAILURE_CLASS_UNSPECIFIED":  0,
		"FAILURE_CLASS_AUTH":         1,
		"FAILURE_CLASS_NOT_FOUND":    2,
		"FAILURE_CLASS_RATE_LIMITED": 3,
		"FAILURE_CLASS_TRANSIENT":    4,
	}
)

func (x FailureClass) Enum() *FailureClass {
	p := new(FailureClass)
	*p = x
	return p
}

func (x FailureClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureClass) Descriptor() protoreflect.EnumDescriptor {
	return file_coord_proto_enumTypes[0].Descriptor()
}

func (FailureClass) Type() protoreflect.EnumType {
	return &file_coord_proto_enumTypes[0]
}

func (x FailureClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureClass.Descriptor instead.
func (FailureClass) EnumDescriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{0}
}

// Kind discriminates the OCI Distribution Spec URL family the puller
// should target at the upstream registry:
//
//	/v2/<repo>/blobs/<digest>      (KIND_BLOB; image-config blobs are
//	                                KIND_CONFIG, all other blobs are
//	                                KIND_BLOB)
//	/v2/<repo>/manifests/<digest>  (KIND_MANIFEST)
//	/v2/<repo>/blobs/<digest>      (KIND_CONFIG; per the OCI Distribution
//	                                Spec the image-config blob lives in
//	                                the same /blobs/ URL family but is
//	                                typed separately so per-kind metrics
//	                                ("manifest | config | layer") agree
//	                                end-to-end across the please_pull
//	                                wire boundary)
//
// Missing or unknown Kind is rejected before any origin work is admitted.
type PleasePullRequest_Kind int32

const (
	PleasePullRequest_KIND_UNSPECIFIED PleasePullRequest_Kind = 0
	PleasePullRequest_KIND_BLOB        PleasePullRequest_Kind = 1
	PleasePullRequest_KIND_MANIFEST    PleasePullRequest_Kind = 2
	PleasePullRequest_KIND_CONFIG      PleasePullRequest_Kind = 3
)

// Enum value maps for PleasePullRequest_Kind.
var (
	PleasePullRequest_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_BLOB",
		2: "KIND_MANIFEST",
		3: "KIND_CONFIG",
	}
	PleasePullRequest_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_BLOB":        1,
		"KIND_MANIFEST":    2,
		"KIND_CONFIG":      3,
	}
)

func (x PleasePullRequest_Kind) Enum() *PleasePullRequest_Kind {
	p := new(PleasePullRequest_Kind)
	*p = x
	return p
}

func (x PleasePullRequest_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PleasePullRequest_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_coord_proto_enumTypes[1].Descriptor()
}

func (PleasePullRequest_Kind) Type() protoreflect.EnumType {
	return &file_coord_proto_enumTypes[1]
}

func (x PleasePullRequest_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PleasePullRequest_Kind.Descriptor instead.
func (PleasePullRequest_Kind) EnumDescriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{1, 0}
}

type PleasePullResponse_Result_Outcome int32

const (
	PleasePullResponse_Result_OUTCOME_UNSPECIFIED     PleasePullResponse_Result_Outcome = 0
	PleasePullResponse_Result_OUTCOME_ALREADY_PULLING PleasePullResponse_Result_Outcome = 1
	PleasePullResponse_Result_OUTCOME_STARTED         PleasePullResponse_Result_Outcome = 2
	PleasePullResponse_Result_OUTCOME_RECENTLY_FAILED PleasePullResponse_Result_Outcome = 3
	PleasePullResponse_Result_OUTCOME_STALE_CHAIR     PleasePullResponse_Result_Outcome = 4
)

// Enum value maps for PleasePullResponse_Result_Outcome.
var (
	PleasePullResponse_Result_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_ALREADY_PULLING",
		2: "OUTCOME_STARTED",
		3: "OUTCOME_RECENTLY_FAILED",
		4: "OUTCOME_STALE_CHAIR",
	}
	PleasePullResponse_Result_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":     0,
		"OUTCOME_ALREADY_PULLING": 1,
		"OUTCOME_STARTED":         2,
		"OUTCOME_RECENTLY_FAILED": 3,
		"OUTCOME_STALE_CHAIR":     4,
	}
)

func (x PleasePullResponse_Result_Outcome) Enum() *PleasePullResponse_Result_Outcome {
	p := new(PleasePullResponse_Result_Outcome)
	*p = x
	return p
}

func (x PleasePullResponse_Result_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PleasePullResponse_Result_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_coord_proto_enumTypes[2].Descriptor()
}

func (PleasePullResponse_Result_Outcome) Type() protoreflect.EnumType {
	return &file_coord_proto_enumTypes[2]
}

func (x PleasePullResponse_Result_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PleasePullResponse_Result_Outcome.Descriptor instead.
func (PleasePullResponse_Result_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{5, 0, 0}
}

// Envelope is the single message kind sent over `/gantry/coord/1.1.0`.
// Receivers dispatch on the `msg` oneof.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Envelope_ChairOfferRequest
	//	*Envelope_ChairOfferResponse
	Msg           isEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_coord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMsg() isEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Envelope) GetChairOfferRequest() *ChairOfferRequest {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_ChairOfferRequest); ok {
			return x.ChairOfferRequest
		}
	}
	return nil
}

func (x *Envelope) GetChairOfferResponse() *ChairOfferResponse {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_ChairOfferResponse); ok {
			return x.ChairOfferResponse
		}
	}
	return nil
}

type isEnvelope_Msg interface {
	isEnvelope_Msg()
}

type Envelope_ChairOfferRequest struct {
	ChairOfferRequest *ChairOfferRequest `protobuf:"bytes,5,opt,name=chair_offer_request,json=chairOfferRequest,proto3,oneof"`
}

type Envelope_ChairOfferResponse struct {
	ChairOfferResponse *ChairOfferResponse `protobuf:"bytes,6,opt,name=chair_offer_response,json=chairOfferResponse,proto3,oneof"`
}

func (*Envelope_ChairOfferRequest) isEnvelope_Msg() {}

func (*Envelope_ChairOfferResponse) isEnvelope_Msg() {}

// PleasePullRequest is carried only by the HTTPS chair endpoint, not Envelope.
type PleasePullRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batched (§5.2a). All digests in a single batch MUST share
	// `upstream_registry`, `repository`, AND `kind`. Mixed-kind batches
	// require separate calls.
	Digests          []string               `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	UpstreamRegistry string                 `protobuf:"bytes,2,opt,name=upstream_registry,json=upstreamRegistry,proto3" json:"upstream_registry,omitempty"` // e.g. "registry.example.com"
	Repository       string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`                                     // e.g. "library/nginx"
	Kind             PleasePullRequest_Kind `protobuf:"varint,4,opt,name=kind,proto3,enum=gantry.coord.v1.PleasePullRequest_Kind" json:"kind,omitempty"`
	// Basic or Bearer authorization delegated by the requesting node. The
	// recipient uses it only if it must contact origin for this request; local
	// cache hits ignore it. It MUST NOT be persisted, logged, or cached.
	Authorization string `protobuf:"bytes,5,opt,name=authorization,proto3" json:"authorization,omitempty"`
	// Required. The server validates the assignment before accepting origin work.
	ChairAssignment *ChairAssignment `protobuf:"bytes,6,opt,name=chair_assignment,json=chairAssignment,proto3" json:"chair_assignment,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PleasePullRequest) Reset() {
	*x = PleasePullRequest{}
	mi := &file_coord_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PleasePullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PleasePullRequest) ProtoMessage() {}

func (x *PleasePullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PleasePullRequest.ProtoReflect.Descriptor instead.
func (*PleasePullRequest) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{1}
}

func (x *PleasePullRequest) GetDigests() []string {
	if x != nil {
		return x.Digests
	}
	return nil
}

func (x *PleasePullRequest) GetUpstreamRegistry() string {
	if x != nil {
		return x.UpstreamRegistry
	}
	return ""
}

func (x *PleasePullRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *PleasePullRequest) GetKind() PleasePullRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return PleasePullRequest_KIND_UNSPECIFIED
}

func (x *PleasePullRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *PleasePullRequest) GetChairAssignment() *ChairAssignment {
	if x != nil {
		return x.ChairAssignment
	}
	return nil
}

type ChairAssignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChairId         uint64                 `protobuf:"varint,1,opt,name=chair_id,json=chairId,proto3" json:"chair_id,omitempty"`
	Generation      int64                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	AssignmentEpoch int64                  `protobuf:"varint,3,opt,name=assignment_epoch,json=assignmentEpoch,proto3" json:"assignment_epoch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChairAssignment) Reset() {
	*x = ChairAssignment{}
	mi := &file_coord_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChairAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChairAssignment) ProtoMessage() {}

func (x *ChairAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChairAssignment.ProtoReflect.Descriptor instead.
func (*ChairAssignment) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{2}
}

func (x *ChairAssignment) GetChairId() uint64 {
	if x != nil {
		return x.ChairId
	}
	return 0
}

func (x *ChairAssignment) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ChairAssignment) GetAssignmentEpoch() int64 {
	if x != nil {
		return x.AssignmentEpoch
	}
	return 0
}

type ChairOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *ChairAssignment       `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChairOfferRequest) Reset() {
	*x = ChairOfferRequest{}
	mi := &file_coord_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChairOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChairOfferRequest) ProtoMessage() {}

func (x *ChairOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChairOfferRequest.ProtoReflect.Descriptor instead.
func (*ChairOfferRequest) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{3}
}

func (x *ChairOfferRequest) GetAssignment() *ChairAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type ChairOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	P2PAddrs      []string               `protobuf:"bytes,3,rep,name=p2p_addrs,json=p2pAddrs,proto3" json:"p2p_addrs,omitempty"`
	TransferAddr  string                 `protobuf:"bytes,4,opt,name=transfer_addr,json=transferAddr,proto3" json:"transfer_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChairOfferResponse) Reset() {
	*x = ChairOfferResponse{}
	mi := &file_coord_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChairOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChairOfferResponse) ProtoMessage() {}

func (x *ChairOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChairOfferResponse.ProtoReflect.Descriptor instead.
func (*ChairOfferResponse) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{4}
}

func (x *ChairOfferResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ChairOfferResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ChairOfferResponse) GetP2PAddrs() []string {
	if x != nil {
		return x.P2PAddrs
	}
	return nil
}

func (x *ChairOfferResponse) GetTransferAddr() string {
	if x != nil {
		return x.TransferAddr
	}
	return ""
}

// PleasePullResponse reports the per-digest outcome of a `please_pull` request.
type PleasePullResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Results       []*PleasePullResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PleasePullResponse) Reset() {
	*x = PleasePullResponse{}
	mi := &file_coord_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PleasePullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PleasePullResponse) ProtoMessage() {}

func (x *PleasePullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PleasePullResponse.ProtoReflect.Descriptor instead.
func (*PleasePullResponse) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{5}
}

func (x *PleasePullResponse) GetResults() []*PleasePullResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type PleasePullResponse_Result struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Digest        string                            `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Outcome       PleasePullResponse_Result_Outcome `protobuf:"varint,2,opt,name=outcome,proto3,enum=gantry.coord.v1.PleasePullResponse_Result_Outcome" json:"outcome,omitempty"`
	StartedAt     *timestamppb.Timestamp            `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CooldownUntil *timestamppb.Timestamp            `protobuf:"bytes,4,opt,name=cooldown_until,json=cooldownUntil,proto3" json:"cooldown_until,omitempty"`
	FailureClass  FailureClass                      `protobuf:"varint,5,opt,name=failure_class,json=failureClass,proto3,enum=gantry.coord.v1.FailureClass" json:"failure_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PleasePullResponse_Result) Reset() {
	*x = PleasePullResponse_Result{}
	mi := &file_coord_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PleasePullResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PleasePullResponse_Result) ProtoMessage() {}

func (x *PleasePullResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PleasePullResponse_Result.ProtoReflect.Descriptor instead.
func (*PleasePullResponse_Result) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{5, 0}
}

func (x *PleasePullResponse_Result) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PleasePullResponse_Result) GetOutcome() PleasePullResponse_Result_Outcome {
	if x != nil {
		return x.Outcome
	}
	return PleasePullResponse_Result_OUTCOME_UNSPECIFIED
}

func (x *PleasePullResponse_Result) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PleasePullResponse_Result) GetCooldownUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.CooldownUntil
	}
	return nil
}

func (x *PleasePullResponse_Result) GetFailureClass() FailureClass {
	if x != nil {
		return x.FailureClass
	}
	return FailureClass_FAILURE_CLASS_UNSPECIFIED
}

var File_coord_proto protoreflect.FileDescriptor

const file_coord_proto_rawDesc = "" +
	"\n" +
	"\vcoord.proto\x12\x0fgantry.coord.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x02\n" +
	"\bEnvelope\x12T\n" +
	"\x13chair_offer_request\x18\x05 \x01(\v2\".gantry.coord.v1.ChairOfferRequestH\x00R\x11chairOfferRequest\x12W\n" +
	"\x14chair_offer_response\x18\x06 \x01(\v2#.gantry.coord.v1.ChairOfferResponseH\x00R\x12chairOfferResponseB\x05\n" +
	"\x03msgJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05R\x13pull_intent_requestR\x14pull_intent_responseR\x13please_pull_requestR\x14please_pull_response\"\xfb\x02\n" +
	"\x11PleasePullRequest\x12\x18\n" +
	"\adigests\x18\x01 \x03(\tR\adigests\x12+\n" +
	"\x11upstream_registry\x18\x02 \x01(\tR\x10upstreamRegistry\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12;\n" +
	"\x04kind\x18\x04 \x01(\x0e2'.gantry.coord.v1.PleasePullRequest.KindR\x04kind\x12$\n" +
	"\rauthorization\x18\x05 \x01(\tR\rauthorization\x12K\n" +
	"\x10chair_assignment\x18\x06 \x01(\v2 .gantry.coord.v1.ChairAssignmentR\x0fchairAssignment\"O\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tKIND_BLOB\x10\x01\x12\x11\n" +
	"\rKIND_MANIFEST\x10\x02\x12\x0f\n" +
	"\vKIND_CONFIG\x10\x03\"w\n" +
	"\x0fChairAssignment\x12\x19\n" +
	"\bchair_id\x18\x01 \x01(\x04R\achairId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x03R\n" +
	"generation\x12)\n" +
	"\x10assignment_epoch\x18\x03 \x01(\x03R\x0fassignmentEpoch\"U\n" +
	"\x11ChairOfferRequest\x12@\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2 .gantry.coord.v1.ChairAssignmentR\n" +
	"assignment\"\x8b\x01\n" +
	"\x12ChairOfferResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1b\n" +
	"\tp2p_addrs\x18\x03 \x03(\tR\bp2pAddrs\x12#\n" +
	"\rtransfer_addr\x18\x04 \x01(\tR\ftransferAddr\"\x9a\x04\n" +
	"\x12PleasePullResponse\x12D\n" +
	"\aresults\x18\x01 \x03(\v2*.gantry.coord.v1.PleasePullResponse.ResultR\aresults\x1a\xbd\x03\n" +
	"\x06Result\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12L\n" +
	"\aoutcome\x18\x02 \x01(\x0e22.gantry.coord.v1.PleasePullResponse.Result.OutcomeR\aoutcome\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12A\n" +
	"\x0ecooldown_until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rcooldownUntil\x12B\n" +
	"\rfailure_class\x18\x05 \x01(\x0e2\x1d.gantry.coord.v1.FailureClassR\ffailureClass\"\x8a\x01\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OUTCOME_ALREADY_PULLING\x10\x01\x12\x13\n" +
	"\x0fOUTCOME_STARTED\x10\x02\x12\x1b\n" +
	"\x17OUTCOME_RECENTLY_FAILED\x10\x03\x12\x17\n" +
	"\x13OUTCOME_STALE_CHAIR\x10\x04*\x9f\x01\n" +
	"\fFailureClass\x12\x1d\n" +
	"\x19FAILURE_CLASS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FAILURE_CLASS_AUTH\x10\x01\x12\x1b\n" +
	"\x17FAILURE_CLASS_NOT_FOUND\x10\x02\x12\x1e\n" +
	"\x1aFAILURE_CLASS_RATE_LIMITED\x10\x03\x12\x1b\n" +
	"\x17FAILURE_CLASS_TRANSIENT\x10\x04BCZAgithub.com/Azure/unbounded/internal/gantry/proto/coord/v1;coordv1b\x06proto3"

var (
	file_coord_proto_rawDescOnce sync.Once
	file_coord_proto_rawDescData []byte
)

func file_coord_proto_rawDescGZIP() []byte {
	file_coord_proto_rawDescOnce.Do(func() {
		file_coord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coord_proto_rawDesc), len(file_coord_proto_rawDesc)))
	})
	return file_coord_proto_rawDescData
}

var file_coord_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_coord_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_coord_proto_goTypes = []any{
	(FailureClass)(0),                      // 0: gantry.coord.v1.FailureClass
	(PleasePullRequest_Kind)(0),            // 1: gantry.coord.v1.PleasePullRequest.Kind
	(PleasePullResponse_Result_Outcome)(0), // 2: gantry.coord.v1.PleasePullResponse.Result.Outcome
	(*Envelope)(nil),                       // 3: gantry.coord.v1.Envelope
	(*PleasePullRequest)(nil),              // 4: gantry.coord.v1.PleasePullRequest
	(*ChairAssignment)(nil),                // 5: gantry.coord.v1.ChairAssignment
	(*ChairOfferRequest)(nil),              // 6: gantry.coord.v1.ChairOfferRequest
	(*ChairOfferResponse)(nil),             // 7: gantry.coord.v1.ChairOfferResponse
	(*PleasePullResponse)(nil),             // 8: gantry.coord.v1.PleasePullResponse
	(*PleasePullResponse_Result)(nil),      // 9: gantry.coord.v1.PleasePullResponse.Result
	(*timestamppb.Timestamp)(nil),          // 10: google.protobuf.Timestamp
}
var file_coord_proto_depIdxs = []int32{
	6,  // 0: gantry.coord.v1.Envelope.chair_offer_request:type_name -> gantry.coord.v1.ChairOfferRequest
	7,  // 1: gantry.coord.v1.Envelope.chair_offer_response:type_name -> gantry.coord.v1.ChairOfferResponse
	1,  // 2: gantry.coord.v1.PleasePullRequest.kind:type_name -> gantry.coord.v1.PleasePullRequest.Kind
	5,  // 3: gantry.coord.v1.PleasePullRequest.chair_assignment:type_name -> gantry.coord.v1.ChairAssignment
	5,  // 4: gantry.coord.v1.ChairOfferRequest.assignment:type_name -> gantry.coord.v1.ChairAssignment
	9,  // 5: gantry.coord.v1.PleasePullResponse.results:type_name -> gantry.coord.v1.PleasePullResponse.Result
	2,  // 6: gantry.coord.v1.PleasePullResponse.Result.outcome:type_name -> gantry.coord.v1.PleasePullResponse.Result.Outcome
	10, // 7: gantry.coord.v1.PleasePullResponse.Result.started_at:type_name -> google.protobuf.Timestamp
	10, // 8: gantry.coord.v1.PleasePullResponse.Result.cooldown_until:type_name -> google.protobuf.Timestamp
	0,  // 9: gantry.coord.v1.PleasePullResponse.Result.failure_class:type_name -> gantry.coord.v1.FailureClass
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_coord_proto_init() }
func file_coord_proto_init() {
	if File_coord_proto != nil {
		return
	}
	file_coord_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_ChairOfferRequest)(nil),
		(*Envelope_ChairOfferResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coord_proto_rawDesc), len(file_coord_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coord_proto_goTypes,
		DependencyIndexes: file_coord_proto_depIdxs,
		EnumInfos:         file_coord_proto_enumTypes,
		MessageInfos:      file_coord_proto_msgTypes,
	}.Build()
	File_coord_proto = out.File
	file_coord_proto_goTypes = nil
	file_coord_proto_depIdxs = nil
}
