# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Inventory

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  CONTAINER_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  inventory:
    name: Build, Scan, and Push Inventory
    runs-on: ubuntu-latest
    steps:
      - name: Normalize container registry
        run: echo "CONTAINER_REGISTRY=${CONTAINER_REGISTRY,,}" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Build all inventory binaries
        run: make inventory-all

      - name: Build all inventory container images
        run: make image-inventory-all-local CONTAINER_ENGINE=docker

      - name: Vulnerability check
        run: make vulncheck

      - name: Log in to ghcr.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push all inventory container images
        run: make image-inventory-all-push CONTAINER_ENGINE=docker
