// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/net/status/proto/status.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeStatusMessage wraps all node-to-controller status messages.
type NodeStatusMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "node_status_full" or "node_status_delta"
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	BaseRevision  uint64                 `protobuf:"varint,3,opt,name=base_revision,json=baseRevision,proto3" json:"base_revision,omitempty"`
	Status        *NodeStatusFull        `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // set for full updates
	Delta         *NodeStatusDelta       `protobuf:"bytes,5,opt,name=delta,proto3" json:"delta,omitempty"`   // set for delta updates
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusMessage) Reset() {
	*x = NodeStatusMessage{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusMessage) ProtoMessage() {}

func (x *NodeStatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusMessage.ProtoReflect.Descriptor instead.
func (*NodeStatusMessage) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{0}
}

func (x *NodeStatusMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeStatusMessage) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeStatusMessage) GetBaseRevision() uint64 {
	if x != nil {
		return x.BaseRevision
	}
	return 0
}

func (x *NodeStatusMessage) GetStatus() *NodeStatusFull {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *NodeStatusMessage) GetDelta() *NodeStatusDelta {
	if x != nil {
		return x.Delta
	}
	return nil
}

// NodeStatusAck is the acknowledgment returned by the controller for push updates.
type NodeStatusAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok" or "resync_required"
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusAck) Reset() {
	*x = NodeStatusAck{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusAck) ProtoMessage() {}

func (x *NodeStatusAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusAck.ProtoReflect.Descriptor instead.
func (*NodeStatusAck) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{1}
}

func (x *NodeStatusAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeStatusAck) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *NodeStatusAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// NodeStatusFull mirrors the complete NodeStatusResponse payload.
type NodeStatusFull struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNs    int64                  `protobuf:"varint,1,opt,name=timestamp_unix_ns,json=timestampUnixNs,proto3" json:"timestamp_unix_ns,omitempty"`
	NodeInfo           *NodeInfo              `protobuf:"bytes,2,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	Peers              []*PeerStatus          `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	RoutingTable       *RoutingTableInfo      `protobuf:"bytes,4,opt,name=routing_table,json=routingTable,proto3" json:"routing_table,omitempty"`
	HealthCheck        *HealthCheckStatus     `protobuf:"bytes,5,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	NodeErrors         []*NodeError           `protobuf:"bytes,6,rep,name=node_errors,json=nodeErrors,proto3" json:"node_errors,omitempty"`
	FetchError         string                 `protobuf:"bytes,7,opt,name=fetch_error,json=fetchError,proto3" json:"fetch_error,omitempty"`
	LastPushTimeUnixNs int64                  `protobuf:"varint,8,opt,name=last_push_time_unix_ns,json=lastPushTimeUnixNs,proto3" json:"last_push_time_unix_ns,omitempty"` // 0 means unset
	StatusSource       string                 `protobuf:"bytes,9,opt,name=status_source,json=statusSource,proto3" json:"status_source,omitempty"`
	NodePodInfo        *NodePodInfo           `protobuf:"bytes,10,opt,name=node_pod_info,json=nodePodInfo,proto3" json:"node_pod_info,omitempty"`
	BpfEntries         []*BpfEntry            `protobuf:"bytes,11,rep,name=bpf_entries,json=bpfEntries,proto3" json:"bpf_entries,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeStatusFull) Reset() {
	*x = NodeStatusFull{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusFull) ProtoMessage() {}

func (x *NodeStatusFull) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusFull.ProtoReflect.Descriptor instead.
func (*NodeStatusFull) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{2}
}

func (x *NodeStatusFull) GetTimestampUnixNs() int64 {
	if x != nil {
		return x.TimestampUnixNs
	}
	return 0
}

func (x *NodeStatusFull) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *NodeStatusFull) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *NodeStatusFull) GetRoutingTable() *RoutingTableInfo {
	if x != nil {
		return x.RoutingTable
	}
	return nil
}

func (x *NodeStatusFull) GetHealthCheck() *HealthCheckStatus {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *NodeStatusFull) GetNodeErrors() []*NodeError {
	if x != nil {
		return x.NodeErrors
	}
	return nil
}

func (x *NodeStatusFull) GetFetchError() string {
	if x != nil {
		return x.FetchError
	}
	return ""
}

func (x *NodeStatusFull) GetLastPushTimeUnixNs() int64 {
	if x != nil {
		return x.LastPushTimeUnixNs
	}
	return 0
}

func (x *NodeStatusFull) GetStatusSource() string {
	if x != nil {
		return x.StatusSource
	}
	return ""
}

func (x *NodeStatusFull) GetNodePodInfo() *NodePodInfo {
	if x != nil {
		return x.NodePodInfo
	}
	return nil
}

func (x *NodeStatusFull) GetBpfEntries() []*BpfEntry {
	if x != nil {
		return x.BpfEntries
	}
	return nil
}

// NodeStatusDelta carries field-level updates; only set fields are applied.
type NodeStatusDelta struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo     *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	Peers        []*PeerStatus          `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	RoutingTable *RoutingTableInfo      `protobuf:"bytes,3,opt,name=routing_table,json=routingTable,proto3" json:"routing_table,omitempty"`
	HealthCheck  *HealthCheckStatus     `protobuf:"bytes,4,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	NodeErrors   []*NodeError           `protobuf:"bytes,5,rep,name=node_errors,json=nodeErrors,proto3" json:"node_errors,omitempty"`
	// Track which top-level fields are present in this delta.
	UpdatedFields []string    `protobuf:"bytes,15,rep,name=updated_fields,json=updatedFields,proto3" json:"updated_fields,omitempty"`
	BpfEntries    []*BpfEntry `protobuf:"bytes,6,rep,name=bpf_entries,json=bpfEntries,proto3" json:"bpf_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusDelta) Reset() {
	*x = NodeStatusDelta{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusDelta) ProtoMessage() {}

func (x *NodeStatusDelta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusDelta.ProtoReflect.Descriptor instead.
func (*NodeStatusDelta) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStatusDelta) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *NodeStatusDelta) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *NodeStatusDelta) GetRoutingTable() *RoutingTableInfo {
	if x != nil {
		return x.RoutingTable
	}
	return nil
}

func (x *NodeStatusDelta) GetHealthCheck() *HealthCheckStatus {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *NodeStatusDelta) GetNodeErrors() []*NodeError {
	if x != nil {
		return x.NodeErrors
	}
	return nil
}

func (x *NodeStatusDelta) GetUpdatedFields() []string {
	if x != nil {
		return x.UpdatedFields
	}
	return nil
}

func (x *NodeStatusDelta) GetBpfEntries() []*BpfEntry {
	if x != nil {
		return x.BpfEntries
	}
	return nil
}

// NodeInfo contains basic node identification and metadata.
type NodeInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SiteName           string                 `protobuf:"bytes,2,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	IsGateway          bool                   `protobuf:"varint,3,opt,name=is_gateway,json=isGateway,proto3" json:"is_gateway,omitempty"`
	PodCidrs           []string               `protobuf:"bytes,4,rep,name=pod_cidrs,json=podCidrs,proto3" json:"pod_cidrs,omitempty"`
	InternalIps        []string               `protobuf:"bytes,5,rep,name=internal_ips,json=internalIps,proto3" json:"internal_ips,omitempty"`
	ExternalIps        []string               `protobuf:"bytes,6,rep,name=external_ips,json=externalIps,proto3" json:"external_ips,omitempty"`
	BuildInfo          *BuildInfo             `protobuf:"bytes,7,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	WireGuard          *WireGuardStatusInfo   `protobuf:"bytes,8,opt,name=wire_guard,json=wireGuard,proto3" json:"wire_guard,omitempty"`
	K8SReady           string                 `protobuf:"bytes,9,opt,name=k8s_ready,json=k8sReady,proto3" json:"k8s_ready,omitempty"`
	ProviderId         string                 `protobuf:"bytes,10,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	OsImage            string                 `protobuf:"bytes,11,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	Kernel             string                 `protobuf:"bytes,12,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Kubelet            string                 `protobuf:"bytes,13,opt,name=kubelet,proto3" json:"kubelet,omitempty"`
	Arch               string                 `protobuf:"bytes,14,opt,name=arch,proto3" json:"arch,omitempty"`
	NodeOs             string                 `protobuf:"bytes,15,opt,name=node_os,json=nodeOs,proto3" json:"node_os,omitempty"`
	K8SLabels          map[string]string      `protobuf:"bytes,16,rep,name=k8s_labels,json=k8sLabels,proto3" json:"k8s_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	K8SUpdatedAtUnixNs int64                  `protobuf:"varint,17,opt,name=k8s_updated_at_unix_ns,json=k8sUpdatedAtUnixNs,proto3" json:"k8s_updated_at_unix_ns,omitempty"` // 0 means unset
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *NodeInfo) GetIsGateway() bool {
	if x != nil {
		return x.IsGateway
	}
	return false
}

func (x *NodeInfo) GetPodCidrs() []string {
	if x != nil {
		return x.PodCidrs
	}
	return nil
}

func (x *NodeInfo) GetInternalIps() []string {
	if x != nil {
		return x.InternalIps
	}
	return nil
}

func (x *NodeInfo) GetExternalIps() []string {
	if x != nil {
		return x.ExternalIps
	}
	return nil
}

func (x *NodeInfo) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *NodeInfo) GetWireGuard() *WireGuardStatusInfo {
	if x != nil {
		return x.WireGuard
	}
	return nil
}

func (x *NodeInfo) GetK8SReady() string {
	if x != nil {
		return x.K8SReady
	}
	return ""
}

func (x *NodeInfo) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *NodeInfo) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

func (x *NodeInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *NodeInfo) GetKubelet() string {
	if x != nil {
		return x.Kubelet
	}
	return ""
}

func (x *NodeInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *NodeInfo) GetNodeOs() string {
	if x != nil {
		return x.NodeOs
	}
	return ""
}

func (x *NodeInfo) GetK8SLabels() map[string]string {
	if x != nil {
		return x.K8SLabels
	}
	return nil
}

func (x *NodeInfo) GetK8SUpdatedAtUnixNs() int64 {
	if x != nil {
		return x.K8SUpdatedAtUnixNs
	}
	return 0
}

// BuildInfo contains build-time version information for a binary.
type BuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	BuildTime     string                 `protobuf:"bytes,3,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{5}
}

func (x *BuildInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BuildInfo) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *BuildInfo) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

// WireGuardStatusInfo contains WireGuard interface status.
type WireGuardStatusInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ListenPort    int32                  `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	PeerCount     int32                  `protobuf:"varint,4,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireGuardStatusInfo) Reset() {
	*x = WireGuardStatusInfo{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuardStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardStatusInfo) ProtoMessage() {}

func (x *WireGuardStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardStatusInfo.ProtoReflect.Descriptor instead.
func (*WireGuardStatusInfo) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{6}
}

func (x *WireGuardStatusInfo) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *WireGuardStatusInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireGuardStatusInfo) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *WireGuardStatusInfo) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

// PeerStatus contains information about a tunnel peer.
type PeerStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PeerType          string                 `protobuf:"bytes,2,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	SiteName          string                 `protobuf:"bytes,3,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	PodCidrGateways   []string               `protobuf:"bytes,4,rep,name=pod_cidr_gateways,json=podCidrGateways,proto3" json:"pod_cidr_gateways,omitempty"`
	SkipPodCidrRoutes bool                   `protobuf:"varint,5,opt,name=skip_pod_cidr_routes,json=skipPodCidrRoutes,proto3" json:"skip_pod_cidr_routes,omitempty"`
	RouteDistances    map[string]int32       `protobuf:"bytes,6,rep,name=route_distances,json=routeDistances,proto3" json:"route_distances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Tunnel            *PeerTunnelStatus      `protobuf:"bytes,7,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	RouteDestinations []string               `protobuf:"bytes,8,rep,name=route_destinations,json=routeDestinations,proto3" json:"route_destinations,omitempty"`
	HealthCheck       *HealthCheckPeerStatus `protobuf:"bytes,9,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{7}
}

func (x *PeerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PeerStatus) GetPeerType() string {
	if x != nil {
		return x.PeerType
	}
	return ""
}

func (x *PeerStatus) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *PeerStatus) GetPodCidrGateways() []string {
	if x != nil {
		return x.PodCidrGateways
	}
	return nil
}

func (x *PeerStatus) GetSkipPodCidrRoutes() bool {
	if x != nil {
		return x.SkipPodCidrRoutes
	}
	return false
}

func (x *PeerStatus) GetRouteDistances() map[string]int32 {
	if x != nil {
		return x.RouteDistances
	}
	return nil
}

func (x *PeerStatus) GetTunnel() *PeerTunnelStatus {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

func (x *PeerStatus) GetRouteDestinations() []string {
	if x != nil {
		return x.RouteDestinations
	}
	return nil
}

func (x *PeerStatus) GetHealthCheck() *HealthCheckPeerStatus {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

// PeerTunnelStatus contains per-link tunnel transport metrics.
type PeerTunnelStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Protocol            string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Interface           string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	PublicKey           string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint            string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,5,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	RxBytes             int64                  `protobuf:"varint,6,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes             int64                  `protobuf:"varint,7,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	LastHandshakeUnixNs int64                  `protobuf:"varint,8,opt,name=last_handshake_unix_ns,json=lastHandshakeUnixNs,proto3" json:"last_handshake_unix_ns,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PeerTunnelStatus) Reset() {
	*x = PeerTunnelStatus{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerTunnelStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerTunnelStatus) ProtoMessage() {}

func (x *PeerTunnelStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerTunnelStatus.ProtoReflect.Descriptor instead.
func (*PeerTunnelStatus) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{8}
}

func (x *PeerTunnelStatus) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PeerTunnelStatus) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *PeerTunnelStatus) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerTunnelStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerTunnelStatus) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PeerTunnelStatus) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *PeerTunnelStatus) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *PeerTunnelStatus) GetLastHandshakeUnixNs() int64 {
	if x != nil {
		return x.LastHandshakeUnixNs
	}
	return 0
}

// RoutingTableInfo contains routing table entries.
type RoutingTableInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Routes            []*RouteEntry          `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	ManagedRouteCount int32                  `protobuf:"varint,2,opt,name=managed_route_count,json=managedRouteCount,proto3" json:"managed_route_count,omitempty"`
	PendingRouteCount int32                  `protobuf:"varint,3,opt,name=pending_route_count,json=pendingRouteCount,proto3" json:"pending_route_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoutingTableInfo) Reset() {
	*x = RoutingTableInfo{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingTableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTableInfo) ProtoMessage() {}

func (x *RoutingTableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTableInfo.ProtoReflect.Descriptor instead.
func (*RoutingTableInfo) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{9}
}

func (x *RoutingTableInfo) GetRoutes() []*RouteEntry {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RoutingTableInfo) GetManagedRouteCount() int32 {
	if x != nil {
		return x.ManagedRouteCount
	}
	return 0
}

func (x *RoutingTableInfo) GetPendingRouteCount() int32 {
	if x != nil {
		return x.PendingRouteCount
	}
	return 0
}

// RouteEntry represents a deduplicated route.
type RouteEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Family        string                 `protobuf:"bytes,2,opt,name=family,proto3" json:"family,omitempty"` // "IPv4" or "IPv6"
	Table         int32                  `protobuf:"varint,3,opt,name=table,proto3" json:"table,omitempty"`
	NextHops      []*NextHop             `protobuf:"bytes,4,rep,name=next_hops,json=nextHops,proto3" json:"next_hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEntry) Reset() {
	*x = RouteEntry{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEntry) ProtoMessage() {}

func (x *RouteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEntry.ProtoReflect.Descriptor instead.
func (*RouteEntry) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{10}
}

func (x *RouteEntry) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteEntry) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *RouteEntry) GetTable() int32 {
	if x != nil {
		return x.Table
	}
	return 0
}

func (x *RouteEntry) GetNextHops() []*NextHop {
	if x != nil {
		return x.NextHops
	}
	return nil
}

// NextHop represents a single next-hop in a route.
type NextHop struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Gateway          string                 `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Device           string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Distance         int32                  `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Weight           int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Mtu              int32                  `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	RouteTypes       []*RouteType           `protobuf:"bytes,6,rep,name=route_types,json=routeTypes,proto3" json:"route_types,omitempty"`
	Expected         *OptionalBool          `protobuf:"bytes,7,opt,name=expected,proto3" json:"expected,omitempty"`
	Present          *OptionalBool          `protobuf:"bytes,8,opt,name=present,proto3" json:"present,omitempty"`
	PeerDestinations []string               `protobuf:"bytes,9,rep,name=peer_destinations,json=peerDestinations,proto3" json:"peer_destinations,omitempty"`
	Info             *NextHopInfo           `protobuf:"bytes,10,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NextHop) Reset() {
	*x = NextHop{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextHop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextHop) ProtoMessage() {}

func (x *NextHop) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextHop.ProtoReflect.Descriptor instead.
func (*NextHop) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{11}
}

func (x *NextHop) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *NextHop) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *NextHop) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *NextHop) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *NextHop) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *NextHop) GetRouteTypes() []*RouteType {
	if x != nil {
		return x.RouteTypes
	}
	return nil
}

func (x *NextHop) GetExpected() *OptionalBool {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *NextHop) GetPresent() *OptionalBool {
	if x != nil {
		return x.Present
	}
	return nil
}

func (x *NextHop) GetPeerDestinations() []string {
	if x != nil {
		return x.PeerDestinations
	}
	return nil
}

func (x *NextHop) GetInfo() *NextHopInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// OptionalBool wraps a boolean value so we can distinguish unset from false.
type OptionalBool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalBool) Reset() {
	*x = OptionalBool{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalBool) ProtoMessage() {}

func (x *OptionalBool) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalBool.ProtoReflect.Descriptor instead.
func (*OptionalBool) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{12}
}

func (x *OptionalBool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

// NextHopInfo contains metadata describing how a next-hop was derived.
type NextHopInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectName    string                 `protobuf:"bytes,1,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	ObjectType    string                 `protobuf:"bytes,2,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	RouteType     string                 `protobuf:"bytes,3,opt,name=route_type,json=routeType,proto3" json:"route_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextHopInfo) Reset() {
	*x = NextHopInfo{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextHopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextHopInfo) ProtoMessage() {}

func (x *NextHopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextHopInfo.ProtoReflect.Descriptor instead.
func (*NextHopInfo) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{13}
}

func (x *NextHopInfo) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *NextHopInfo) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *NextHopInfo) GetRouteType() string {
	if x != nil {
		return x.RouteType
	}
	return ""
}

// RouteType contains the protocol type and attributes for one contributor to a nexthop.
type RouteType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Attributes    []string               `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteType) Reset() {
	*x = RouteType{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteType) ProtoMessage() {}

func (x *RouteType) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteType.ProtoReflect.Descriptor instead.
func (*RouteType) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{14}
}

func (x *RouteType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RouteType) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// HealthCheckStatus contains aggregate health check service information.
type HealthCheckStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Healthy         bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Summary         string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	PeerCount       int32                  `protobuf:"varint,3,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	CheckedAtUnixNs int64                  `protobuf:"varint,4,opt,name=checked_at_unix_ns,json=checkedAtUnixNs,proto3" json:"checked_at_unix_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheckStatus) Reset() {
	*x = HealthCheckStatus{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckStatus) ProtoMessage() {}

func (x *HealthCheckStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckStatus.ProtoReflect.Descriptor instead.
func (*HealthCheckStatus) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckStatus) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *HealthCheckStatus) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *HealthCheckStatus) GetCheckedAtUnixNs() int64 {
	if x != nil {
		return x.CheckedAtUnixNs
	}
	return 0
}

// HealthCheckPeerStatus contains health check session status for a peer.
type HealthCheckPeerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Uptime        string                 `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Rtt           string                 `protobuf:"bytes,4,opt,name=rtt,proto3" json:"rtt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckPeerStatus) Reset() {
	*x = HealthCheckPeerStatus{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckPeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckPeerStatus) ProtoMessage() {}

func (x *HealthCheckPeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckPeerStatus.ProtoReflect.Descriptor instead.
func (*HealthCheckPeerStatus) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{16}
}

func (x *HealthCheckPeerStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HealthCheckPeerStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckPeerStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *HealthCheckPeerStatus) GetRtt() string {
	if x != nil {
		return x.Rtt
	}
	return ""
}

// NodeError describes a node-level error surfaced in status payloads.
type NodeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // Unix nanoseconds; 0 means unset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeError) Reset() {
	*x = NodeError{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeError) ProtoMessage() {}

func (x *NodeError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeError.ProtoReflect.Descriptor instead.
func (*NodeError) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{17}
}

func (x *NodeError) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NodeError) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// NodePodInfo contains information about the unbounded-net-node pod on a node.
type NodePodInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PodName         string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	StartTimeUnixNs int64                  `protobuf:"varint,2,opt,name=start_time_unix_ns,json=startTimeUnixNs,proto3" json:"start_time_unix_ns,omitempty"`
	Restarts        int32                  `protobuf:"varint,3,opt,name=restarts,proto3" json:"restarts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodePodInfo) Reset() {
	*x = NodePodInfo{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePodInfo) ProtoMessage() {}

func (x *NodePodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePodInfo.ProtoReflect.Descriptor instead.
func (*NodePodInfo) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{18}
}

func (x *NodePodInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *NodePodInfo) GetStartTimeUnixNs() int64 {
	if x != nil {
		return x.StartTimeUnixNs
	}
	return 0
}

func (x *NodePodInfo) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

// BpfEntry represents a single entry from the eBPF LPM trie tunnel maps.
type BpfEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Remote        string                 `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	InterfaceName string                 `protobuf:"bytes,4,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Vni           uint32                 `protobuf:"varint,6,opt,name=vni,proto3" json:"vni,omitempty"`
	Mtu           int32                  `protobuf:"varint,7,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Ifindex       uint32                 `protobuf:"varint,8,opt,name=ifindex,proto3" json:"ifindex,omitempty"`
	Healthy       bool                   `protobuf:"varint,9,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BpfEntry) Reset() {
	*x = BpfEntry{}
	mi := &file_internal_net_status_proto_status_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BpfEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BpfEntry) ProtoMessage() {}

func (x *BpfEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_net_status_proto_status_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BpfEntry.ProtoReflect.Descriptor instead.
func (*BpfEntry) Descriptor() ([]byte, []int) {
	return file_internal_net_status_proto_status_proto_rawDescGZIP(), []int{19}
}

func (x *BpfEntry) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *BpfEntry) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *BpfEntry) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *BpfEntry) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *BpfEntry) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *BpfEntry) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

func (x *BpfEntry) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *BpfEntry) GetIfindex() uint32 {
	if x != nil {
		return x.Ifindex
	}
	return 0
}

func (x *BpfEntry) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

var File_internal_net_status_proto_status_proto protoreflect.FileDescriptor

const file_internal_net_status_proto_status_proto_rawDesc = "" +
	"\n" +
	"&internal/net/status/proto/status.proto\x12\x16unboundednet.status.v1\"\xe8\x01\n" +
	"\x11NodeStatusMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12#\n" +
	"\rbase_revision\x18\x03 \x01(\x04R\fbaseRevision\x12>\n" +
	"\x06status\x18\x04 \x01(\v2&.unboundednet.status.v1.NodeStatusFullR\x06status\x12=\n" +
	"\x05delta\x18\x05 \x01(\v2'.unboundednet.status.v1.NodeStatusDeltaR\x05delta\"[\n" +
	"\rNodeStatusAck\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x9c\x05\n" +
	"\x0eNodeStatusFull\x12*\n" +
	"\x11timestamp_unix_ns\x18\x01 \x01(\x03R\x0ftimestampUnixNs\x12=\n" +
	"\tnode_info\x18\x02 \x01(\v2 .unboundednet.status.v1.NodeInfoR\bnodeInfo\x128\n" +
	"\x05peers\x18\x03 \x03(\v2\".unboundednet.status.v1.PeerStatusR\x05peers\x12M\n" +
	"\rrouting_table\x18\x04 \x01(\v2(.unboundednet.status.v1.RoutingTableInfoR\froutingTable\x12L\n" +
	"\fhealth_check\x18\x05 \x01(\v2).unboundednet.status.v1.HealthCheckStatusR\vhealthCheck\x12B\n" +
	"\vnode_errors\x18\x06 \x03(\v2!.unboundednet.status.v1.NodeErrorR\n" +
	"nodeErrors\x12\x1f\n" +
	"\vfetch_error\x18\a \x01(\tR\n" +
	"fetchError\x122\n" +
	"\x16last_push_time_unix_ns\x18\b \x01(\x03R\x12lastPushTimeUnixNs\x12#\n" +
	"\rstatus_source\x18\t \x01(\tR\fstatusSource\x12G\n" +
	"\rnode_pod_info\x18\n" +
	" \x01(\v2#.unboundednet.status.v1.NodePodInfoR\vnodePodInfo\x12A\n" +
	"\vbpf_entries\x18\v \x03(\v2 .unboundednet.status.v1.BpfEntryR\n" +
	"bpfEntries\"\xd5\x03\n" +
	"\x0fNodeStatusDelta\x12=\n" +
	"\tnode_info\x18\x01 \x01(\v2 .unboundednet.status.v1.NodeInfoR\bnodeInfo\x128\n" +
	"\x05peers\x18\x02 \x03(\v2\".unboundednet.status.v1.PeerStatusR\x05peers\x12M\n" +
	"\rrouting_table\x18\x03 \x01(\v2(.unboundednet.status.v1.RoutingTableInfoR\froutingTable\x12L\n" +
	"\fhealth_check\x18\x04 \x01(\v2).unboundednet.status.v1.HealthCheckStatusR\vhealthCheck\x12B\n" +
	"\vnode_errors\x18\x05 \x03(\v2!.unboundednet.status.v1.NodeErrorR\n" +
	"nodeErrors\x12%\n" +
	"\x0eupdated_fields\x18\x0f \x03(\tR\rupdatedFields\x12A\n" +
	"\vbpf_entries\x18\x06 \x03(\v2 .unboundednet.status.v1.BpfEntryR\n" +
	"bpfEntries\"\xc5\x05\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tsite_name\x18\x02 \x01(\tR\bsiteName\x12\x1d\n" +
	"\n" +
	"is_gateway\x18\x03 \x01(\bR\tisGateway\x12\x1b\n" +
	"\tpod_cidrs\x18\x04 \x03(\tR\bpodCidrs\x12!\n" +
	"\finternal_ips\x18\x05 \x03(\tR\vinternalIps\x12!\n" +
	"\fexternal_ips\x18\x06 \x03(\tR\vexternalIps\x12@\n" +
	"\n" +
	"build_info\x18\a \x01(\v2!.unboundednet.status.v1.BuildInfoR\tbuildInfo\x12J\n" +
	"\n" +
	"wire_guard\x18\b \x01(\v2+.unboundednet.status.v1.WireGuardStatusInfoR\twireGuard\x12\x1b\n" +
	"\tk8s_ready\x18\t \x01(\tR\bk8sReady\x12\x1f\n" +
	"\vprovider_id\x18\n" +
	" \x01(\tR\n" +
	"providerId\x12\x19\n" +
	"\bos_image\x18\v \x01(\tR\aosImage\x12\x16\n" +
	"\x06kernel\x18\f \x01(\tR\x06kernel\x12\x18\n" +
	"\akubelet\x18\r \x01(\tR\akubelet\x12\x12\n" +
	"\x04arch\x18\x0e \x01(\tR\x04arch\x12\x17\n" +
	"\anode_os\x18\x0f \x01(\tR\x06nodeOs\x12N\n" +
	"\n" +
	"k8s_labels\x18\x10 \x03(\v2/.unboundednet.status.v1.NodeInfo.K8sLabelsEntryR\tk8sLabels\x122\n" +
	"\x16k8s_updated_at_unix_ns\x18\x11 \x01(\x03R\x12k8sUpdatedAtUnixNs\x1a<\n" +
	"\x0eK8sLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\tBuildInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x1d\n" +
	"\n" +
	"build_time\x18\x03 \x01(\tR\tbuildTime\"\x92\x01\n" +
	"\x13WireGuardStatusInfo\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\x05R\n" +
	"listenPort\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x04 \x01(\x05R\tpeerCount\"\x9e\x04\n" +
	"\n" +
	"PeerStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tpeer_type\x18\x02 \x01(\tR\bpeerType\x12\x1b\n" +
	"\tsite_name\x18\x03 \x01(\tR\bsiteName\x12*\n" +
	"\x11pod_cidr_gateways\x18\x04 \x03(\tR\x0fpodCidrGateways\x12/\n" +
	"\x14skip_pod_cidr_routes\x18\x05 \x01(\bR\x11skipPodCidrRoutes\x12_\n" +
	"\x0froute_distances\x18\x06 \x03(\v26.unboundednet.status.v1.PeerStatus.RouteDistancesEntryR\x0erouteDistances\x12@\n" +
	"\x06tunnel\x18\a \x01(\v2(.unboundednet.status.v1.PeerTunnelStatusR\x06tunnel\x12-\n" +
	"\x12route_destinations\x18\b \x03(\tR\x11routeDestinations\x12P\n" +
	"\fhealth_check\x18\t \x01(\v2-.unboundednet.status.v1.HealthCheckPeerStatusR\vhealthCheck\x1aA\n" +
	"\x13RouteDistancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x93\x02\n" +
	"\x10PeerTunnelStatus\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x05 \x03(\tR\n" +
	"allowedIps\x12\x19\n" +
	"\brx_bytes\x18\x06 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\a \x01(\x03R\atxBytes\x123\n" +
	"\x16last_handshake_unix_ns\x18\b \x01(\x03R\x13lastHandshakeUnixNs\"\xae\x01\n" +
	"\x10RoutingTableInfo\x12:\n" +
	"\x06routes\x18\x01 \x03(\v2\".unboundednet.status.v1.RouteEntryR\x06routes\x12.\n" +
	"\x13managed_route_count\x18\x02 \x01(\x05R\x11managedRouteCount\x12.\n" +
	"\x13pending_route_count\x18\x03 \x01(\x05R\x11pendingRouteCount\"\x9a\x01\n" +
	"\n" +
	"RouteEntry\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x16\n" +
	"\x06family\x18\x02 \x01(\tR\x06family\x12\x14\n" +
	"\x05table\x18\x03 \x01(\x05R\x05table\x12<\n" +
	"\tnext_hops\x18\x04 \x03(\v2\x1f.unboundednet.status.v1.NextHopR\bnextHops\"\xad\x03\n" +
	"\aNextHop\x12\x18\n" +
	"\agateway\x18\x01 \x01(\tR\agateway\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x05R\bdistance\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12\x10\n" +
	"\x03mtu\x18\x05 \x01(\x05R\x03mtu\x12B\n" +
	"\vroute_types\x18\x06 \x03(\v2!.unboundednet.status.v1.RouteTypeR\n" +
	"routeTypes\x12@\n" +
	"\bexpected\x18\a \x01(\v2$.unboundednet.status.v1.OptionalBoolR\bexpected\x12>\n" +
	"\apresent\x18\b \x01(\v2$.unboundednet.status.v1.OptionalBoolR\apresent\x12+\n" +
	"\x11peer_destinations\x18\t \x03(\tR\x10peerDestinations\x127\n" +
	"\x04info\x18\n" +
	" \x01(\v2#.unboundednet.status.v1.NextHopInfoR\x04info\"$\n" +
	"\fOptionalBool\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"n\n" +
	"\vNextHopInfo\x12\x1f\n" +
	"\vobject_name\x18\x01 \x01(\tR\n" +
	"objectName\x12\x1f\n" +
	"\vobject_type\x18\x02 \x01(\tR\n" +
	"objectType\x12\x1d\n" +
	"\n" +
	"route_type\x18\x03 \x01(\tR\trouteType\"?\n" +
	"\tRouteType\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"attributes\x18\x02 \x03(\tR\n" +
	"attributes\"\x93\x01\n" +
	"\x11HealthCheckStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x03 \x01(\x05R\tpeerCount\x12+\n" +
	"\x12checked_at_unix_ns\x18\x04 \x01(\x03R\x0fcheckedAtUnixNs\"s\n" +
	"\x15HealthCheckPeerStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\tR\x06uptime\x12\x10\n" +
	"\x03rtt\x18\x04 \x01(\tR\x03rtt\"\\\n" +
	"\tNodeError\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\"q\n" +
	"\vNodePodInfo\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12+\n" +
	"\x12start_time_unix_ns\x18\x02 \x01(\x03R\x0fstartTimeUnixNs\x12\x1a\n" +
	"\brestarts\x18\x03 \x01(\x05R\brestarts\"\xe5\x01\n" +
	"\bBpfEntry\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12\x16\n" +
	"\x06remote\x18\x02 \x01(\tR\x06remote\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x12%\n" +
	"\x0einterface_name\x18\x04 \x01(\tR\rinterfaceName\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03vni\x18\x06 \x01(\rR\x03vni\x12\x10\n" +
	"\x03mtu\x18\a \x01(\x05R\x03mtu\x12\x18\n" +
	"\aifindex\x18\b \x01(\rR\aifindex\x12\x18\n" +
	"\ahealthy\x18\t \x01(\bR\ahealthyB;Z9github.com/Azure/unbounded-kube/internal/net/status/protob\x06proto3"

var (
	file_internal_net_status_proto_status_proto_rawDescOnce sync.Once
	file_internal_net_status_proto_status_proto_rawDescData []byte
)

func file_internal_net_status_proto_status_proto_rawDescGZIP() []byte {
	file_internal_net_status_proto_status_proto_rawDescOnce.Do(func() {
		file_internal_net_status_proto_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_net_status_proto_status_proto_rawDesc), len(file_internal_net_status_proto_status_proto_rawDesc)))
	})
	return file_internal_net_status_proto_status_proto_rawDescData
}

var file_internal_net_status_proto_status_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_net_status_proto_status_proto_goTypes = []any{
	(*NodeStatusMessage)(nil),     // 0: unboundednet.status.v1.NodeStatusMessage
	(*NodeStatusAck)(nil),         // 1: unboundednet.status.v1.NodeStatusAck
	(*NodeStatusFull)(nil),        // 2: unboundednet.status.v1.NodeStatusFull
	(*NodeStatusDelta)(nil),       // 3: unboundednet.status.v1.NodeStatusDelta
	(*NodeInfo)(nil),              // 4: unboundednet.status.v1.NodeInfo
	(*BuildInfo)(nil),             // 5: unboundednet.status.v1.BuildInfo
	(*WireGuardStatusInfo)(nil),   // 6: unboundednet.status.v1.WireGuardStatusInfo
	(*PeerStatus)(nil),            // 7: unboundednet.status.v1.PeerStatus
	(*PeerTunnelStatus)(nil),      // 8: unboundednet.status.v1.PeerTunnelStatus
	(*RoutingTableInfo)(nil),      // 9: unboundednet.status.v1.RoutingTableInfo
	(*RouteEntry)(nil),            // 10: unboundednet.status.v1.RouteEntry
	(*NextHop)(nil),               // 11: unboundednet.status.v1.NextHop
	(*OptionalBool)(nil),          // 12: unboundednet.status.v1.OptionalBool
	(*NextHopInfo)(nil),           // 13: unboundednet.status.v1.NextHopInfo
	(*RouteType)(nil),             // 14: unboundednet.status.v1.RouteType
	(*HealthCheckStatus)(nil),     // 15: unboundednet.status.v1.HealthCheckStatus
	(*HealthCheckPeerStatus)(nil), // 16: unboundednet.status.v1.HealthCheckPeerStatus
	(*NodeError)(nil),             // 17: unboundednet.status.v1.NodeError
	(*NodePodInfo)(nil),           // 18: unboundednet.status.v1.NodePodInfo
	(*BpfEntry)(nil),              // 19: unboundednet.status.v1.BpfEntry
	nil,                           // 20: unboundednet.status.v1.NodeInfo.K8sLabelsEntry
	nil,                           // 21: unboundednet.status.v1.PeerStatus.RouteDistancesEntry
}
var file_internal_net_status_proto_status_proto_depIdxs = []int32{
	2,  // 0: unboundednet.status.v1.NodeStatusMessage.status:type_name -> unboundednet.status.v1.NodeStatusFull
	3,  // 1: unboundednet.status.v1.NodeStatusMessage.delta:type_name -> unboundednet.status.v1.NodeStatusDelta
	4,  // 2: unboundednet.status.v1.NodeStatusFull.node_info:type_name -> unboundednet.status.v1.NodeInfo
	7,  // 3: unboundednet.status.v1.NodeStatusFull.peers:type_name -> unboundednet.status.v1.PeerStatus
	9,  // 4: unboundednet.status.v1.NodeStatusFull.routing_table:type_name -> unboundednet.status.v1.RoutingTableInfo
	15, // 5: unboundednet.status.v1.NodeStatusFull.health_check:type_name -> unboundednet.status.v1.HealthCheckStatus
	17, // 6: unboundednet.status.v1.NodeStatusFull.node_errors:type_name -> unboundednet.status.v1.NodeError
	18, // 7: unboundednet.status.v1.NodeStatusFull.node_pod_info:type_name -> unboundednet.status.v1.NodePodInfo
	19, // 8: unboundednet.status.v1.NodeStatusFull.bpf_entries:type_name -> unboundednet.status.v1.BpfEntry
	4,  // 9: unboundednet.status.v1.NodeStatusDelta.node_info:type_name -> unboundednet.status.v1.NodeInfo
	7,  // 10: unboundednet.status.v1.NodeStatusDelta.peers:type_name -> unboundednet.status.v1.PeerStatus
	9,  // 11: unboundednet.status.v1.NodeStatusDelta.routing_table:type_name -> unboundednet.status.v1.RoutingTableInfo
	15, // 12: unboundednet.status.v1.NodeStatusDelta.health_check:type_name -> unboundednet.status.v1.HealthCheckStatus
	17, // 13: unboundednet.status.v1.NodeStatusDelta.node_errors:type_name -> unboundednet.status.v1.NodeError
	19, // 14: unboundednet.status.v1.NodeStatusDelta.bpf_entries:type_name -> unboundednet.status.v1.BpfEntry
	5,  // 15: unboundednet.status.v1.NodeInfo.build_info:type_name -> unboundednet.status.v1.BuildInfo
	6,  // 16: unboundednet.status.v1.NodeInfo.wire_guard:type_name -> unboundednet.status.v1.WireGuardStatusInfo
	20, // 17: unboundednet.status.v1.NodeInfo.k8s_labels:type_name -> unboundednet.status.v1.NodeInfo.K8sLabelsEntry
	21, // 18: unboundednet.status.v1.PeerStatus.route_distances:type_name -> unboundednet.status.v1.PeerStatus.RouteDistancesEntry
	8,  // 19: unboundednet.status.v1.PeerStatus.tunnel:type_name -> unboundednet.status.v1.PeerTunnelStatus
	16, // 20: unboundednet.status.v1.PeerStatus.health_check:type_name -> unboundednet.status.v1.HealthCheckPeerStatus
	10, // 21: unboundednet.status.v1.RoutingTableInfo.routes:type_name -> unboundednet.status.v1.RouteEntry
	11, // 22: unboundednet.status.v1.RouteEntry.next_hops:type_name -> unboundednet.status.v1.NextHop
	14, // 23: unboundednet.status.v1.NextHop.route_types:type_name -> unboundednet.status.v1.RouteType
	12, // 24: unboundednet.status.v1.NextHop.expected:type_name -> unboundednet.status.v1.OptionalBool
	12, // 25: unboundednet.status.v1.NextHop.present:type_name -> unboundednet.status.v1.OptionalBool
	13, // 26: unboundednet.status.v1.NextHop.info:type_name -> unboundednet.status.v1.NextHopInfo
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_internal_net_status_proto_status_proto_init() }
func file_internal_net_status_proto_status_proto_init() {
	if File_internal_net_status_proto_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_net_status_proto_status_proto_rawDesc), len(file_internal_net_status_proto_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_net_status_proto_status_proto_goTypes,
		DependencyIndexes: file_internal_net_status_proto_status_proto_depIdxs,
		MessageInfos:      file_internal_net_status_proto_status_proto_msgTypes,
	}.Build()
	File_internal_net_status_proto_status_proto = out.File
	file_internal_net_status_proto_status_proto_goTypes = nil
	file_internal_net_status_proto_status_proto_depIdxs = nil
}
